#!/usr/bin/env bash
# unblock-coordinator.sh — the operator-side steps the Claude Code tool policy refuses the
# coordinator (secret-store writes and production reads), run once by the user.
#
#   ALERT_EMAIL=<on-call address> bash infra/rollout/unblock-coordinator.sh
#
# Idempotent: a parameter, topic or subscription that already exists is kept. If the monitor
# DSN exists but this run generated a new monitor password, the script stops and says how to
# rebuild it (it never overwrites a secret). Secrets are generated into a 0700/0600 temp
# directory, passed to AWS by `file://`, shredded (or removed) on exit and never printed. Uses
# the default AWS profile (the stale AWS_* exports are dropped, CLAUDE.md "AWS access from this
# host"), region us-east-1 (AWS_REGION overrides). New SecureStrings use the KMS key of
# /model-inference/pg_journal_url. Reads: pg_journal_url (to derive the monitor DSN's
# host/db/sslmode/Supavisor suffix exactly as 55-runtime-login.sh does), the box inventory
# (read-only step 10). Writes: three SSM SecureStrings, the SNS topic (create is idempotent),
# one SNS subscription, one inventory log. The box role's sns:Publish grant is NOT done here
# (the role is shared with another box; infra/README.md keeps it untouched): see the end.
# After it: rollout.md W10b (55-runtime-login.sh) must run once before the first 50-install
# that picks up monitor_database_url — until then infrx_monitor is NOLOGIN (0021).
set -euo pipefail

REPO=$(git rev-parse --show-toplevel)
cd "$REPO"
aws() { env -u AWS_ACCESS_KEY_ID -u AWS_SECRET_ACCESS_KEY -u AWS_SESSION_TOKEN aws --region "${AWS_REGION:-us-east-1}" "$@"; }
INSTANCE=${INSTANCE:-i-0e8449a4ffca29bab}
TOPIC_NAME=${TOPIC_NAME:-infrx-pilot-alerts}
ALERT_EMAIL=${ALERT_EMAIL:-}
PREFIX=/model-inference
rc=0
step() { printf '\n### %s\n' "$*"; }
# The parameter's version, or return 1 only for ParameterNotFound; any other error stops the run
# (the message carries the parameter NAME, never a value).
have() {
  local e
  if e=$(aws ssm get-parameter --name "$1" --query Parameter.Version --output text 2>&1); then echo "$e"; return 0; fi
  case $e in *ParameterNotFound*) return 1 ;; *) echo "$1: ${e%%$'\n'*}" >&2; exit 4 ;; esac
}

work=$(umask 077; mktemp -d)
cleanup() { find "$work" -type f -exec shred -u {} + 2>/dev/null || true; rm -rf -- "$work"; }
trap cleanup EXIT

step "0 identity"
aws sts get-caller-identity --query '[Account,Arn]' --output text

step "1 SSM SecureStrings: the two dedicated-login passwords (55-runtime-login.sh, W10b)"
kid=$(aws ssm describe-parameters --parameter-filters "Key=Name,Values=$PREFIX/pg_journal_url" --query 'Parameters[0].KeyId' --output text 2>/dev/null || true)
keyarg=(); case ${kid:-None} in None|"") ;; *) keyarg=(--key-id "$kid"); echo "KMS key: the one pg_journal_url uses" ;; esac
new_monitor=
for name in infrx_runtime_password infrx_monitor_password; do
  p="$PREFIX/$name"
  if v=$(have "$p"); then
    echo "$p exists (version $v): kept"
  else
    (umask 077; python3 -c 'import secrets, sys; sys.stdout.write(secrets.token_hex(24))' > "$work/$name")   # 48 hex chars, no newline
    aws ssm put-parameter --name "$p" --type SecureString "${keyarg[@]}" \
      --description "${name%_password} login password for 55-runtime-login.sh (W10b; RV-09, D10 wiring 6); generated by unblock-coordinator.sh $(date -u +%F)" \
      --value "file://$work/$name" --query Version --output text | sed "s|^|$p created, version |"
    [ "$name" = infrx_monitor_password ] && new_monitor=1
  fi
done

step "2 SSM SecureString: the monitor DSN (preflight leaf; O4 MONITOR_DSN_PARAM)"
p="$PREFIX/monitor_database_url"
if v=$(have "$p"); then
  if [ -n "$new_monitor" ]; then
    echo "$p exists (version $v) but $PREFIX/infrx_monitor_password was just generated: the DSN carries an old password." >&2
    echo "Delete the DSN parameter (aws ssm delete-parameter --name $p) and rerun this script to rebuild it." >&2
    exit 5
  fi
  echo "$p exists (version $v): kept"
else
  aws ssm get-parameter --with-decryption --name "$PREFIX/pg_journal_url" --query Parameter.Value --output text > "$work/owner"
  aws ssm get-parameter --with-decryption --name "$PREFIX/infrx_monitor_password" --query Parameter.Value --output text > "$work/monpw"
  python3 - "$work" <<'PY'
import os, re, sys, urllib.parse
w = sys.argv[1]
owner = open(f"{w}/owner").read().strip()
pw = open(f"{w}/monpw").read().strip()
u = urllib.parse.urlsplit(owner)
if u.scheme not in ("postgres", "postgresql") or not u.hostname or not u.username:
    sys.exit("pg_journal_url is not a postgres URL with a host and a user: refused")
user = urllib.parse.unquote(u.username)
suffix = "." + user.split(".", 1)[1] if "." in user else ""          # Supavisor: <role>.<project-ref>
host = f"[{u.hostname}]" if ":" in u.hostname else u.hostname
db = (u.path or "/postgres").lstrip("/") or "postgres"
sslmode = dict(urllib.parse.parse_qsl(u.query)).get("sslmode", "require")
q = lambda s: urllib.parse.quote(s, safe="")
dsn = f"postgresql://{q('infrx_monitor' + suffix)}:{q(pw)}@{host}:6543/{db}?sslmode={sslmode}"
if not re.fullmatch(r"postgresql://\S+", dsn) or any(c in dsn for c in "\n\r\0'\"\\"):
    sys.exit("the derived DSN has a forbidden shape (preflight would refuse it): refused")
fd = os.open(f"{w}/dsn", os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
os.write(fd, dsn.encode()); os.close(fd)
print(f"monitor DSN derived: user infrx_monitor{'.<project-ref>' if suffix else ''}, host {u.hostname.split('.')[0]}…, port 6543, db {db}, sslmode {sslmode}")
PY
  aws ssm put-parameter --name "$p" --type SecureString "${keyarg[@]}" \
    --description "infrx_monitor DSN on the pooler :6543 (preflight leaf; O4 MONITOR_DSN_PARAM); password = $PREFIX/infrx_monitor_password; generated by unblock-coordinator.sh $(date -u +%F)" \
    --value "file://$work/dsn" --query Version --output text | sed "s|^|$p created, version |"
fi

step "3 SNS topic (create is idempotent) and the on-call subscription"
TOPIC_ARN=$(aws sns create-topic --name "$TOPIC_NAME" --query TopicArn --output text)
echo "topic $TOPIC_ARN"
if [ -z "$ALERT_EMAIL" ]; then
  echo "ALERT_EMAIL unset: no subscription made (rerun with ALERT_EMAIL=<address>)"
else
  subs=$(aws sns list-subscriptions-by-topic --topic-arn "$TOPIC_ARN" --query 'Subscriptions[].Endpoint' --output text | tr '\t' '\n')
  if printf '%s\n' "$subs" | grep -qixF -- "$ALERT_EMAIL"; then
    echo "$ALERT_EMAIL already subscribed (PendingConfirmation until the email is confirmed)"
  else
    aws sns subscribe --topic-arn "$TOPIC_ARN" --protocol email --notification-endpoint "$ALERT_EMAIL" --query SubscriptionArn --output text
    echo "subscription requested for $ALERT_EMAIL: click the confirmation link AWS emails"
  fi
fi

step "4 P-06: the read-only box inventory (docker/buildx versions, checkout, units, env NAMES, containers, edge)"
out="research/plan/evidence/coordinator/inventory"
mkdir -p "$out"
log="$out/10-inventory-$(date -u +%Y%m%dT%H%M%SZ).log"
if INSTANCE="$INSTANCE" TIMEOUT_S="${TIMEOUT_S:-600}" REGION="${AWS_REGION:-us-east-1}" \
     infra/rollout/ssm.sh infra/rollout/steps/10-inventory.sh > "$log" 2>&1; then
  echo "inventory saved: $log ($(wc -l < "$log") lines) — the coordinator reads it for the P-06 digests and the PINNED list"
else
  echo "inventory step FAILED: see $log"; rc=1
fi

step "done (exit $rc)"
cat <<EOF
Created/kept: $PREFIX/infrx_runtime_password, $PREFIX/infrx_monitor_password, $PREFIX/monitor_database_url;
topic $TOPIC_ARN; SNS subscription (if ALERT_EMAIL); inventory log under $out/.
Then: W10b (55-runtime-login.sh) must run once before the first 50-install that picks up monitor_database_url.
Manual, one command (the box role is shared with another box, so this script does not touch it):
  aws iam put-role-policy --role-name bootcamp-instance-role --policy-name infrx-pilot-alerts-sns-publish \\
    --policy-document '{"Version":"2012-10-17","Statement":[{"Sid":"PublishPilotAlerts","Effect":"Allow","Action":"sns:Publish","Resource":"$TOPIC_ARN"}]}'
Still manual (hosted Supabase / decisions, not scriptable here): the PITR read token, the second user's
email confirmation, MEDIA_BASE_URL, the two pre-cutover key revocations, a fresh verified hosted dump,
the hosted backup rehearsal + a hosted G6B issue+revoke, the production-needle guard decision (4 offenders).
EOF
exit "$rc"
