#!/usr/bin/env node
// L1's mutant runner (R32; LANE-RULES addendum): every L1 decision is one edit that a case it names
// must fail by assertion. A stale `find`, a load failure or a failure in an undeclared case is not a
// kill. Pattern and judging follow apps/app/tests/u/run-mutants.mjs.
// Usage: node tests/l/shell/run-mutants.mjs [--only ID,ID]
import { m, runMutants } from "./harness.mjs";

const SUITE = ["access", "config", "request", "guard", "boundary", "session", "shapes"].map((f) => `tests/l/shell/${f}.test.ts`);

const ACCESS = "lib/auth/access.ts";
const MEMBERS = "lib/auth/memberships.ts";
const CONFIG = "lib/auth/config.ts";
const SHAPES = "lib/services/shapes.ts"; // LAB-10
const REQUEST = "lib/auth/request.ts";
const GUARD = "lib/auth/guard.ts";
const ACTION = "lib/auth/actions.ts";
const LAYOUT = "app/(provider)/layout.tsx";
const NEXT = "next.config.ts";
const SIGNIN = "lib/auth/sign-in.ts";
const ROUTES = "lib/auth/routes.ts";
const FORM = "lib/auth/sign-in-form.tsx";

const C = {
  a01: "L1-A01 a signed-in user with no provider membership (consumer-only) is denied",
  a02: "L1-A02 a single membership is selected without asking",
  a03: "L1-A03 several memberships and no valid choice ask the user to select",
  a04: "L1-A04 a cookie naming a provider the user is not a member of selects nothing",
  a05: "L1-A05 a failed membership read is unavailable, never denied and never a workspace",
  a06: "L1-A06 a signed-out request is signed-out and never reads memberships",
  a07: "L1-A07 the selection action accepts only one of the user's own workspaces",
  a08: "L1-A08 the denial copy keeps consumer onboarding in the App: no signup, credits or onboarding offer",
  a09: "L1-A09 a page needs a selected workspace; the selection action needs a provider session",
  m01: "L1-M01 the membership read is the named RPC over the user's own session, with no identity argument",
  m02: "L1-M02 an RPC error or a thrown transport is unavailable",
  m03: "L1-M03 a malformed, unknown-role or duplicate row fails the whole read closed",
  c01: "L1-C01 the origin is explicit: development defaults to port 3100, production needs its own https origin",
  c02: "L1-C02 cookies are secure exactly when the origin is https",
  c03: "L1-C03 the Lab session cookie is its own and host-only: never the App's name, never a domain",
  c04: "L1-C04 the workspace preference cookie is http-only and bounded",
  c05: "L1-C05 every Lab response is private and no-store, and does not advertise the framework",
  h01: "L1-H01 a record id is a lowercase v4 UUID, whole; a read-back id is any UUID in either case, whole",
  h02: "L1-H02 a USD amount is exact to 1e-8: eight decimals, no leading zero, at most twelve integer digits",
  h03: "L1-H03 a digest is sha256 and exactly 64 lowercase hex",
  c06: "L1-C06 every Lab family reads LAB_API_URL first, then only its own old name; an empty value is unset",
  r01: "L1-R01 a misconfigured Lab is unavailable and builds no client",
  r02: "L1-R02 the session client is the Lab's: its cookie options, its env, and the request's cookie store",
  r03: "L1-R03 the user comes from the session and the workspace from the Lab's cookie, re-checked against memberships",
  g01: "L1-G01 a page gets a workspace only when one is selected: the picker state is a 404, never the first workspace",
  g02: "L1-G02 the selection action runs for any provider session and is a 404 for everyone else",
  g03: "L1-G03 the guard reads through the Lab's own session client and sends no identity",
  b01: "L1-B01 every page, route, provider layout and server action calls the provider guard",
  b02: "L1-B02 the provider layout renders its children only for a ready workspace",
  b03: "L1-B03 the selection action stores the membership it validated, never the submitted value",
  b04: "L1-B04 the Lab never imports the App: shared code comes only from packages/shared",
  b05: "L1-B05 a signed-out visitor gets the Lab sign-in form, and every signed-in state can sign out",
  s01: "L1-S01 sign-in sets the Lab session through the Lab's own client and lands on the home page",
  s02: "L1-S02 a failed or impossible sign-in is a fixed notice: never the auth server's words, never a session",
  s03: "L1-S03 sign-out ends the Lab session and forgets the workspace preference",
  s04: "L1-S04 the email-link callback verifies the code or token on the Lab client and only ever returns home",
  s05: "L1-S05 the proxy refreshes the Lab session cookie on the response and never redirects",
};

const MUTANTS = [
  m("L1-X01", "a consumer-only user gets the workspace picker", ACCESS, '  if (workspaces.length === 0) return { kind: "denied" };\n', "", [C.a01]),
  m("L1-X02", "an unmatched cookie falls back to the first workspace", ACCESS, "workspaces.find((m) => m.providerId === selected);", "(workspaces.find((m) => m.providerId === selected) ?? workspaces[0]);", [C.a03, C.a04]),
  m("L1-X03", "a single membership is not auto-selected", ACCESS, "workspaces.length === 1 ? workspaces[0] : ", "", [C.a02, C.a04]),
  m("L1-X04", "a failed read reads as denied", ACCESS, 'if (!read.ok) return { kind: "unavailable" };', 'if (!read.ok) return { kind: "denied" };', [C.a05]),
  m("L1-X05", "memberships are read before the session is checked", ACCESS,
    '  if ((await deps.userId()) === null) return { kind: "signed-out" };\n  return providerAccess(await deps.memberships(), deps.selected);',
    '  const read = await deps.memberships();\n  if ((await deps.userId()) === null) return { kind: "signed-out" };\n  return providerAccess(read, deps.selected);', [C.a06]),
  m("L1-X06", "a signed-out request is treated as signed in", ACCESS, '  if ((await deps.userId()) === null) return { kind: "signed-out" };\n', "", [C.a06, C.r03]),
  m("L1-X07", "the selection action falls back to any workspace", ACCESS, "find((m) => m.providerId === requested) ?? null;", "find((m) => m.providerId === requested) ?? sessionAccess(access)?.workspaces[0] ?? null;", [C.a07]),
  m("L1-X08", "the denial offers the consumer signup grant", ACCESS, "Consumer accounts use the infrx App.", "Sign up for 10,000 free credits.", [C.a08]),
  m("L1-X09", "a picker state counts as a selected workspace", ACCESS, 'access.kind === "ready" ? access.workspace : null', 'access.kind === "ready" ? access.workspace : access.kind === "select" ? access.workspaces[0] : null', [C.a09]),
  m("L1-X10", "a denied user counts as a provider session", ACCESS, 'access.kind === "select" || access.kind === "ready" ? access : null', 'access.kind === "unavailable" ? null : (access as SessionAccess)', [C.a09, C.a07]),
  m("L1-X11", "the membership read sends a client-side identity", MEMBERS, "client.rpc(MEMBERSHIPS_RPC)", 'client.rpc(MEMBERSHIPS_RPC, { user_id: "" })', [C.m01]),
  m("L1-X12", "an RPC error reads as no memberships", MEMBERS, "error ? { ok: false } :", "error ? { ok: true, memberships: [] } :", [C.m02]),
  m("L1-X13", "a transport failure reads as no memberships", MEMBERS, "  } catch {\n    return { ok: false };", "  } catch {\n    return { ok: true, memberships: [] };", [C.m02]),
  m("L1-X14", "an unknown role is accepted", MEMBERS, "    if (!ROLES.includes(role as Role)) return { ok: false };\n", "", [C.m03]),
  m("L1-X15", "a malformed row is skipped instead of failing the read", MEMBERS, "if (typeof id !== \"string\" || !UUID.test(id)) return { ok: false };", "if (typeof id !== \"string\" || !UUID.test(id)) continue;", [C.m03]),
  m("L1-X16", "a duplicate provider row is accepted", MEMBERS, "    if (memberships.some((m) => m.providerId === id)) return { ok: false };\n", "", [C.m03]),
  m("L1-X17", "an empty provider name is accepted", MEMBERS, 'typeof name !== "string" || name === ""', 'typeof name !== "string"', [C.m03]),
  m("L1-X18", "the RPC name drifts from the one membership read (R156)", MEMBERS, '"lab_provider_memberships"', '"lab_my_provider_memberships"', [C.m01]),
  m("L1-X20", "production accepts an http origin", CONFIG, '  if (production && url.protocol !== "https:") return null;\n', "", [C.c01]),
  m("L1-X21", "an origin with a path is accepted", CONFIG, '  if (url.origin !== raw.replace(/\\/$/, "")) return null; // an origin, no path\n', "", [C.c01]),
  m("L1-X19", "a missing Supabase URL is not a misconfiguration", CONFIG, "!supabaseUrl || !anonKey", "!anonKey", [C.c01]),
  m("L1-X22", "a missing anon key is not a misconfiguration", CONFIG, "!supabaseUrl || !anonKey", "!supabaseUrl", [C.c01]),
  m("L1-X41", "an unparsable origin throws out of the guard", CONFIG, "  let url: URL;\n  try {\n    url = new URL(raw);\n  } catch {\n    return null;\n  }\n", "  const url = new URL(raw);\n", [C.c01]),
  m("L1-X23", "cookies are never secure", CONFIG, 'secure: url.protocol === "https:"', "secure: false", [C.c02]),
  m("L1-X24", "the session cookie is widened to a parent domain", CONFIG, 'return { name: AUTH_COOKIE, path: "/",', 'return { name: AUTH_COOKIE, domain: ".callbill.ai", path: "/",', [C.c03]),
  m("L1-X25", "the workspace cookie is widened to a parent domain", CONFIG, 'return { httpOnly: true, path: "/",', 'return { httpOnly: true, domain: ".callbill.ai", path: "/",', [C.c03]),
  m("L1-X26", "the Lab rides on the App's session cookie name", CONFIG, '"sb-infrx-lab-auth"', '"sb-fcbnscgsymzdykendbrc-auth-token"', [C.c03]),
  m("L1-X27", "the workspace cookie is readable by scripts", CONFIG, "return { httpOnly: true,", "return { httpOnly: false,", [C.c04]),
  m("L1-X28", "the workspace cookie never expires", CONFIG, ", maxAge: 60 * 60 * 24 * 30 }", " }", [C.c04]),
  m("L1-X70", "LAB_API_URL is not read", CONFIG, "env.LAB_API_URL || env[LEGACY_API_URL[family]] || null", "env[LEGACY_API_URL[family]] || null", [C.c06]),
  m("L1-X71", "the old names are not a fallback", CONFIG, "env.LAB_API_URL || env[LEGACY_API_URL[family]] || null", "env.LAB_API_URL || null", [C.c06]),
  m("L1-X72", "an old name wins over LAB_API_URL", CONFIG, "env.LAB_API_URL || env[LEGACY_API_URL[family]] || null", "env[LEGACY_API_URL[family]] || env.LAB_API_URL || null", [C.c06]),
  m("L1-X73", "an empty LAB_API_URL counts as set", CONFIG, "env.LAB_API_URL || env[LEGACY_API_URL[family]] || null", "env.LAB_API_URL ?? env[LEGACY_API_URL[family]] ?? null", [C.c06]),
  m("L1-X74", "unset reads as undefined, not null", CONFIG, "env.LAB_API_URL || env[LEGACY_API_URL[family]] || null", "env.LAB_API_URL || env[LEGACY_API_URL[family]]", [C.c06]),
  m("L1-X75", "a family falls back to any family's old name", CONFIG, "env.LAB_API_URL || env[LEGACY_API_URL[family]] || null", "env.LAB_API_URL || Object.values(LEGACY_API_URL).map((n) => env[n]).find(Boolean) || null", [C.c06]),
  m("L1-X76", "the control fallback is not the deployed name", CONFIG, "control: \"LAB_CONTROL_URL\"", "control: \"LAB_CONTROL_API_URL\"", [C.c06]),
  m("L1-X77", "the traces fallback is not the deployed name", CONFIG, "traces: \"LAB_TRACES_API_URL\"", "traces: \"LAB_TRACE_API_URL\"", [C.c06]),
  m("L1-X78", "the evaluation fallback is not the deployed name", CONFIG, "evaluation: \"LAB_EVALS_API_URL\"", "evaluation: \"LAB_EVALUATION_API_URL\"", [C.c06]),
  m("L1-X79", "the pipelines fallback is not the deployed name", CONFIG, "pipelines: \"LAB_PIPELINES_API_URL\"", "pipelines: \"LAB_PIPELINE_API_URL\"", [C.c06]),
  m("L1-X80", "the releases fallback is not the deployed name", CONFIG, "releases: \"LAB_RELEASES_API_URL\"", "releases: \"LAB_ROLLOUTS_API_URL\"", [C.c06]),
  m("L1-X81", "the datasets fallback is not the deployed name", CONFIG, "datasets: \"LAB_DATASETS_API_URL\"", "datasets: \"LAB_DATASET_API_URL\"", [C.c06]),
  m("L1-X82", "a record id may be any UUID version", SHAPES, "-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-", "-[0-9a-f]{4}-[0-9a-f]{4}-", [C.h01]),
  m("L1-X83", "a record id may carry text around it", SHAPES, "new RegExp(`^${UUID}$`)", "new RegExp(UUID)", [C.h01]),
  m("L1-X84", "a record id may be upper case", SHAPES, "new RegExp(`^${UUID}$`)", "new RegExp(`^${UUID}$`, \"i\")", [C.h01]),
  m("L1-X85", "a read-back id is case-sensitive", SHAPES, "[0-9a-f]{12}$/i;", "[0-9a-f]{12}$/;", [C.h01]),
  m("L1-X86", "a read-back id may be v4 only", SHAPES, "/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-", "/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-", [C.h01]),
  m("L1-X87", "a read-back id may lead with text", SHAPES, "UUID_ANY_RE = /^", "UUID_ANY_RE = /", [C.h01]),
  m("L1-X88", "a USD amount may have fewer than eight decimals", SHAPES, "\\.[0-9]{8}$/;", "\\.[0-9]{1,8}$/;", [C.h02]),
  m("L1-X89", "a USD amount may lead with zero", SHAPES, "(0|[1-9][0-9]{0,11})", "[0-9]{1,12}", [C.h02]),
  m("L1-X90", "a USD amount may exceed twelve integer digits", SHAPES, "[1-9][0-9]{0,11})", "[1-9][0-9]*)", [C.h02]),
  m("L1-X91", "a USD amount may trail text", SHAPES, "[0-9]{8}$/;", "[0-9]{8}/;", [C.h02]),
  m("L1-X92", "a digest may be any hex length", SHAPES, "sha256:[0-9a-f]{64}$/;", "sha256:[0-9a-f]+$/;", [C.h03]),
  m("L1-X93", "a digest may name another algorithm", SHAPES, "DIGEST_RE = /^sha256:", "DIGEST_RE = /^[a-z0-9]+:", [C.h03]),
  m("L1-X29", "Lab responses become cacheable", NEXT, '"private, no-store"', '"public, max-age=60"', [C.c05]),
  m("L1-X30", "the framework header is advertised", NEXT, "poweredByHeader: false", "poweredByHeader: true", [C.c05]),
  m("L1-X31", "a misconfigured Lab still builds a client", REQUEST, '  if (config === null) return { kind: "unavailable" };\n', "  if (config === null) return resolveAccess({ userId: async () => null, memberships: async () => ({ ok: false }), selected: undefined });\n  makeClient(\"\", \"\", {} as ClientOptions);\n", [C.r01]),
  m("L1-X32", "the session client drops the Lab cookie options", REQUEST, "    cookieOptions: authCookieOptions(config),\n", "    cookieOptions: { ...authCookieOptions(config), name: undefined },\n", [C.r02]),
  m("L1-X33", "refreshed session cookies are dropped", REQUEST, "for (const { name, value, options } of list) store.set(name, value, options);", "void list;", [C.r02]),
  m("L1-X34", "a read-only cookie store throws out of setAll", REQUEST, "        } catch {\n", "        } catch (error) {\n          throw error;\n", [C.r02]),
  m("L1-X35", "the workspace preference is ignored", REQUEST, "selected: store.get(WORKSPACE_COOKIE)?.value,", "selected: undefined,", [C.r03]),
  m("L1-X36", "the selection action skips the provider guard", ACTION, "const access = await requireProviderSession();", 'const access = { kind: "denied" } as const;', [C.b01]),
  m("L1-X37", "the picker state renders the page", LAYOUT, "        <Workspaces workspaces={access.workspaces} />\n        <SignOut />\n      </main>", "        <Workspaces workspaces={access.workspaces} />\n        <SignOut />\n        {children}\n      </main>", [C.b02]),
  m("L1-X38", "the provider layout is prerendered", LAYOUT, 'export const dynamic = "force-dynamic";', "", [C.b02]),
  m("L1-X39", "the action stores the submitted value", ACTION, ".set(WORKSPACE_COOKIE, chosen.providerId,", '.set(WORKSPACE_COOKIE, String(formData.get("providerId")),', [C.b03]),
  // Fix round (0-L1-R-2): guard.ts is run by guard.test.ts; X42 is the reviewer's type-correct H2'.
  m("L1-X42", "a page under the picker state gets the first workspace (H2')", GUARD, "const workspace = readyWorkspace(await providerAccessForRequest());",
    "const access = await providerAccessForRequest();\n  const workspace = readyWorkspace(access) ?? sessionAccess(access)?.workspaces[0] ?? null;", [C.g01]),
  m("L1-X43", "the page guard renders without a workspace", GUARD, "  if (workspace === null) notFound();\n", "", [C.g01]),
  m("L1-X44", "the action guard runs without a provider session", GUARD, "  if (access === null) notFound();\n", "", [C.g02]),
  m("L1-X45", "the action guard admits any signed-in state", GUARD, "const access = sessionAccess(await providerAccessForRequest());", "const access = (await providerAccessForRequest()) as SessionAccess;", [C.g02]),
  m("L1-X46", "the guard's client drops the Lab cookie options", GUARD, "createServerClient(url, key, options)", "createServerClient(url, key, { cookies: options.cookies })", [C.g03]),
  m("L1-X47", "the guard's membership read sends an identity", GUARD, "rpc: (name) => client.rpc(name)", 'rpc: (name) => client.rpc(name, { user_id: "" })', [C.g03]),
  // Fix round (0-L1-R-1): server actions in every form Next accepts; X48 is the reviewer's H1.
  m("L1-X48", "an unguarded arrow-const server action (H1)", ACTION, '  redirect("/");\n}\n',
    '  redirect("/");\n}\n\nexport const peekWorkspaces = async (formData: FormData) => {\n  return String(formData.get("providerId"));\n};\n', [C.b01]),
  m("L1-X49", "an unguarded default-export server action", ACTION, '  redirect("/");\n}\n', '  redirect("/");\n}\n\nexport default async function peek() {\n  return 1;\n}\n', [C.b01]),
  m("L1-X50", "an unguarded inline server action in the provider layout", LAYOUT, "<form action={selectWorkspace}>", '<form action={async () => { "use server"; }}>', [C.b01]),
  // WR-L1-6 (LW2): sign-in, sign-out, the email-link callback and the proxy refresh.
  m("L1-X51", "sign-in uses a client without the Lab cookie options", SIGNIN, "clientOptions(config, await cookies()))", "{ cookies: clientOptions(config, await cookies()).cookies })", [C.s01, C.s03]),
  m("L1-X52", "a failed sign-in still lands home", SIGNIN, '  if (error) return { error: "failed" };\n', "", [C.s02]),
  m("L1-X53", "a sign-in without a password is sent anyway", SIGNIN, '  if (typeof email !== "string" || typeof password !== "string") return { error: "failed" };\n', "", [C.s02]),
  m("L1-X54", "a misconfigured Lab reads as a wrong password", SIGNIN, 'if (client === null) return { error: "unavailable" };', 'if (client === null) return { error: "failed" };', [C.s02]),
  m("L1-X55", "sign-out keeps the workspace preference", SIGNIN, "  (await cookies()).delete(WORKSPACE_COOKIE);\n", "", [C.s03]),
  m("L1-X56", "sign-out never ends the session", SIGNIN, "  await client?.auth.signOut().catch(() => undefined);\n", "", [C.s03]),
  m("L1-X57", "an unguarded export beside the public sign-in actions", SIGNIN, "export async function signOut()", "export async function peek() {\n  return 1;\n}\n\nexport async function signOut()", [C.b01]),
  m("L1-X58", "the callback follows the link's next parameter", ROUTES, 'new URL("/", config?.origin ?? request.nextUrl.origin)', 'new URL(request.nextUrl.searchParams.get("next") ?? "/", config?.origin ?? request.nextUrl.origin)', [C.s04]),
  m("L1-X59", "the callback redirects to the request's Host", ROUTES, 'new URL("/", config?.origin ?? request.nextUrl.origin)', 'new URL("/", request.nextUrl.origin)', [C.s04]),
  m("L1-X60", "the callback verifies signup and recovery links", ROUTES, '(type === "magiclink" || type === "email")', "type", [C.s04]),
  m("L1-X61", "the callback drops the session cookie", ROUTES, "    for (const { name, value, options } of list) response.cookies.set(name, value, options);\n  }).auth;", "    void list;\n  }).auth;", [C.s04]),
  m("L1-X62", "the request client drops the Lab cookie options", ROUTES, "    cookieOptions: authCookieOptions(config),\n", "", [C.s04, C.s05]),
  m("L1-X63", "the proxy drops the refreshed cookie", ROUTES, "    for (const { name, value, options } of list) response.cookies.set(name, value, options);\n  });\n  await", "    void list;\n  });\n  await", [C.s05]),
  m("L1-X64", "the proxy never refreshes the session", ROUTES, "  await client.auth.getUser().catch(() => undefined);\n", "", [C.s05]),
  m("L1-X65", "the proxy redirects a signed-out request", ROUTES, "  await client.auth.getUser().catch(() => undefined);\n  return response;", '  await client.auth.getUser().catch(() => undefined);\n  return NextResponse.redirect(new URL("/", request.url));', [C.s05]),
  m("L1-X66", "a signed-out visitor gets no sign-in form", LAYOUT, "        <SignInForm />\n", "", [C.b05]),
  m("L1-X67", "a consumer-only user cannot sign out", LAYOUT, '      {access.kind === "denied" && <SignOut />}\n', "", [C.b05]),
  m("L1-X68", "the form shows the action's raw error", FORM, "SIGN_IN_COPY[state.error]", "String(state.error)", [C.b05]),
  m("L1-X69", "the sign-in notice repeats the auth server", ACCESS, '"That email and password did not sign you in.', '"Invalid login credentials. That email and password did not sign you in.', [C.s02]),
  m("L1-X40", "the Lab imports the App's code", ACCESS, "export const ROLES", 'import type {} from "../../../app/lib/types.ts";\nexport const ROLES', [C.b04]),
];

process.exit(await runMutants({ suite: SUITE, prefix: "L1", mutants: MUTANTS }));
