#!/usr/bin/env node
// L1's mutant runner (R32; LANE-RULES addendum): every L1 decision is one edit that a case it names
// must fail by assertion. A stale `find`, a load failure or a failure in an undeclared case is not a
// kill. Pattern and judging follow apps/app/tests/u/run-mutants.mjs.
// Usage: node tests/l/shell/run-mutants.mjs [--only ID,ID]
import { m, runMutants } from "./harness.mjs";

const SUITE = [...["access", "config", "request", "guard", "boundary", "session", "shapes"].map((f) => `tests/l/shell/${f}.test.ts`), "tests/boundary/api.test.ts"];

const ACCESS = "lib/auth/access.ts";
const MEMBERS = "lib/auth/memberships.ts";
const CONFIG = "lib/auth/config.ts";
const SHAPES = "lib/services/shapes.ts"; // LAB-10
const REQUEST = "lib/auth/request.ts";
const GUARD = "lib/auth/guard.ts";
const ACTION = "lib/auth/actions.ts";
const LAYOUT = "app/(provider)/layout.tsx";
const NEXT = "next.config.ts";
const SIGNIN = "lib/auth/sign-in.ts";
const SESSION = "lib/auth/session.ts";
const COMMON = "lib/services/common.ts";
const PORT = "lib/api/index.ts";
const REVIEW = "lib/services/review/index.ts";
const ROUTES = "lib/auth/routes.ts";
const FORM = "lib/auth/sign-in-form.tsx";
const PORTS = ["control", "evaluation", "pipelines"].map((f) => `lib/services/${f}/port.ts`); // LAB-07: they re-export access.ts's holds

const C = {
  a01: "L1-A01 a signed-in user with no provider membership (consumer-only) is denied",
  a02: "L1-A02 a single membership is selected without asking",
  a03: "L1-A03 several memberships and no valid choice ask the user to select",
  a04: "L1-A04 a cookie naming a provider the user is not a member of selects nothing",
  a05: "L1-A05 a failed membership read is unavailable, never denied and never a workspace; a dead session is signed-out",
  a06: "L1-A06 a signed-out request is signed-out and never reads memberships",
  a07: "L1-A07 the selection action accepts only one of the user's own workspaces",
  a08: "L1-A08 the denial copy keeps consumer onboarding in the App: no signup, credits or onboarding offer",
  a09: "L1-A09 a page needs a selected workspace; the selection action needs a provider session",
  a10: "L1-A10 holds() grants exactly the contracts/v2 ROLE_CAPABILITIES, for every role and capability",
  a11: "L1-A11 every family port answers capabilities from that one table, not a table of its own",
  m01: "L1-M01 the membership read is GET /lab/v1/workspaces as the user's own session, with no identity argument",
  m02: "L1-M02 an API failure or a thrown transport is unavailable; only a refused session (401) is signed-out",
  m03: "L1-M03 a malformed, unknown-role or duplicate row fails the whole read closed; an unknown capability grants nothing",
  m04: "L1-M04 a membership id is read back at any UUID version, either case (shapes UUID_ANY_RE, LAB-10)",
  c01: "L1-C01 the origin is explicit: development defaults to port 3100, production needs its own https origin",
  c02: "L1-C02 cookies are secure exactly when the origin is https",
  c03: "L1-C03 the Lab session cookies are its own, http-only and host-only: never the App's or Supabase's name, never a domain",
  c04: "L1-C04 the workspace preference and session cookies are http-only and bounded",
  c05: "L1-C05 every Lab response is private and no-store, and does not advertise the framework",
  h01: "L1-H01 a record id is a lowercase v4 UUID, whole; a read-back id is any UUID in either case, whole",
  h02: "L1-H02 a USD amount is exact to 1e-8: eight decimals, no leading zero, at most twelve integer digits",
  h03: "L1-H03 a digest is sha256 and exactly 64 lowercase hex",
  c06: "L1-C06 every Lab family reads LAB_API_URL only; the six old per-family names are read nowhere; an empty value is unset",
  r01: "L1-R01 a misconfigured Lab is unavailable and sends nothing",
  r02: "L1-R02 the read goes to LAB_API_URL as the session cookie's own token, and forwards no cookie",
  r03: "L1-R03 the user comes from the session and the workspace from the Lab's cookie, re-checked against memberships",
  g01: "L1-G01 a page gets a workspace only when one is selected: the picker state is a 404, never the first workspace",
  g02: "L1-G02 the selection action runs for any provider session and is a 404 for everyone else",
  g03: "L1-G03 the guard reads memberships from the API as the session's own token and sends no identity",
  b01: "L1-B01 every page, route, provider layout and server action calls the provider guard",
  b02: "L1-B02 the provider layout renders its children only for a ready workspace",
  b03: "L1-B03 the selection action stores the membership it validated, never the submitted value",
  b06: "L1-B06 the action, refusal-copy and preview boilerplate lives once, in lib/services/common.ts and components/preview-note.tsx",
  b07: "L1-B07 every page types its props with Next's PageProps and has a title; app code imports lib and components by @/",
  b04: "L1-B04 the Lab never imports the App: shared code comes only from packages/shared",
  b05: "L1-B05 a signed-out visitor gets the Lab sign-in form, and every signed-in state can sign out",
  s01: "L1-S01 sign-in posts the credentials to the auth facade, keeps the session in the Lab's http-only cookies and lands home",
  s02: "L1-S02 a failed or impossible sign-in is a fixed notice: never the auth server's words, never a session",
  s03: "L1-S03 sign-out ends the session at the auth facade, drops both session cookies and forgets the workspace preference",
  s04: "L1-S04 the email-link callback verifies the code or token at the auth facade and only ever returns home",
  a12: "L1-A12 holds() on a workspace answers from the API's capability set for it, not from the role table",
  a13: "L1-A13 an action lands by the workspace's own API capability set: withheld there, it is refused without a call",
  m05: "L1-M05 a workspace's feature availability is GET /lab/v1/capabilities for that provider; a failed read is unavailable, never disabled",
  t01: "L1-T01 no Lab production module reaches the database: no RPC, no table read, no Supabase client or setting",
  t02: "L1-T02 every API call the Lab makes is a documented operation: the Lab unit's export, or a Lab-shell route the gateway exports",
  t03: "L1-T03 the hand-typed Lab-shell routes are the gateway export's, path, method and record fields",
  s05: "L1-S05 the proxy refreshes a session near expiry at the auth facade, on the response and the request; it never redirects",
};

const MUTANTS = [
  m("L1-X01", "a consumer-only user gets the workspace picker", ACCESS, '  if (workspaces.length === 0) return { kind: "denied" };\n', "", [C.a01]),
  m("L1-X02", "an unmatched cookie falls back to the first workspace", ACCESS, "workspaces.find((m) => m.providerId === selected);", "(workspaces.find((m) => m.providerId === selected) ?? workspaces[0]);", [C.a03, C.a04]),
  m("L1-X03", "a single membership is not auto-selected", ACCESS, "workspaces.length === 1 ? workspaces[0] : ", "", [C.a02, C.a04]),
  m("L1-X07", "the selection action falls back to any workspace", ACCESS, "find((m) => m.providerId === requested) ?? null;", "find((m) => m.providerId === requested) ?? sessionAccess(access)?.workspaces[0] ?? null;", [C.a07]),
  m("L1-X08", "the denial offers the consumer signup grant", ACCESS, "Consumer accounts use the infrx App.", "Sign up for 10,000 free credits.", [C.a08]),
  m("L1-X09", "a picker state counts as a selected workspace", ACCESS, 'access.kind === "ready" ? access.workspace : null', 'access.kind === "ready" ? access.workspace : access.kind === "select" ? access.workspaces[0] : null', [C.a09]),
  m("L1-X10", "a denied user counts as a provider session", ACCESS, 'access.kind === "select" || access.kind === "ready" ? access : null', 'access.kind === "unavailable" ? null : (access as SessionAccess)', [C.a09, C.a07]),
  // AP-09 09c: the API's membership read, its capability set, the facade session (replace X04-X06, X11-X19, X22-X28, X31-X34, X46-X47, X51-X56, X61-X65, X70-X81, X97).
  m("L1-X04", "a failed read reads as denied", ACCESS, 'if (!read.ok) return { kind: read.reason };', 'if (!read.ok) return { kind: "denied" };', [C.a05]),
  m("L1-X05", "memberships are read before the session is checked", ACCESS,
    '  if (!deps.signedIn) return { kind: "signed-out" };\n  return providerAccess(await deps.memberships(), deps.selected);',
    '  const read = await deps.memberships();\n  if (!deps.signedIn) return { kind: "signed-out" };\n  return providerAccess(read, deps.selected);', [C.a06]),
  m("L1-X06", "a signed-out request is treated as signed in", ACCESS, '  if (!deps.signedIn) return { kind: "signed-out" };\n', "", [C.a06]),
  m("L1-X107", "a dead session reads as unavailable, not signed-out", ACCESS, 'if (!read.ok) return { kind: read.reason };', 'if (!read.ok) return { kind: "unavailable" };', [C.a05]),
  m("L1-X97", "holds ignores the role", ACCESS, "ROLE_CAPABILITIES[who] :", "CAPABILITIES :", [C.a10]),
  m("L1-X108", "a workspace answers from the role table, not the API's set", ACCESS, "(who.capabilities ?? ROLE_CAPABILITIES[who.role])", "ROLE_CAPABILITIES[who.role]", [C.a12]),
  m("L1-X109", "an actor without the API's set holds everything", ACCESS, "?? ROLE_CAPABILITIES[who.role])", "?? CAPABILITIES)", [C.a12]),
  m("L1-X110", "an action lands by the role table, not the workspace's API set", COMMON, "!holds(w, capability)", "!holds(w.role, capability)", [C.a13]),
  m("L1-X11", "the membership read sends a client-side identity", MEMBERS, 'api.call("get", "/lab/v1/workspaces")', 'api.call("get", "/lab/v1/workspaces", { query: { user_id: "" } })', [C.m01]),
  m("L1-X18", "the membership read drifts from AP-01's route", MEMBERS, '"get", "/lab/v1/workspaces")', '"get", "/lab/v1/memberships")', [C.m01]),
  m("L1-X12", "an API error reads as no memberships", MEMBERS, '{ ok: false, reason: "signed-out" } : UNAVAILABLE;', '{ ok: false, reason: "signed-out" } : { ok: true, memberships: [] };', [C.m02]),
  m("L1-X13", "every failure reads as signed-out", MEMBERS, "answer.error.status === 401 ?", "true ?", [C.m02]),
  m("L1-X111", "a refused session reads as unavailable", MEMBERS, '{ ok: false, reason: "signed-out" } : UNAVAILABLE;', "UNAVAILABLE : UNAVAILABLE;", [C.m02]),
  m("L1-X14", "an unknown role is accepted", MEMBERS, "    if (!ROLES.includes(role as Role)) return UNAVAILABLE;\n", "", [C.m03]),
  m("L1-X15", "a malformed row is skipped instead of failing the read", MEMBERS, 'if (typeof id !== "string" || !UUID.test(id)) return UNAVAILABLE;', 'if (typeof id !== "string" || !UUID.test(id)) continue;', [C.m03]),
  m("L1-X16", "a duplicate provider row is accepted", MEMBERS, "    if (memberships.some((m) => m.providerId === id)) return UNAVAILABLE;\n", "", [C.m03]),
  m("L1-X17", "an empty provider name is accepted", MEMBERS, 'typeof name !== "string" || name === ""', 'typeof name !== "string"', [C.m03]),
  m("L1-X112", "a non-list page reads as no memberships", MEMBERS, "if (!Array.isArray(data)) return UNAVAILABLE;", "if (!Array.isArray(data)) return { ok: true, memberships: [] };", [C.m03]),
  m("L1-X113", "a malformed capability set is accepted", MEMBERS, '    if (!Array.isArray(capabilities) || !capabilities.every((c) => typeof c === "string")) return UNAVAILABLE;\n', "", [C.m03]),
  m("L1-X114", "an unknown capability is trusted", MEMBERS, "const held = CAPABILITIES.filter((c) => capabilities.includes(c));", "const held = capabilities;", [C.m03]),
  m("L1-X115", "the feature read names no workspace", MEMBERS, "{ query: { provider_org_id: w.providerId } }", "{}", [C.m05]),
  m("L1-X116", "a failed feature read reads as no features", MEMBERS, 'if (typeof features !== "object" || features === null) return { ok: false };', 'if (typeof features !== "object" || features === null) return { ok: true, features: {} };', [C.m05]),
  m("L1-X117", "an unreadable feature state is shown", MEMBERS, "return readable ?", "return true ?", [C.m05]),
  m("L1-X19", "a missing LAB_API_URL is not a misconfiguration", CONFIG, "  if (!apiUrl) return null;\n", "", [C.c01]),
  m("L1-X22", "the API origin is the Lab's own", CONFIG, "return { origin: url.origin, apiUrl,", "return { origin: url.origin, apiUrl: url.origin,", [C.c01]),
  m("L1-X24", "the session cookies are widened to a parent domain", CONFIG, 'return { httpOnly: true, path: "/",', 'return { httpOnly: true, domain: ".callbill.ai", path: "/",', [C.c03]),
  m("L1-X26", "the Lab session cookie takes a Supabase-style name", CONFIG, '"infrx-lab-session"', '"sb-infrx-lab-auth"', [C.c03]),
  m("L1-X25", "the refresh token rides in the access token's cookie", CONFIG, '"infrx-lab-refresh"', '"infrx-lab-session"', [C.c03]),
  m("L1-X27", "the session cookies are readable by scripts", CONFIG, "return { httpOnly: true,", "return { httpOnly: false,", [C.c03, C.c04]),
  m("L1-X28", "the cookies never expire", CONFIG, ", maxAge: 60 * 60 * 24 * 30 }", " }", [C.c04]),
  m("L1-X70", "LAB_API_URL is not read", CONFIG, "return env.LAB_API_URL || null;", "return null;", [C.c06]),
  m("L1-X71", "an old per-family name is revived as a fallback", CONFIG, "return env.LAB_API_URL || null;", "return env.LAB_API_URL || env.LAB_CONTROL_URL || null;", [C.c06]),
  m("L1-X73", "an empty LAB_API_URL counts as set", CONFIG, "return env.LAB_API_URL || null;", "return env.LAB_API_URL ?? null;", [C.c06]),
  m("L1-X74", "unset reads as undefined, not null", CONFIG, "return env.LAB_API_URL || null;", "return env.LAB_API_URL as string;", [C.c06]),
  m("L1-X31", "a misconfigured Lab still sends", REQUEST, '  if (config === null) return { kind: "unavailable" };\n',
    '  if (config === null) return resolveAccess({ signedIn: true, memberships: () => readMemberships(labApi({ baseUrl: "http://x.invalid", fetch: send })), selected: undefined });\n', [C.r01]),
  m("L1-X32", "the token is read from another cookie", REQUEST, "store.get(AUTH_COOKIE)?.value || null", "store.get(WORKSPACE_COOKIE)?.value || null", [C.r02]),
  m("L1-X33", "the request's cookies ride along to the API", REQUEST, "session: () => ({ token })", 'session: () => ({ token, cookie: "infrx-lab-session=x" })', [C.r02]),
  m("L1-X34", "a request without a session cookie reads memberships", REQUEST, "signedIn: token !== null", "signedIn: true", [C.r03]),
  m("L1-X46", "the guard reads another API origin", GUARD, "accessFromRequest(process.env, await cookies())", 'accessFromRequest({ ...process.env, LAB_API_URL: "http://other.invalid" }, await cookies())', [C.g03]),
  m("L1-X51", "the credentials are not what was typed", SIGNIN, "{ body: { email, password } }", '{ body: { email, password: "" } }', [C.s01]),
  m("L1-X52", "a failed sign-in is not a fixed failure", SIGNIN, "  if (!answer.ok) return { error: signInFailure(answer.error) };\n", "", [C.s02]),
  m("L1-X53", "a sign-in without a password is sent anyway", SIGNIN, '  if (typeof email !== "string" || typeof password !== "string") return { error: "failed" };\n', "", [C.s02]),
  m("L1-X54", "a misconfigured Lab reads as a wrong password", SIGNIN, 'if (config === null) return { error: "unavailable" };', 'if (config === null) return { error: "failed" };', [C.s02]),
  m("L1-X118", "an unreadable facade answer is stored as a session", SIGNIN, '  if (!isTokens(answer.data)) return { error: "unavailable" };\n', "", [C.s02]),
  m("L1-X119", "a sign-in keeps no session", SIGNIN, "  storeSession(await cookies(), config, answer.data);\n", "", [C.s01]),
  m("L1-X55", "sign-out keeps the workspace preference", SIGNIN, "  jar.delete(WORKSPACE_COOKIE);\n", "", [C.s03]),
  m("L1-X56", "sign-out keeps the session cookies", SIGNIN, "  clearSession(jar);\n", "", [C.s03]),
  m("L1-X120", "sign-out never ends the session at the facade", SIGNIN, '    await labApi({ baseUrl: config.apiUrl, session: () => ({ token }) }).call("post", "/auth/v1/sign-out");\n', "", [C.s03]),
  m("L1-X121", "sign-out sends no bearer", SIGNIN, "session: () => ({ token })", "session: () => ({ token: null })", [C.s03]),
  m("L1-X122", "a rate limit reads as a wrong password", SESSION, " && error.status !== 429", "", [C.s02]),
  m("L1-X123", "an outage reads as a wrong password", SESSION, "error.status < 500", "error.status < 600", [C.s02]),
  m("L1-X124", "a refused sign-in reads as an outage", SESSION, '? "failed" : "unavailable"', '? "unavailable" : "unavailable"', [C.s02]),
  m("L1-X125", "an answer without an access token is a session", SESSION, 'typeof (value as Tokens | null)?.access_token === "string" && ', "", [C.s02]),
  m("L1-X126", "an answer without a refresh token is a session", SESSION, ' && typeof (value as Tokens).refresh_token === "string"', "", [C.s02]),
  m("L1-X127", "the access token cookie is not http-only", SESSION, "jar.set(AUTH_COOKIE, tokens.access_token, authCookieOptions(config));", "jar.set(AUTH_COOKIE, tokens.access_token);", [C.s01, C.s04]),
  m("L1-X128", "the refresh token is not kept", SESSION, "  jar.set(REFRESH_COOKIE, tokens.refresh_token, authCookieOptions(config));\n", "", [C.s01, C.s04]),
  m("L1-X129", "ending a session keeps its refresh token", SESSION, "  jar.delete(REFRESH_COOKIE);\n", "", [C.s03, C.s05]),
  m("L1-X130", "a token is refreshed only once expired", SESSION, "exp - nowMs / 1000 <= REFRESH_MARGIN_S", "exp - nowMs / 1000 <= 0", [C.s05]),
  m("L1-X131", "an unreadable token is never refreshed", SESSION, "  } catch {\n    return true;", "  } catch {\n    return false;", [C.s05]),
  m("L1-X132", "a token without exp is never refreshed", SESSION, 'typeof exp !== "number" || ', "", [C.s05]),
  m("L1-X61", "the callback drops the session", ROUTES, "  if (isTokens(session)) storeSession(response.cookies, config, session);\n", "", [C.s04]),
  m("L1-X62", "the callback forwards another code", ROUTES, "const query = code ? { code } :", 'const query = code ? { code: "x" } :', [C.s04]),
  m("L1-X133", "the callback follows the facade's redirect", ROUTES, "  if (isTokens(session)) storeSession(response.cookies, config, session);\n  return response;",
    "  if (isTokens(session)) storeSession(response.cookies, config, session);\n  return answer.ok ? NextResponse.redirect(answer.data.redirect) : response;", [C.s04]),
  m("L1-X63", "the proxy drops the refreshed cookie", ROUTES, "    storeSession(response.cookies, config, answer.data);\n", "", [C.s05]),
  m("L1-X64", "the proxy refreshes a fresh session", ROUTES, "!refreshDue(request.cookies.get(AUTH_COOKIE)?.value)", "false", [C.s05]),
  m("L1-X134", "the proxy refreshes without a refresh token", ROUTES, "config === null || !refresh ||", "config === null ||", [C.s05]),
  m("L1-X135", "this request's pages keep the stale token", ROUTES, "    request.cookies.set(AUTH_COOKIE, answer.data.access_token);\n", "", [C.s05]),
  m("L1-X136", "a refused refresh keeps the session", ROUTES, "    clearSession(response.cookies);\n", "", [C.s05]),
  m("L1-X137", "an unreachable facade ends the session", ROUTES, "!answer.ok && answer.error.status === 401", "!answer.ok", [C.s05]),
  m("L1-X65", "the proxy redirects", ROUTES, "\n  return NextResponse.next({ request });\n}", '\n  return NextResponse.redirect(new URL("/", request.url));\n}', [C.s05]),
  // API-BOUNDARY (tests/boundary/api.test.ts): a direct-database transport or an undocumented call comes back.
  m("L1-X140", "the membership read is an RPC again", MEMBERS, 'const answer = await api.call("get", "/lab/v1/workspaces");',
    'const answer = await (api as unknown as { rpc(n: string): ReturnType<LabApi["call"]> }).rpc("lab_provider_memberships");', [C.t01]),
  m("L1-X141", "the review reads a table", REVIEW, "const KEYS = [", 'export const table = (c: { from(t: string): unknown }) => c.from("lab_trace_reviews");\nconst KEYS = [', [C.t01]),
  m("L1-X142", "the guard loads a Supabase client", GUARD, 'import { cache } from "react";', 'import { cache } from "react";\nimport "@supabase/ssr";', [C.t01]),
  m("L1-X143", "the config names a Supabase setting", CONFIG, 'export const WORKSPACE_COOKIE = "infrx-lab-workspace";', 'export const WORKSPACE_COOKIE = "infrx-lab-workspace";\nexport const PROJECT = () => process.env.NEXT_PUBLIC_SUPABASE_URL;', [C.t01]),
  m("L1-X144", "the Lab calls an undocumented route", MEMBERS, '"/lab/v1/capabilities", { query', '"/lab/v1/capability", { query', [C.t02, C.m05]),
  m("L1-X145", "a hand-typed shell route drifts from the gateway's", PORT, '"/auth/v1/refresh": { post:', '"/auth/v1/refresh-token": { post:', [C.t03]),
  m("L1-X20", "production accepts an http origin", CONFIG, '  if (production && url.protocol !== "https:") return null;\n', "", [C.c01]),
  m("L1-X21", "an origin with a path is accepted", CONFIG, '  if (url.origin !== raw.replace(/\\/$/, "")) return null; // an origin, no path\n', "", [C.c01]),
  m("L1-X41", "an unparsable origin throws out of the guard", CONFIG, "  let url: URL;\n  try {\n    url = new URL(raw);\n  } catch {\n    return null;\n  }\n", "  const url = new URL(raw);\n", [C.c01]),
  m("L1-X23", "cookies are never secure", CONFIG, 'secure: url.protocol === "https:"', "secure: false", [C.c02]),
  m("L1-X82", "a record id may be any UUID version", SHAPES, "-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-", "-[0-9a-f]{4}-[0-9a-f]{4}-", [C.h01]),
  m("L1-X83", "a record id may carry text around it", SHAPES, "new RegExp(`^${UUID}$`)", "new RegExp(UUID)", [C.h01]),
  m("L1-X84", "a record id may be upper case", SHAPES, "new RegExp(`^${UUID}$`)", "new RegExp(`^${UUID}$`, \"i\")", [C.h01]),
  m("L1-X85", "a read-back id is case-sensitive", SHAPES, "[0-9a-f]{12}$/i;", "[0-9a-f]{12}$/;", [C.h01]),
  m("L1-X86", "a read-back id may be v4 only", SHAPES, "/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-", "/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-", [C.h01]),
  m("L1-X87", "a read-back id may lead with text", SHAPES, "UUID_ANY_RE = /^", "UUID_ANY_RE = /", [C.h01]),
  m("L1-X88", "a USD amount may have fewer than eight decimals", SHAPES, "\\.[0-9]{8}$/;", "\\.[0-9]{1,8}$/;", [C.h02]),
  m("L1-X89", "a USD amount may lead with zero", SHAPES, "(0|[1-9][0-9]{0,11})", "[0-9]{1,12}", [C.h02]),
  m("L1-X90", "a USD amount may exceed twelve integer digits", SHAPES, "[1-9][0-9]{0,11})", "[1-9][0-9]*)", [C.h02]),
  m("L1-X91", "a USD amount may trail text", SHAPES, "[0-9]{8}$/;", "[0-9]{8}/;", [C.h02]),
  m("L1-X92", "a digest may be any hex length", SHAPES, "sha256:[0-9a-f]{64}$/;", "sha256:[0-9a-f]+$/;", [C.h03]),
  m("L1-X93", "a digest may name another algorithm", SHAPES, "DIGEST_RE = /^sha256:", "DIGEST_RE = /^[a-z0-9]+:", [C.h03]),
  m("L1-X94", "the membership read imports the record-id strictness (lowercase v4)", MEMBERS, "import { UUID_ANY_RE as UUID }", "import { UUID_RE as UUID }", [C.m04]),
  m("L1-X29", "Lab responses become cacheable", NEXT, '"private, no-store"', '"public, max-age=60"', [C.c05]),
  m("L1-X30", "the framework header is advertised", NEXT, "poweredByHeader: false", "poweredByHeader: true", [C.c05]),
  m("L1-X35", "the workspace preference is ignored", REQUEST, "selected: store.get(WORKSPACE_COOKIE)?.value }", "selected: undefined }", [C.r03]),
  m("L1-X36", "the selection action skips the provider guard", ACTION, "const access = await requireProviderSession();", 'const access = { kind: "denied" } as const;', [C.b01]),
  m("L1-X37", "the picker state renders the page", LAYOUT, "        <Workspaces workspaces={access.workspaces} />\n        <SignOut />\n      </main>", "        <Workspaces workspaces={access.workspaces} />\n        <SignOut />\n        {children}\n      </main>", [C.b02]),
  m("L1-X38", "the provider layout is prerendered", LAYOUT, 'export const dynamic = "force-dynamic";', "", [C.b02]),
  m("L1-X39", "the action stores the submitted value", ACTION, ".set(WORKSPACE_COOKIE, chosen.providerId,", '.set(WORKSPACE_COOKIE, String(formData.get("providerId")),', [C.b03]),
  // Fix round (0-L1-R-2): guard.ts is run by guard.test.ts; X42 is the reviewer's type-correct H2'.
  m("L1-X42", "a page under the picker state gets the first workspace (H2')", GUARD, "const workspace = readyWorkspace(await providerAccessForRequest());",
    "const access = await providerAccessForRequest();\n  const workspace = readyWorkspace(access) ?? sessionAccess(access)?.workspaces[0] ?? null;", [C.g01]),
  m("L1-X43", "the page guard renders without a workspace", GUARD, "  if (workspace === null) notFound();\n", "", [C.g01]),
  m("L1-X44", "the action guard runs without a provider session", GUARD, "  if (access === null) notFound();\n", "", [C.g02]),
  m("L1-X45", "the action guard admits any signed-in state", GUARD, "const access = sessionAccess(await providerAccessForRequest());", "const access = (await providerAccessForRequest()) as SessionAccess;", [C.g02]),
  // Fix round (0-L1-R-1): server actions in every form Next accepts; X48 is the reviewer's H1.
  m("L1-X48", "an unguarded arrow-const server action (H1)", ACTION, '  redirect("/");\n}\n',
    '  redirect("/");\n}\n\nexport const peekWorkspaces = async (formData: FormData) => {\n  return String(formData.get("providerId"));\n};\n', [C.b01]),
  m("L1-X49", "an unguarded default-export server action", ACTION, '  redirect("/");\n}\n', '  redirect("/");\n}\n\nexport default async function peek() {\n  return 1;\n}\n', [C.b01]),
  m("L1-X50", "an unguarded inline server action in the provider layout", LAYOUT, "<form action={selectWorkspace}>", '<form action={async () => { "use server"; }}>', [C.b01]),
  // WR-L1-6 (LW2): sign-in, sign-out, the email-link callback and the proxy refresh.
  m("L1-X57", "an unguarded export beside the public sign-in actions", SIGNIN, "export async function signOut()", "export async function peek() {\n  return 1;\n}\n\nexport async function signOut()", [C.b01]),
  m("L1-X58", "the callback follows the link's next parameter", ROUTES, 'new URL("/", config?.origin ?? request.nextUrl.origin)', 'new URL(request.nextUrl.searchParams.get("next") ?? "/", config?.origin ?? request.nextUrl.origin)', [C.s04]),
  m("L1-X59", "the callback redirects to the request's Host", ROUTES, 'new URL("/", config?.origin ?? request.nextUrl.origin)', 'new URL("/", request.nextUrl.origin)', [C.s04]),
  m("L1-X60", "the callback verifies signup and recovery links", ROUTES, '(type === "magiclink" || type === "email")', "type", [C.s04]),
  m("L1-X66", "a signed-out visitor gets no sign-in form", LAYOUT, "        <SignInForm />\n", "", [C.b05]),
  m("L1-X67", "a consumer-only user cannot sign out", LAYOUT, '      {access.kind === "denied" && <SignOut />}\n', "", [C.b05]),
  m("L1-X68", "the form shows the action's raw error", FORM, "SIGN_IN_COPY[state.error]", "String(state.error)", [C.b05]),
  m("L1-X69", "the sign-in notice repeats the auth server", ACCESS, '"That email and password did not sign you in.', '"Invalid login credentials. That email and password did not sign you in.', [C.s02]),
  // LAB-07: the one role table (each family runner kills its own role mutants on it too)
  m("L1-X95", "an administrator loses manage_members", ACCESS, '"propose_publication", "manage_members"]', '"propose_publication"]', [C.a10]),
  m("L1-X96", "a role holds customer content", ACCESS, 'viewer: ["read_aggregate_health"],', 'viewer: ["read_aggregate_health", "read_customer_content"],', [C.a10]),
  m("L1-X98", "a developer holds manage_members", ACCESS, '"manage_dev_deployment", "run_evaluation"],\n  administrator', '"manage_dev_deployment", "run_evaluation", "manage_members"],\n  administrator', [C.a10]),
  ...PORTS.map((port, i) => m(`L1-X${99 + i}`, `${port} answers from a table of its own`, port,
    'export { holds, type Actor, type Capability } from "../../auth/access.ts";',
    'export { type Actor, type Capability } from "../../auth/access.ts";\nexport const holds = (role: string, capability: string): boolean => role !== "viewer" || capability === "read_aggregate_health";', [C.a11])),
  // LAB-09: the boilerplate lives once
  m("L1-X102", "a family keeps its own refusal guard", "lib/services/rollouts/view.ts", "export const refusalCopy = fixedCopy(REFUSALS, REFUSAL_COPY);",
    "export const refusalCopy = (value: unknown) => ((REFUSALS as readonly unknown[]).includes(value) ? REFUSAL_COPY[value as Refusal] : null);", [C.b06]),
  m("L1-X103", "a page inlines its own preview copy", LAYOUT, '<PreviewNote records="control" service="control" />',
    '<p role="note">Preview: control records come from an in-memory stand-in, not the control service.</p>', [C.b06]),
  // LAB-13: the page conventions
  m("L1-X104", "a page types its params by hand", "app/(provider)/datasets/[ref]/page.tsx", 'PageProps<"/datasets/[ref]">', "{ params: Promise<{ ref: string }> }", [C.b07]),
  m("L1-X105", "a page has no title", "app/(provider)/datasets/page.tsx", 'export const metadata = { title: "Datasets · infrx Lab" };\n', "", [C.b07]),
  m("L1-X106", "a route climbs to lib by a relative path", "app/(provider)/experiments/[id]/report/route.ts", 'from "@/lib/auth/guard";', 'from "../../../../../lib/auth/guard.ts";', [C.b07]),
  m("L1-X40", "the Lab imports the App's code", ACCESS, "export const ROLES", 'import type {} from "../../../app/lib/types.ts";\nexport const ROLES', [C.b04]),
];

process.exit(await runMutants({ suite: SUITE, prefix: "L1", mutants: MUTANTS }));
