"""F2C.c — the published-model projection: public capability and accounting identity.

One record answers "what may a caller send to this model, how is it priced, what does
serving keep" for every consumer of that answer: the discovery route and any provider
document (G7), the console catalog/docs (A3), the pricing seam (D10) and the dataset
client (E1C). RV-01 is the defect this closes: `/v1/models` returned a static file that
advertised 120 s videos, tool parameters, a readiness flag and zero data retention, none
of which the runtime honours. The TypeScript twin is
`apps/app/lib/contracts/v2/published-model.ts`; both halves serialize a record to the same
canonical bytes (`codec.canonical_bytes`) and read the same fixtures from `published/`
(generated by `published_fixtures.py`).

Rules this module is the single statement of (proposed ruling R109):

* **Resolution is defined once.** `split_model` is the grammar `<public id>[@<revision
  label>]` (0008 `resolve_admission_pins`'s own pattern) and `resolve` picks, among the
  published records, the one with that id and label; an unlabelled id takes the highest
  listing. Nothing resolves by a spelling it was not published under: the engine's served
  name `marlin2b`, the artifact repo `NemoStation/Marlin-2B` and a coming-soon row are
  `not_found`.
* **Pricing follows resolution, never the spelling (P-22).** `price` returns the pins an
  admission records: the caller's `requested_model` verbatim beside the canonical
  `model_revision`, deployment and serving revision, and exactly one price identity - the
  CREDIT `rate_card_version` in the credit regime, the USD `price_version` keyed by the
  canonical revision in the legacy regime. There is no conversion between the two and no
  function here produces one.
* **One public rate identity per revision.** It is `(rate_card_version, CREDIT)` of the
  card the revision's effective catalog listing names - the card 0008
  `resolve_admission_pins` pins - and `project` must be handed exactly that card. A card
  no effective listing names is not a public rate: `marlin_release()`'s locally computed
  `rc_marlin2b_<ts>_provisional_p01` (certify, endpoint_doc) was never written to the
  hosted catalog, whose listing names the seed's `rc_marlin2b_2026_09_provisional`. History
  maps through each job's own pinned `rate_card_version` (R78), never through the current
  identity: no mapping table, no rewritten row.
* **Unpriced or unpublishable fails closed.** `project` refuses a private or non-active
  deployment (`not_found`, R70) and a deployment without the active regime's price
  identity (`invalid_request`, R69). `Pricing` cannot be constructed without it either.
* **Availability is not capability.** `availability` says whether requests are being
  accepted now; `capability` says what an accepted request may contain. Neither implies
  the other, and no capacity or latency number is published (P-18: unmeasured).
* **A projection never advertises what serving refuses.** `violations` compares a
  projection with the `ServingProfile` the running deployment actually enforces: a cap may
  be advertised at or below the enforced one, a vocabulary only as a subset, the declared
  preprocessing constraints and every retention figure exactly.
* **Serving keeps content.** `ServingRetention` cannot state zero data retention or that
  turning trace capture off deletes serving content: payloads, media and results have
  their own lifecycles (RV-01, RV-03, P-25).
"""
from __future__ import annotations

import re
from datetime import datetime
from typing import Annotated, Iterable, Literal

from pydantic import (AfterValidator, BeforeValidator, Field, StrictBool, StrictInt, StrictStr,
                      model_validator)

from .. import errors
from ..limits import PilotSettings
from ..records import ExecutionMode, PriceSnapshot
from .money_units import CREDIT, USD, Credit, Usd
from .records import (AccountingRegime, CreditField, DeploymentRevision, DeploymentState,
                      DigestSource, RateCardSnapshot, RecordV2, ServingRevision, Sha256,
                      Timestamp, UsdField, UuidStr, Visibility)

# 0008 `resolve_admission_pins`: `^[^@\s]{1,200}(@[^@\s]{1,64})?$`.
MODEL_GRAMMAR = re.compile(r"^([^@\s]{1,200})(?:@([^@\s]{1,64}))?$")

# What serving stores for an accepted request whatever the trace mode (RV-01): the staged
# normalized request, the fetched/uploaded source, the prepared media cache, the result
# record and the SSE journal. Sorted: the wire order of a set is its sorted order.
STORED_CONTENT = ("prepared_media", "request_payload", "result", "source_media",
                  "stream_journal")
StoredContent = Literal["prepared_media", "request_payload", "result", "source_media",
                        "stream_journal"]

# Parameters that need a capability the serving revision must declare first.
TOOL_PARAMETERS = frozenset({"tools", "tool_choice", "functions", "function_call",
                             "parallel_tool_calls"})
STRUCTURED_PARAMETERS = frozenset({"response_format"})


def _false(value: bool) -> bool:
    if value is not False:
        raise ValueError("this statement is false for every serving deployment here")
    return value


def _canonical(unit_type):
    """On the wire an amount is its canonical eight-digit string, never a number or `"400"`
    (the console refuses both; `UsageRecordV2.charged_amount` has the same rule)."""
    def check(value: object) -> object:
        if isinstance(value, unit_type):
            return value
        if not isinstance(value, str) or str(unit_type(value)) != value:
            raise ValueError("an amount crosses JSON as its canonical eight-digit string")
        return value
    return BeforeValidator(check)


WireCredit = Annotated[CreditField, _canonical(Credit)]
WireUsd = Annotated[UsdField, _canonical(Usd)]
AlwaysFalse = Annotated[StrictBool, AfterValidator(_false)]
Count = Annotated[StrictInt, Field(ge=1)]
Name = Annotated[StrictStr, Field(min_length=1)]


def _sorted_unique(name: str, values: tuple) -> None:
    items = [str(v) for v in values]
    if items != sorted(set(items)):
        raise ValueError(f"{name} is sorted and has no duplicates, so one claim is one "
                         f"spelling on the wire")


# --- the record -------------------------------------------------------------
class VideoInput(RecordV2):
    """A finite video clip per request. `live_stream` is native live-video input."""

    max_seconds: Count
    max_bytes: Count
    max_per_request: Count
    mime_types: tuple[Name, ...] = Field(min_length=1)
    live_stream: StrictBool
    # Declared by the pinned preprocessing profile (S2M §1.5), not measured per request.
    profile_version: Name
    fps: Count
    min_frames: Count
    max_frames: Count
    max_pixels_per_frame: Count

    @model_validator(mode="after")
    def _consistent(self) -> VideoInput:
        _sorted_unique("mime_types", self.mime_types)
        if self.min_frames > self.max_frames:
            raise ValueError("min_frames exceeds max_frames")
        return self


class Capability(RecordV2):
    """What an accepted request may contain. The advertised and the enforced side are
    both this type, so `violations` compares like with like."""

    input_modalities: tuple[Literal["text", "video"], ...] = Field(min_length=1)
    output_modalities: tuple[Literal["text"], ...] = Field(min_length=1)
    # `stream` is SSE output; `async` is an explicit job (`Prefer: respond-async`, /v1/jobs).
    execution_modes: tuple[ExecutionMode, ...] = Field(min_length=1)
    parameters: tuple[Name, ...] = Field(min_length=1)        # the exact allow-list
    unsupported_parameters: tuple[Name, ...]                   # refused by name
    max_request_bytes: Count
    max_context_tokens: Count
    max_input_tokens: Count
    max_output_tokens: Count
    video: VideoInput | None = None

    @model_validator(mode="after")
    def _consistent(self) -> Capability:
        for name in ("input_modalities", "output_modalities", "execution_modes", "parameters",
                     "unsupported_parameters"):
            _sorted_unique(name, getattr(self, name))
        if set(self.parameters) & set(self.unsupported_parameters):
            raise ValueError("a parameter is either accepted or refused, not both")
        if (self.video is None) != ("video" not in self.input_modalities):
            raise ValueError("video limits are stated exactly when video input is accepted")
        if self.max_input_tokens + self.max_output_tokens > self.max_context_tokens:
            raise ValueError("max_input_tokens + max_output_tokens exceeds max_context_tokens")
        return self


class ServingRetention(RecordV2):
    """What serving keeps, apart from opt-in traces. Every TTL is a logical lifetime (after
    it the content is refused); `physical_deletion_bound_s` is the committed bound on when
    the bytes are gone, and None means no bound is committed yet (P-25)."""

    zero_data_retention: AlwaysFalse
    capture_off_deletes_serving_content: AlwaysFalse
    trace_capture_default: Literal["off"]
    content_stored: tuple[StoredContent, ...] = Field(min_length=1)
    result_ttl_s: Count
    stream_journal_ttl_s: Count
    idempotency_ttl_s: Count
    processing_cache_ttl_s: Count
    physical_deletion_bound_s: Count | None = None

    @model_validator(mode="after")
    def _consistent(self) -> ServingRetention:
        _sorted_unique("content_stored", self.content_stored)
        return self


class ServingIdentity(RecordV2):
    """The immutable serving revision, public part: artifact, processor, prompt, engine."""

    serving_version_id: UuidStr
    revision_label: Name
    model_repo: Name
    model_commit: StrictStr = Field(pattern=r"^[0-9a-f]{40}$")
    weight_shard_digests: tuple[Sha256, ...] = Field(min_length=1)
    adapter_digest: Sha256 | None = None
    tokenizer_digest: Sha256
    chat_template_digest: Sha256
    digest_source: DigestSource
    prompt_harness_ref: Name
    preprocessor_profile_version: Name
    runtime_image_ref: Name
    runtime_image_digest: Sha256 | None = None
    engine_options_digest: Sha256
    precision: Name

    @classmethod
    def of(cls, serving: ServingRevision) -> ServingIdentity:
        return cls(**{name: getattr(serving, name) for name in cls.model_fields
                      if name != "schema_version"})


class CreditRate(RecordV2):
    """The approved CREDIT card admission pins (`RateCardSnapshot`), public part."""

    rate_card_version: Name
    unit: Literal["CREDIT"]
    meter: Literal["tokens-v1"]
    input_rate_per_million: WireCredit
    output_rate_per_million: WireCredit
    effective_at: Timestamp
    provisional: StrictBool          # true until P-01 approves the launch rate

    @model_validator(mode="after")
    def _nonnegative(self) -> CreditRate:
        if self.input_rate_per_million.is_negative or self.output_rate_per_million.is_negative:
            raise ValueError("a CREDIT rate is nonnegative")
        return self


class UsdPrice(RecordV2):
    """The legacy regime's USD price identity (`infrx.price_versions`), keyed by the
    canonical revision it prices (P-22) - never derived from a CREDIT card."""

    price_version: Name
    unit: Literal["USD"]
    model_revision: Name
    input_rate_per_million: WireUsd
    output_rate_per_million: WireUsd
    token_rules_version: Name

    @model_validator(mode="after")
    def _nonnegative(self) -> UsdPrice:
        if self.input_rate_per_million.is_negative or self.output_rate_per_million.is_negative:
            raise ValueError("a USD rate is nonnegative")
        return self


class Pricing(RecordV2):
    """Which regime admission charges in, and its price identity. The other identity is
    informational: in the credit regime `legacy_usd` is what pre-cutover USD rows resolved
    through; in the legacy regime no CREDIT card is shown, because none is charged."""

    regime: AccountingRegime
    credit: CreditRate | None = None
    legacy_usd: UsdPrice | None = None

    @model_validator(mode="after")
    def _the_active_regime_is_priced(self) -> Pricing:
        if self.regime is AccountingRegime.credit and self.credit is None:
            raise ValueError("unpriced is unserveable: the credit regime needs an approved card")
        if self.regime is AccountingRegime.legacy_usd:
            if self.legacy_usd is None:
                raise ValueError("unpriced is unserveable: the legacy regime needs a USD price")
            if self.credit is not None:
                raise ValueError("the legacy regime charges USD; a CREDIT rate it does not "
                                 "charge is not published beside it")
        return self


class PublishedModel(RecordV2):
    """One entry of the public catalog, OpenAI list-shaped (`object`, `id`, `created`,
    `owned_by`) with the projection beside it."""

    object: Literal["model"]
    id: Name                                   # the canonical public model id
    created: StrictInt = Field(ge=0)           # the serving revision's creation, unix s
    owned_by: Name
    model_revision: Name                       # `<id>@<revision label>` (R62)
    aliases: tuple[Name, ...] = Field(min_length=1)
    listing_version: Count
    deployment_revision_id: UuidStr
    serving: ServingIdentity
    capability: Capability
    pricing: Pricing
    retention: ServingRetention
    availability: Literal["available", "unavailable"]
    availability_as_of: Timestamp

    @model_validator(mode="after")
    def _consistent(self) -> PublishedModel:
        if self.model_revision != f"{self.id}@{self.serving.revision_label}":
            raise ValueError("model_revision is <id>@<serving revision label>")
        _sorted_unique("aliases", self.aliases)
        if self.model_revision not in self.aliases:
            raise ValueError("the pinned revision always resolves to its own record")
        if not set(self.aliases) <= {self.id, self.model_revision}:
            raise ValueError("an alias is the id or the pinned revision; no other spelling "
                             "resolves (split_model)")
        usd = self.pricing.legacy_usd
        if usd is not None and usd.model_revision != self.model_revision:
            raise ValueError("a USD price identity is keyed by the canonical model_revision "
                             "(P-22), not by a spelling")
        return self


class ServingProfile(RecordV2):
    """What the running deployment enforces, built by G7 from the runtime (settings, the
    validator's allow-list, the media profile, the deployment revision)."""

    capability: Capability
    retention: ServingRetention


class PricedResolution(RecordV2):
    """The pins an admission records for one request (P-22)."""

    requested_model: Name                      # verbatim, as the caller sent it
    model_revision: Name                       # canonical, immutable
    deployment_revision_id: UuidStr
    serving_version_id: UuidStr
    accounting_regime: AccountingRegime
    rate_card_version: Name | None = None
    price_version: Name | None = None

    @model_validator(mode="after")
    def _one_price_identity(self) -> PricedResolution:
        credit = self.accounting_regime is AccountingRegime.credit
        if credit != (self.rate_card_version is not None) or credit == (
                self.price_version is not None):
            raise ValueError("a credit pin names a rate card and a legacy_usd pin a USD "
                             "price_version, never both and never neither")
        return self


# --- resolution and pricing, once --------------------------------------------
def split_model(requested: str) -> tuple[str, str | None]:
    """`<public id>[@<revision label>]`, or `not_found` (never a hint of what exists)."""
    match = MODEL_GRAMMAR.match(requested) if isinstance(requested, str) else None
    if match is None:
        raise errors.NotFound("model")
    return match.group(1), match.group(2)


def resolve(requested: str, published: Iterable[PublishedModel]) -> PublishedModel:
    public_id, label = split_model(requested)
    matches = [m for m in published
               if m.id == public_id and (label is None or m.serving.revision_label == label)]
    if not matches:
        raise errors.NotFound("model")
    return max(matches, key=lambda m: m.listing_version)


def price(requested: str, published: Iterable[PublishedModel]) -> PricedResolution:
    model = resolve(requested, published)
    pricing = model.pricing
    credit = pricing.regime is AccountingRegime.credit
    return PricedResolution(
        requested_model=requested, model_revision=model.model_revision,
        deployment_revision_id=model.deployment_revision_id,
        serving_version_id=model.serving.serving_version_id, accounting_regime=pricing.regime,
        rate_card_version=pricing.credit.rate_card_version if credit else None,
        price_version=None if credit else pricing.legacy_usd.price_version)


def catalog_problems(published: Iterable[PublishedModel]) -> list[str]:
    """Every advertised alias must resolve back to the record advertising it (so the
    floating id sits only on the highest listing) and revisions are unique."""
    models = list(published)
    problems = [f"{m.model_revision}: alias {a!r} resolves to "
                f"{resolve(a, models).model_revision}"
                for m in models for a in m.aliases if resolve(a, models) is not m]
    revisions = [m.model_revision for m in models]
    problems += [f"{r}: published twice" for r in sorted(set(revisions))
                 if revisions.count(r) > 1]
    return problems


# --- projection from the trusted rows ------------------------------------------
def project(*, serving: ServingRevision, deployment: DeploymentRevision, listing_version: int,
            regime: AccountingRegime | str, credit_card: RateCardSnapshot | None,
            credit_provisional: bool, usd_price: PriceSnapshot | None, capability: Capability,
            retention: ServingRetention, owned_by: str, available: bool,
            as_of: datetime) -> PublishedModel:
    """The published record, or the refusal that keeps a model out of the catalog.

    `credit_card` is the card the effective catalog listing names (the public rate
    identity), not the newest card for the deployment; `usd_price` is the effective
    `price_versions` row for the canonical revision."""
    if (deployment.visibility is not Visibility.public
            or deployment.state is not DeploymentState.active):
        raise errors.NotFound("model")                   # R70: never listed, never hinted
    if deployment.serving_version_id != serving.serving_version_id:
        raise errors.InvalidRequest("the deployment pins a different serving revision")
    regime = AccountingRegime(regime)
    credit = None
    if regime is AccountingRegime.credit:
        if credit_card is None:
            raise errors.InvalidRequest("unpriced is unserveable: no approved CREDIT card")
        if (credit_card.deployment_revision_id != deployment.deployment_revision_id
                or credit_card.serving_version_id != serving.serving_version_id):
            raise errors.InvalidRequest("the rate card prices a different revision")
        credit = CreditRate(rate_card_version=credit_card.rate_card_version, unit=CREDIT,
                            meter=credit_card.meter,
                            input_rate_per_million=credit_card.input_rate_per_million,
                            output_rate_per_million=credit_card.output_rate_per_million,
                            effective_at=credit_card.effective_at,
                            provisional=credit_provisional)
    usd = None
    if usd_price is not None:
        if usd_price.model_revision != serving.model_revision:
            raise errors.InvalidRequest("a USD price is keyed by the canonical revision (P-22)")
        usd = UsdPrice(price_version=usd_price.price_version, unit=USD,
                       model_revision=usd_price.model_revision,
                       input_rate_per_million=Usd(usd_price.input_rate_per_million),
                       output_rate_per_million=Usd(usd_price.output_rate_per_million),
                       token_rules_version=usd_price.token_rules_version)
    if regime is AccountingRegime.legacy_usd and usd is None:
        raise errors.InvalidRequest("unpriced is unserveable: no USD price for the revision")
    declared = serving.capability
    params = set(capability.parameters)
    if (not set(capability.input_modalities) <= set(declared.input_modalities)
            or not set(capability.output_modalities) <= set(declared.output_modalities)
            or (ExecutionMode.stream in capability.execution_modes and not declared.stream_output)
            or (capability.video is not None and capability.video.live_stream
                and not declared.stream_input)
            or (params & TOOL_PARAMETERS and not declared.tools)
            or (params & STRUCTURED_PARAMETERS and not declared.structured_output)):
        raise errors.InvalidRequest("the capability exceeds what the serving revision declares")
    if (capability.max_input_tokens > deployment.max_input_tokens
            or capability.max_output_tokens > deployment.max_output_tokens):
        raise errors.InvalidRequest("the capability exceeds the deployment's validated limits")
    return PublishedModel(
        object="model", id=serving.public_model_id,
        created=int(serving.created_at.timestamp()), owned_by=owned_by,
        model_revision=serving.model_revision,
        aliases=tuple(sorted({serving.public_model_id, serving.model_revision})),
        listing_version=listing_version,
        deployment_revision_id=deployment.deployment_revision_id,
        serving=ServingIdentity.of(serving), capability=capability,
        pricing=Pricing(regime=regime, credit=credit, legacy_usd=usd),
        retention=retention, availability="available" if available else "unavailable",
        availability_as_of=as_of)


# --- the profile-vs-projection check (G7 calls this in CI) ---------------------
def serving_profile(*, limits: PilotSettings, deployment: DeploymentRevision,
                    serving: ServingRevision, parameters: Iterable[str],
                    refused: Iterable[str], video_mime: Iterable[str], fps: int,
                    min_frames: int, max_frames: int, max_pixels_per_frame: int,
                    execution_modes: Iterable[ExecutionMode | str]) -> ServingProfile:
    """What a deployment enforces, from the values the runtime reads (G7 passes
    `validate.SUPPORTED`/`UNSUPPORTED`, the MIME types BOTH the validator and the media
    profile accept, and `Settings.fps/min_frames/max_frames/px_per_frame`). The token
    ceilings are `Validator.ceilings`': the deployment's, never past the pilot limits."""
    output = min(limits.max_output_tokens, deployment.max_output_tokens)
    declared = serving.capability
    video = None
    if "video" in declared.input_modalities:
        video = VideoInput(max_seconds=int(limits.max_video_seconds),
                           max_bytes=limits.max_media_bytes, max_per_request=1,
                           mime_types=tuple(sorted(set(video_mime))),
                           live_stream=declared.stream_input,
                           profile_version=serving.preprocessor_profile_version, fps=fps,
                           min_frames=min_frames, max_frames=max_frames,
                           max_pixels_per_frame=max_pixels_per_frame)
    capability = Capability(
        input_modalities=tuple(sorted(declared.input_modalities)),
        output_modalities=tuple(sorted(declared.output_modalities)),
        execution_modes=tuple(sorted(ExecutionMode(m) for m in execution_modes)),
        parameters=tuple(sorted(set(parameters))),
        unsupported_parameters=tuple(sorted(set(refused))),
        max_request_bytes=limits.max_request_bytes,
        max_context_tokens=limits.max_context_tokens,
        max_input_tokens=min(deployment.max_input_tokens, limits.max_context_tokens - output),
        max_output_tokens=output, video=video)
    retention = ServingRetention(
        zero_data_retention=False, capture_off_deletes_serving_content=False,
        trace_capture_default="off", content_stored=STORED_CONTENT,
        result_ttl_s=int(limits.result_ttl_s),
        stream_journal_ttl_s=int(limits.journal_chunk_ttl_s),
        idempotency_ttl_s=int(limits.idempotency_ttl_s),
        processing_cache_ttl_s=int(limits.processing_cache_ttl_s))
    return ServingProfile(capability=capability, retention=retention)


CAPS =("max_request_bytes", "max_context_tokens", "max_input_tokens", "max_output_tokens")
SUBSETS = ("input_modalities", "output_modalities", "execution_modes", "parameters")
VIDEO_CAPS = ("max_seconds", "max_bytes", "max_per_request")
VIDEO_EXACT = ("profile_version", "fps", "min_frames", "max_frames", "max_pixels_per_frame")


def violations(published: PublishedModel, profile: ServingProfile) -> list[str]:
    """Each way `published` advertises what `profile` refuses, as `path: detail`, sorted.

    Empty means honest. A cap may be advertised at or below the enforced one; a vocabulary
    only as a subset; a refused parameter only if it is really refused; live video only if
    served; the preprocessing constraints and every retention figure only exactly.
    """
    out: list[str] = []
    ad, real = published.capability, profile.capability

    def more(path, a, b):
        out.append(f"{path}: advertised {a!r}, enforced {b!r}")

    for name in CAPS:
        if getattr(ad, name) > getattr(real, name):
            more(f"capability.{name}", getattr(ad, name), getattr(real, name))
    for name in SUBSETS:
        extra = sorted(str(v) for v in set(getattr(ad, name)) - set(getattr(real, name)))
        if extra:
            more(f"capability.{name}", extra, sorted(str(v) for v in getattr(real, name)))
    accepted = sorted(set(ad.unsupported_parameters) & set(real.parameters))
    if accepted:
        more("capability.unsupported_parameters", accepted, "accepted")
    if ad.video is not None:
        if real.video is None:
            more("capability.video", "video", None)
        else:
            for name in VIDEO_CAPS:
                if getattr(ad.video, name) > getattr(real.video, name):
                    more(f"capability.video.{name}", getattr(ad.video, name),
                         getattr(real.video, name))
            for name in VIDEO_EXACT:
                if getattr(ad.video, name) != getattr(real.video, name):
                    more(f"capability.video.{name}", getattr(ad.video, name),
                         getattr(real.video, name))
            extra = sorted(set(ad.video.mime_types) - set(real.video.mime_types))
            if extra:
                more("capability.video.mime_types", extra, list(real.video.mime_types))
            if ad.video.live_stream and not real.video.live_stream:
                more("capability.video.live_stream", True, False)
    for name in ServingRetention.model_fields:
        if getattr(published.retention, name) != getattr(profile.retention, name):
            more(f"retention.{name}", getattr(published.retention, name),
                 getattr(profile.retention, name))
    return sorted(out)


__all__ = ["Capability", "CreditRate", "PricedResolution", "Pricing", "PublishedModel",
           "ServingIdentity", "ServingProfile", "ServingRetention", "UsdPrice", "VideoInput",
           "catalog_problems", "price", "project", "resolve", "serving_profile", "split_model",
           "violations"]
