#!/usr/bin/env node
// B4's mutant runner (R32; LANE-RULES addendum) over tests/b, on the shared Lab harness.
// Usage: node tests/b/run-mutants.mjs [--only ID,ID]
import { m, runMutants } from "../l/shell/harness.mjs";

const SUITE = ["view", "real", "journey", "actions", "pages", "http", "wiring"].map((f) => `tests/b/${f}.test.ts`);
const COMMON = "lib/services/common.ts"; // LAB-09: land, form readers, refusal copy, preview switch
const NOTE = "components/preview-note.tsx"; // LAB-09: the one preview note
const PORT = "lib/services/evaluation/port.ts";
const ACCESS = "lib/auth/access.ts"; // LAB-07: the one role table
const FAKE = "lib/services/evaluation/fake.ts";
const VIEW = "lib/services/evaluation/view.ts";
const ACTIONS = "lib/services/evaluation/actions.ts";
const ROUTE = "app/(provider)/experiments/[id]/report/route.ts";
const EVALS = "app/(provider)/evaluations/page.tsx";
const CHECKPOINTS = "app/(provider)/evaluations/checkpoints/page.tsx";
const EXPERIMENT = "app/(provider)/experiments/[id]/page.tsx";
const RUNS = "app/(provider)/evaluations/runs.tsx";
const HTTP = "lib/services/evaluation/http.ts";
const TRANSPORT = "lib/services/http.ts"; // LAB-04: the one transport every family adapter calls
const SERVER = "lib/services/evaluation/server.ts";
const SESSION = "lib/auth/session.ts"; // LAB-05: the one read-only session client
const SHAPES = "lib/services/shapes.ts"; // LAB-10: the shared input shapes

const C = {
  v01: "B4-V01 everyone in the workspace reads evaluations; only developer and administrator run or cancel them",
  v02: "B4-V02 progress is counted against every case of the run, failures and unfinished cases included",
  v03: "B4-V03 cancel is offered only on a queued or running run, and only to a role that runs evaluations",
  v04: "B4-V04 a run's state is its record's: queued waits for a worker and an ended run is never called a success",
  v05: "B4-V05 CREDIT and PROVIDER_USD are listed per unit, as exact strings, never summed or converted",
  v06: "B4-V06 an estimate with too few cases or clusters shows no difference, no interval and no improvement; no latency is not a number",
  v07: "B4-V07 a subscription shows its pinned suite, CREDIT limits and one decision per checkpoint as recorded",
  v08: "B4-V08 a refusal is fixed copy for a known reason and nothing for anything else in the URL",
  v09: "B4-V09 the evaluation port fails closed: unavailable until the real adapter is wired, the preview never in production",
  r01: "B4-R01 real D7 run records: a cancelled run's in-flight case stays unfinished, a queued one waits",
  c01: "B4-C01 a required slice that is inferior rejects the candidate even when the overall estimate improved",
  c02: "B4-C02 missing, errored and unscored cases stay in view and a coverage gap is inconclusive, never accepted",
  c03: "B4-C03 costs stay per unit: PROVIDER_USD beside CREDIT, and a delta only where both runs carry the unit",
  c04: "B4-C04 the comparison names both runs, the case universe and the protocol by digest so it can be reproduced",
  j01: "B4-J01 launch → queued baseline and candidate runs → progress → cancel → the report, each read back from the records",
  j02: "B4-J02 foreign, viewer and malformed variants: nothing leaks, nothing is queued",
  j03: "B4-J03 a checkpoint subscription pins its suite and CREDIT limits once; decisions arrive from B3 and stay the provider's",
  a01: "B4-A01 a launch runs as the session's provider and role and sends the parsed, predeclared protocol",
  a02: "B4-A02 a viewer is refused before the evaluation service is asked",
  a03: "B4-A03 malformed launch, cancel and subscription input is refused as invalid and never reaches the service",
  a04: "B4-A04 the service's refusal is carried as its reason; a cancel lands back on the run records",
  a05: "B4-A05 a consumer-only user gets a 404 from every action and the export, and the service is never asked",
  a06: "B4-A06 the export is the stored B2 report verbatim for the provider's own experiment, and nothing before it exists",
  p01: "B4-P01 each page reads the evaluation records as the session's workspace and shows ?refused= only as fixed copy",
  p02: "B4-P02 launch and subscribe forms are shown only to a role that runs evaluations and carry a fresh record id",
  p03: "B4-P03 an experiment is found only among the workspace's own, compared only through B2's report, exported only once it exists",
  p04: "B4-P04 the preview stand-in is labelled on every page only when it is on",
  h01: "B4-H01 every call is the session's token and the actor's provider on its route, reads unwrapped from {data}",
  h02: "B4-H02 the route's refusals are the port's reasons; anything else, or no answer, is unavailable",
  h03: "B4-H03 the backends' records pass verbatim; one unreadable row fails the whole answer closed",
  h04: "B4-H04 without a session token nothing is sent and every call is unavailable",
  h05: "B4-H05 a session-token getter that rejects is no session: nothing is sent and every call is unavailable",
  w01: "B4-W01 LAB_API_URL set: the port reads the route as the session's own access token",
  w02: "B4-W02 a missing LAB_API_URL or Lab config fails closed: every call unavailable, nothing sent",
};

const MUTANTS = [
  // view: progress, units, the comparison, subscriptions, refusals
  m("B4-X01", "costs are summed into one total", VIEW, "const lines = Object.keys(amounts).sort().map((unit) => `${amounts[unit]} ${unit}`);",
    "const lines = Object.keys(amounts).length > 0 ? [`${Object.values(amounts).reduce((a, b) => a + Number(b), 0)} total`] : [];", [C.v05, C.c03]),
  m("B4-X02", "no cost reads as nothing at all", VIEW, 'return lines.length > 0 ? lines : ["none"];', "return lines;", [C.v05, C.r01]),
  m("B4-X03", "units are listed in arrival order", VIEW, "Object.keys(amounts).sort()", "Object.keys(amounts)", [C.v05]),
  m("B4-X04", "a queued run reads as running", VIEW, 'queued: "queued · waiting for a worker",', 'queued: "running",', [C.v04, C.r01]),
  m("B4-X05", "an ended run is called a success", VIEW, 'succeeded: "finished",', 'succeeded: "succeeded",', [C.v04]),
  m("B4-X06", "the denominator leaves out failed and in-flight cases", VIEW, "const total = Object.values(run.cases).reduce((a, b) => a + b, 0);",
    "const total = (run.cases.done ?? 0) + (run.cases.pending ?? 0);", [C.v02, C.r01]),
  m("B4-X07", "a leased case is not counted as unfinished", VIEW, 'n("pending") + n("leased")', 'n("pending")', [C.v02, C.r01]),
  m("B4-X08", "cancel is offered on an ended run", VIEW, '(run.state === "queued" || run.state === "running") && ', "", [C.v03, C.r01]),
  m("B4-X09", "cancel is offered to a viewer", VIEW, ' && holds(role, "run_evaluation"),', ",", [C.v03]),
  m("B4-X10", "a queued run cannot be cancelled", VIEW, 'run.state === "queued" || ', "", [C.v03, C.r01]),
  m("B4-X11", "no attempts reads as an empty string", VIEW, 'attempts.length > 0 ? attempts.join(" · ") : "none yet"', 'attempts.join(" · ")', [C.v02, C.r01]),
  m("B4-X12", "an undecidable difference reads as zero", VIEW, 'diff: e.diff === null ? "—" : String(e.diff),', "diff: String(e.diff ?? 0),", [C.v06]),
  m("B4-X13", "an absent interval is printed", VIEW, 'interval: e.low === null ? "—" : `[${e.low}, ${e.high}]`,', "interval: `[${e.low}, ${e.high}]`,", [C.v06]),
  m("B4-X14", "the interval loses its lower bound", VIEW, ": `[${e.low}, ${e.high}]`,", ": `≤ ${e.high}`,", [C.c01]),
  m("B4-X15", "improvement is claimed from non-inferiority", VIEW, 'improved: e.improved ? "improved" : ""', 'improved: e.verdict === "non_inferior" ? "improved" : ""', [C.c02]),
  m("B4-X16", "a slice is judged by the overall thresholds", VIEW, "r.estimates.slices[s], p.required_slices[s])", "r.estimates.slices[s], p)", [C.c01, C.v06]),
  m("B4-X17", "required slices are dropped from the comparison", VIEW, "...Object.keys(r.estimates.slices).sort()", "...Object.keys({}).sort()", [C.c01, C.c02, C.v06]),
  m("B4-X18", "too few cases reads as merely uncertain", VIEW, 'insufficient: "too few cases to decide",', 'insufficient: "uncertain",', [C.v06]),
  m("B4-X19", "an inconclusive comparison reads as accepted", VIEW, 'inconclusive: "Inconclusive: the evidence does not decide this comparison",', 'inconclusive: "Accept: every predeclared criterion is met",', [C.c02]),
  m("B4-X20", "a rejection reads as accepted", VIEW, 'reject: "Reject: a predeclared criterion failed",', 'reject: "Accept: every predeclared criterion is met",', [C.c01]),
  m("B4-X21", "the decision's reasons are hidden", VIEW, "reasons: r.decision.reasons,", "reasons: [],", [C.c01, C.c02, C.j01]),
  m("B4-X22", "paired cases lose their universe", VIEW, "paired: `${r.observed.paired} / ${r.observed.universe} cases paired`,", "paired: `${r.observed.paired} cases paired`,", [C.c02]),
  m("B4-X23", "missing cases lose their universe", VIEW, "missing: `${o.missing} / ${r.observed.universe} missing`", "missing: `${o.missing} missing`", [C.c02]),
  m("B4-X24", "unscored cases are hidden", VIEW, "notComparable: `${o.not_comparable} not comparable`", 'notComparable: "0 not comparable"', [C.c02]),
  m("B4-X25", "errored cases are hidden", VIEW, "errors: `${o.errors} errored`", 'errors: "0 errored"', [C.c02]),
  m("B4-X26", "both runs show the baseline's costs", VIEW, "costs: units(o.costs)", "costs: units(r.observed.baseline.costs)", [C.c03]),
  m("B4-X27", "the cost delta is the candidate's total", VIEW, "costDelta: units(r.observed.cost_delta),", "costDelta: units(r.observed.candidate.costs),", [C.c03]),
  m("B4-X28", "the protocol digest is left out of the identity", VIEW, '["Case universe", r.universe_digest], ["Protocol", r.protocol_digest],', '["Case universe", r.universe_digest],', [C.c04]),
  m("B4-X29", "the confidence is shown as a raw fraction", VIEW, "${Math.round(p.confidence * 1000) / 10}% intervals", "${p.confidence}% intervals", [C.c01]),
  m("B4-X30", "the metric basis is not shown", VIEW, 'basis: r.estimates.basis.replace("_", " "),', 'basis: "",', [C.c01]),
  m("B4-X31", "the pairing kind is shown raw", VIEW, 'r.pairing.kind.replace("_", " ")', "r.pairing.kind", [C.c01]),
  m("B4-X32", "latency loses its sample size", VIEW, "ms over ${l.n}`", "ms`", [C.c02]),
  m("B4-X33", "no latency prints undefined percentiles", VIEW, 'l.n === 0 ? "no latencies" : ', "", [C.v06]),
  m("B4-X34", "a queued checkpoint run is not named", VIEW, "`evaluation queued · run ${d.run_id}`", "`evaluation queued`", [C.v07, C.j03]),
  m("B4-X35", "a skip hides its reason", VIEW, "`skipped · ${d.reason}`", '"skipped"', [C.v07]),
  m("B4-X36", "a rejected checkpoint reads as undecided", VIEW, 'return d.receipt === "rejected" ? "not evaluated: the checkpoint was rejected" : "not decided yet";', 'return "not decided yet";', [C.v07]),
  m("B4-X37", "the policies are swapped", VIEW, 's.policy === "latest_only" ?', 's.policy === "every" ?', [C.v07]),
  m("B4-X38", "subscription limits lose their unit", VIEW, "`${s.run_limit.value} ${s.run_limit.unit} per run", "`${s.run_limit.value} per run", [C.v07]),
  m("B4-X39", "any ?refused= string is looked up", COMMON, "(refusals as readonly unknown[]).includes(value) ?", 'typeof value === "string" ?', [C.v08]),
  // port: roles and the fail-closed seam
  m("B4-X40", "a viewer may run evaluations", ACCESS, 'viewer: ["read_aggregate_health"],', 'viewer: ["read_aggregate_health", "run_evaluation"],', [C.v01, C.a02, C.j02]),
  m("B4-X41", "a developer may not run evaluations", ACCESS, 'developer: ["read_aggregate_health", "manage_dev_deployment", "run_evaluation"],', 'developer: ["read_aggregate_health", "manage_dev_deployment"],', [C.v01, C.a01, C.j01]),
  m("B4-X42", "a viewer may not read", ACCESS, 'viewer: ["read_aggregate_health"],', 'viewer: [],', [C.v01]),
  m("B4-X43", "the preview stand-in runs in production", COMMON, ' && env.NODE_ENV !== "production"', "", [C.v09]),
  m("B4-X44", "the default port is the stand-in, not unavailable", COMMON, "real(env) ?? unavailable", "(preview ??= fake())", [C.v09, C.w02]),
  m("B4-X45", "any preview flag value turns the stand-in on", COMMON, 'env[flag] === "1"', "env[flag] !== undefined", [C.v09]),
  // fake: what the backends must enforce
  m("B4-X46", "reads are not scoped to the provider", FAKE, "rows.filter((r) => r.providerId === actor.providerId).map(", "rows.map(", [C.j02, C.j03]),
  m("B4-X47", "the catalog is not scoped to the provider", FAKE, "ok(copy(this.offered.get(actor.providerId) ?? EMPTY))", "ok(copy([...this.offered.values()][0] ?? EMPTY))", [C.j02]),
  m("B4-X48", "another provider's run can be cancelled", FAKE, "x.row.run_id === runId && x.providerId === actor.providerId", "x.row.run_id === runId", [C.j02]),
  m("B4-X49", "a foreign run id is judged by role first (confirms it exists)", FAKE,
    '    if (r === undefined) return no("not_found");\n    if (!holds(actor.role, "run_evaluation")) return no("denied");',
    '    if (!holds(actor.role, "run_evaluation")) return no("denied");\n    if (r === undefined) return no("not_found");', [C.j02]),
  m("B4-X50", "cancel without the capability", FAKE, '    if (!holds(actor.role, "run_evaluation")) return no("denied");\n    if (r.row.state', "    if (r.row.state", [C.j02]),
  m("B4-X51", "an ended run is cancelled again", FAKE, '    if (r.row.state !== "queued" && r.row.state !== "running") return no("conflict");\n', "", [C.j01, C.a04]),
  m("B4-X114", "a finished run can be cancelled (H5: only cancelled is refused)", FAKE, 'if (r.row.state !== "queued" && r.row.state !== "running") return no("conflict");', 'if (r.row.state === "cancelled") return no("conflict");', [C.j01, C.j02]),
  m("B4-X52", "launch without the capability", FAKE, '    this.calls.push(["launch", actor, launch]);\n    if (!holds(actor.role, "run_evaluation")) return no("denied");\n', '    this.calls.push(["launch", actor, launch]);\n', [C.j02]),
  m("B4-X53", "a resubmitted launch queues new runs", FAKE, "    if (seen !== null) return seen;\n    const c = ", "    const c = ", [C.j01, C.j02]),
  m("B4-X54", "one id with another body is accepted", FAKE, 'return seen.body === body ? ok(copy(seen.row)) : no("conflict");', "return ok(copy(seen.row));", [C.j02, C.j03]),
  m("B4-X55", "a form id finds another provider's record", FAKE, "rows.find((r) => r.providerId === actor.providerId && id(r.row) === key)", "rows.find((r) => id(r.row) === key)", [C.j02]),
  m("B4-X56", "a dataset the provider was not offered is queued", FAKE, "if (!has(c.datasets, launch.dataset_ref) || ", "if (", [C.j02]),
  m("B4-X57", "a harness revision not offered is queued", FAKE, "!has(c.harnesses, launch.harness_ref) || ", "", [C.j02]),
  m("B4-X58", "an evaluator not offered is queued", FAKE, " || !has(c.evaluators, launch.evaluator_ref)", "", [C.j02]),
  m("B4-X59", "a baseline serving not offered is queued", FAKE, "|| !has(c.servings, launch.baseline_serving_ref) ", "", [C.j02]),
  m("B4-X60", "a candidate serving not offered is queued", FAKE, " || !has(c.servings, launch.candidate_serving_ref)", "", [C.j02]),
  m("B4-X61", "a launched run starts as running", FAKE, 'state: "queued", cases: { pending: launch.max_cases }', 'state: "running", cases: { pending: launch.max_cases }', [C.j01]),
  m("B4-X62", "a launched run has no cases", FAKE, "cases: { pending: launch.max_cases }", "cases: {}", [C.j01]),
  m("B4-X63", "a launch carries a report before any run ended", FAKE, "candidate: queued(), report: null };", "candidate: queued(), report: {} };", [C.j01, C.a06]),
  m("B4-X64", "subscribe without the capability", FAKE, '    this.calls.push(["subscribe", actor, request]);\n    if (!holds(actor.role, "run_evaluation")) return no("denied");\n', '    this.calls.push(["subscribe", actor, request]);\n', [C.j03]),
  m("B4-X65", "a subscription to another provider's run is accepted", FAKE, '.every((ref) => ref.split(":")[2] === actor.providerId)', ".every(() => true)", [C.j03]),
  m("B4-X66", "a subscription spends PROVIDER_USD", FAKE, 'request.run_limit.unit === "CREDIT" && request.limit.unit === "CREDIT" && ', "", [C.j03]),
  m("B4-X67", "a run's limit may exceed the total", FAKE, "exact(request.run_limit.value) <= exact(request.limit.value)", "true", [C.j03]),
  // actions: the session's actor, the capability, the shapes, the landing
  m("B4-X68", "a launch acts as the form's provider", ACTIONS, "evaluationPort().launch(w, launch!)", 'evaluationPort().launch({ ...w, providerId: text(data, "providerId") }, launch!)', [C.a01]),
  m("B4-X69", "the actor's role is not the session's", ACTIONS, "evaluationPort().launch(w, launch!)", 'evaluationPort().launch({ ...w, role: "administrator" as const }, launch!)', [C.a01]),
  m("B4-X70", "the capability check is skipped", COMMON, '!holds(w, capability) ? "denied" : ', "", [C.a02]),
  m("B4-X71", "malformed input reaches the service", COMMON, ' : !valid ? "invalid"', "", [C.a03]),
  m("B4-X72", "a ref of any kind passes", ACTIONS, "new RegExp(`^lab:${kind}:", "new RegExp(`^lab:[a-z_]+:", [C.a03]),
  m("B4-X73", "a ref with trailing text passes", ACTIONS, "@sha256:[0-9a-f]{64}$`);", "@sha256:[0-9a-f]{64}`);", [C.a03]),
  m("B4-X74", "any record id passes", SHAPES, "UUID_RE = new RegExp(`^${UUID}$`);", "UUID_RE = /./;", [C.a03]),
  m("B4-X75", "any CREDIT string passes", ACTIONS, "const CREDIT = /^(0|[1-9][0-9]{0,11})(\\.[0-9]{1,8})?$/;", "const CREDIT = /^-?[0-9.e]+$/;", [C.a03]),
  m("B4-X76", "an amount is not written with 8 decimals", ACTIONS, 'frac.padEnd(8, "0")', "frac", [C.a01]),
  m("B4-X77", "zero cases may be launched", ACTIONS, 'max_cases: int(data, "max_cases", 1), run_limit: credit(data, "run_limit"), protocol', 'max_cases: int(data, "max_cases", 0), run_limit: credit(data, "run_limit"), protocol', [C.a03]),
  m("B4-X78", "a fractional count passes", ACTIONS, "/^[0-9]{1,9}$/.test(v) && Number(v) >= min", "Number(v) >= min", [C.a03]),
  m("B4-X79", "the confidence bounds are loosened", ACTIONS, "!(confidence > 0.5 && confidence < 1)", "!(confidence > 0 && confidence <= 1)", [C.a03]),
  m("B4-X80", "a negative or infinite number passes", ACTIONS, '/^[0-9]+(\\.[0-9]+)?$/.test(v) ? Number(v) : null', "Number.isNaN(Number(v)) ? null : Number(v)", [C.a03]),
  m("B4-X81", "one paired case may decide", ACTIONS, 'const min_cases = int(data, "min_cases", 2);', 'const min_cases = int(data, "min_cases", 1);', [C.a03]),
  m("B4-X82", "any metric basis passes", ACTIONS, '  if (metric_source !== "deterministic_metric" && metric_source !== "teacher_judgment") return null;\n', "", [C.a03]),
  m("B4-X83", "a slice line with extra fields passes", ACTIONS, "rest.length > 0 || ", "", [C.a03]),
  m("B4-X84", "a slice declared twice passes", ACTIONS, " || name in required_slices", "", [C.a03]),
  m("B4-X85", "a slice may decide on one case", ACTIONS, " || rule.min_cases < 2", "", [C.a03]),
  m("B4-X86", "a slice without a valid margin passes", ACTIONS, " || rule.margin === null", "", [C.a03]),
  m("B4-X87", "required slices are dropped", ACTIONS, "    required_slices[name] = { margin: rule.margin, min_cases: rule.min_cases };\n", "", [C.a01]),
  m("B4-X88", "any policy passes", ACTIONS, 'policy === "latest_only" || policy === "every" ? policy : null', "policy", [C.a03]),
  m("B4-X89", "zero concurrent runs pass", ACTIONS, 'max_active: int(data, "max_active", 1)', 'max_active: int(data, "max_active", 0)', [C.a03]),
  m("B4-X90", "the total limit is the per-run one", ACTIONS, 'limit: credit(data, "limit")', 'limit: credit(data, "run_limit")', [C.a01]),
  m("B4-X91", "a refusal is dropped on the way back", COMMON, 'return result.ok ? to(result.value) : `${page}${page.includes("?") ? "&" : "?"}refused=${result.reason}`;', "return result.ok ? to(result.value) : page;", [C.a02, C.a04]),
  m("B4-X92", "a launch lands on the list, not its records", ACTIONS, ", (e) => `/experiments/${e.experiment_id}`))", "))", [C.a01]),
  m("B4-X93", "a success is flagged by the action, not the records", COMMON, "return result.ok ? to(result.value) :", "return result.ok ? `${to(result.value)}?done=1` :", [C.a01, C.a04]),
  m("B4-X94", "an action runs without a provider workspace", ACTIONS, "export async function cancelRun(data: FormData): Promise<void> {\n  const w = await requireProviderWorkspace();",
    'export async function cancelRun(data: FormData): Promise<void> {\n  const w = { providerId: "x", providerName: "x", role: "administrator" } as const;', [C.a05]),
  m("B4-X95", "a subscription lands on the evaluations list", ACTIONS, 'await land("/evaluations/checkpoints", w,', 'await land("/evaluations", w,', [C.a01, C.a02]),
  // the export route
  m("B4-X96", "the export runs without a provider workspace", ROUTE, "const workspace = await requireProviderWorkspace();", 'const workspace = { providerId: "x", role: "viewer" as const };', [C.a05]),
  m("B4-X97", "the export answers before the report exists", ROUTE, '  if (experiment.report === null) return Response.json({ refusal: "conflict" }, { status: 409, headers: HEADERS });\n', "", [C.a06]),
  m("B4-X98", "the export reads as a fixed provider", ROUTE, "evaluationPort().experiments(workspace)", 'evaluationPort().experiments({ ...workspace, providerId: "11111111-1111-4111-8111-111111111111" })', [C.a06]),
  m("B4-X99", "the export may be cached", ROUTE, 'const HEADERS = { "cache-control": "private, no-store" };', "const HEADERS = {};", [C.a06]),
  m("B4-X100", "the export is shown inline", ROUTE, '"content-disposition": `attachment; filename=', '"content-disposition": `inline; filename=', [C.a06]),
  m("B4-X101", "the export drops the report's digest", ROUTE, "return Response.json(experiment.report, {", "return Response.json({ ...experiment.report, report_digest: undefined }, {", [C.a06]),
  // pages
  m("B4-X102", "a page reads records as a fixed provider", EVALS, "port.runs(workspace)", 'port.runs({ ...workspace, providerId: "11111111-1111-4111-8111-111111111111" })', [C.p01]),
  m("B4-X103", "a page shows ?refused= raw", CHECKPOINTS, "const refused = refusalCopy((await searchParams).refused);", 'const refused = String((await searchParams).refused ?? "") || null;', [C.p01]),
  m("B4-X104", "a page claims success on its own", EVALS, "<h1>Evaluations</h1>", "<h1>Evaluations</h1>\n      <p>Launched successfully.</p>", [C.p01]),
  m("B4-X105", "the launch form is shown to a viewer", EVALS, '{holds(workspace.role, "run_evaluation") && (\n        launch.kind', "{(\n        launch.kind", [C.p02]),
  m("B4-X106", "the launch form carries a fixed id", EVALS, 'name="experiment_id" value={crypto.randomUUID()}', 'name="experiment_id" value="00000000-0000-4000-8000-000000000000"', [C.p02]),
  m("B4-X107", "the subscribe form is shown to a viewer", CHECKPOINTS, '{holds(workspace.role, "run_evaluation") && (\n        offered.kind', "{(\n        offered.kind", [C.p02]),
  m("B4-X108", "cancel is rendered on every row", RUNS, "{r.cancel && (", "{(", [C.p02]),
  m("B4-X109", "the harness is typed, not picked", EVALS, '<select name="harness_ref" required>', '<input name="harness_ref" required /><select name="unused">', [C.p02]),
  m("B4-X110", "a deep link shows the first experiment", EXPERIMENT, "list.value.find((x) => x.experiment_id === id)", "list.value[0]", [C.p03]),
  m("B4-X111", "a comparison is drawn without B2's report", EXPERIMENT, "const c = e.report === null ? null : comparison(e.report);", "const c = comparison(e.report!);", [C.p03]),
  m("B4-X112", "the export is offered before the report exists", EXPERIMENT, "      <h2>Runs</h2>", "      <a href={`/experiments/${e.experiment_id}/report`}>Export</a>\n      <h2>Runs</h2>", [C.p03]),
  m("B4-X113", "the preview label shows when the stand-in is off", EVALS, "{isPreview() && <PreviewNote", "{<PreviewNote", [C.p04]),
  // the HTTP adapter (WR-B4-1, lane lab-api-2)
  m("B4-X115", "the session token is not sent", TRANSPORT, "authorization: `Bearer ${bearer}`", "authorization: \"Bearer\"", [C.h01]),
  m("B4-X116", "the provider is not the actor's", TRANSPORT, "encodeURIComponent(actor.providerId)", "\"\"", [C.h01]),
  m("B4-X117", "a read is not unwrapped from {data}", TRANSPORT, "read: Answer = (p) => keys(p.data)", "read: Answer = (p) => keys(p)", [C.h01]),
  m("B4-X118", "a cancel is a read", HTTP, "post(actor, `runs/", "get(actor, `runs/", [C.h01]),
  m("B4-X119", "the body is dropped", TRANSPORT, "body: body === undefined ? undefined : JSON.stringify(body)", "body: undefined", [C.h01]),
  m("B4-X120", "the body is not declared JSON", TRANSPORT, "if (body !== undefined) headers[\"content-type\"] = \"application/json\";", "", [C.h01]),
  m("B4-X121", "no session reads as unavailable", TRANSPORT, "401: \"denied\", ", "", [C.h02]),
  m("B4-X122", "a missing capability reads as not found", TRANSPORT, "403: \"denied\"", "403: \"not_found\"", [C.h02]),
  m("B4-X123", "an unmapped status is invalid", TRANSPORT, "?? \"unavailable\"", "?? \"invalid\"", [C.h02]),
  m("B4-X124", "no answer is invalid", TRANSPORT, "return { ok: false, reason: \"unavailable\" }; // transport", "return { ok: false, reason: \"invalid\" }; // transport", [C.h02]),
  // the swap (WR-B4-1): the configured adapter, the session's token, the row check
  m("B4-X125", "the configured adapter is ignored", PORT, "labEvaluation, UNAVAILABLE)", "() => null, UNAVAILABLE)", [C.w01]),
  m("B4-X127", "a missing session cookie sends a fixed credential", SESSION, "get(AUTH_COOKIE)?.value || null", "get(AUTH_COOKIE)?.value || \"anon\"", [C.w01]),
  m("B4-X128", "the session is read from another cookie", SESSION, "get(AUTH_COOKIE)?.value || null", "get(REFRESH_COOKIE)?.value || null", [C.w01]),
  m("B4-X155", "the evaluation adapter carries the publishable key, not the session's token", SERVER, "token: sessionToken", "token: async () => \"anon\"", [C.w01]),
  m("B4-X130", "a call is sent without a session token", TRANSPORT, "    if (!bearer) return { ok: false, reason: \"unavailable\" }; // no session: nothing is sent\n", "", [C.h04, C.w01]),
  m("B4-X131", "an answer is not checked", TRANSPORT, "return readable(value) ? { ok: true, value: value as T } : { ok: false, reason: \"unavailable\" };", "return { ok: true, value: value as T };", [C.h03]),
  m("B4-X132", "a run in an unknown state is read", HTTP, 'state: oneOf("queued", "running", "succeeded", "failed", "cancelled"),', "state: str,", [C.h03]),
  m("B4-X133", "a run without case counts is read", HTTP, "  cases: map(num), attempts", "  cases: opt(map(num)), attempts", [C.h03]),
  m("B4-X134", "a run cost that is not an exact string is read", HTTP, "attempts: map(num), costs: map(str),", "attempts: map(num), costs: map(() => true),", [C.h03]),
  m("B4-X135", "a list answer that is one record is read", HTTP, "get(actor, \"runs\", list(RUN))", "get(actor, \"runs\", (v) => list(RUN)(v) || RUN(v))", [C.h03]),
  m("B4-X136", "a report without its decision is read", HTTP, '  decision: obj({ outcome: oneOf("accept", "reject", "inconclusive"), reasons: list(str) }),', '  decision: opt(obj({ outcome: oneOf("accept", "reject", "inconclusive"), reasons: list(str) })),', [C.h03]),
  m("B4-X137", "an unknown outcome is read", HTTP, 'outcome: oneOf("accept", "reject", "inconclusive")', "outcome: str", [C.h03]),
  m("B4-X138", "an experiment without its candidate run is read", HTTP, "baseline: RUN, candidate: RUN, report", "baseline: RUN, candidate: nul(RUN), report", [C.h03]),
  m("B4-X139", "an experiment without its protocol is read", HTTP, "created_at: str, protocol: PROTOCOL,", "created_at: str, protocol: opt(PROTOCOL),", [C.h03]),
  m("B4-X140", "an unnamed harness revision is offered", HTTP, 'ref: str, harness_id: str, version: num, adapter: oneOf("text", "finite_video", "structured")', "ref: str", [C.h03]),
  m("B4-X141", "a catalog without servings is read", HTTP, "datasets: list(OPTION), servings: list(OPTION),", "datasets: list(OPTION), servings: opt(list(OPTION)),", [C.h03]),
  m("B4-X142", "subscription decisions are not checked", HTTP, "  decisions: list(obj({", "  decisions: list((v) => true || obj({", [C.h03]),
  m("B4-X143", "an amount without its unit is read", HTTP, 'const AMOUNT = obj({ unit: oneOf("CREDIT", "PROVIDER_USD"), value: str });', "const AMOUNT = obj({ value: str });", [C.h03]),
  m("B4-X144", "a cancel's answer is not checked", HTTP, "/cancel`, RUN)", "/cancel`, () => true)", [C.h03]),
  m("B4-X145", "a launch's answer is not checked", HTTP, '"experiments", EXPERIMENT, launch)', '"experiments", () => true, launch)', [C.h03]),
  m("B4-X146", "a subscription's answer is not checked", HTTP, '"subscriptions", SUBSCRIPTION, request)', '"subscriptions", () => true, request)', [C.h03]),
  m("B4-X147", "a record's missing field is not checked", TRANSPORT, "Object.entries(spec).every(([k, check]) => check(v[k]))", "Object.entries(v).every(([k]) => !(k in spec) || spec[k](v[k]))", [C.h03]),
  m("B4-X148", "list items are not checked", TRANSPORT, "Array.isArray(v) && v.every(check)", "Array.isArray(v)", [C.h03]),
  m("B4-X149", "map values are not checked", TRANSPORT, "isObj(v) && Object.values(v).every(check)", "isObj(v)", [C.h03]),
  m("B4-X150", "any value is one of a set", TRANSPORT, "(v) => values.includes(v)", "() => true", [C.h03]),
  m("B4-X151", "a missing nullable field reads as null", TRANSPORT, "(v) => v === null || check(v)", "(v) => v == null || check(v)", [C.h03]),
  m("B4-X152", "a session-token getter that rejects escapes the adapter", TRANSPORT, "const bearer = await token().catch(() => null);", "const bearer = await token();", [C.h05]),
  m("B4-X153", "a 410 reads as gone in a family that has no gone", TRANSPORT, "422: \"invalid\" }", "422: \"invalid\", 410: \"gone\" }", [C.h02]),
  m("B4-X154", "a write's answer is unwrapped from {data}", TRANSPORT, "body?: unknown, read: Answer = keys)", "body?: unknown, read: Answer = (p) => keys(p.data))", [C.h01]),
  // LAB-09: each action names its capability now that land() is shared
  m("B4-X156", "a launch needs only read access", ACTIONS, 'land("/evaluations", w, "run_evaluation", launch', 'land("/evaluations", w, "read_aggregate_health", launch', [C.a02]),
  m("B4-X157", "a cancel needs only read access", ACTIONS, 'land("/evaluations", w, "run_evaluation", id', 'land("/evaluations", w, "read_aggregate_health", id', [C.a02]),
  m("B4-X158", "a subscription needs only read access", ACTIONS, 'land("/evaluations/checkpoints", w, "run_evaluation"', 'land("/evaluations/checkpoints", w, "read_aggregate_health"', [C.a02]),
  m("B4-X159", "the preview note does not say it is a stand-in", NOTE, "come from an in-memory stand-in, not", "come from", [C.p04]),
];

process.exit(await runMutants({ suite: SUITE, prefix: "B4", mutants: MUTANTS }));
