"""F2C.d: versioned acceptance transcripts of the lifecycle ports.

The exported lifecycle cases (`conformance/lifecycle.py`) assert invariants; this module
records WHAT each process observed while they ran - every port call's normalized answer
or typed refusal, in order, per process (`p1`, `p2`, ... from `reopen()`, and `jobs`), with
every clock move - and commits that transcript as `fixtures/acceptance/lifecycle.json`.
The file is versioned (`VERSION`), regenerated byte-for-byte by a test, and its sha256 is
the F2C fixture hash the evidence records.

A real adapter replays it:

    from infrx.contracts.conformance.acceptance import replay
    assert replay(my_factory) == []          # [] = every case answered exactly as committed

`replay(factory, strict_times=False)` compares everything but relative instants, for an
adapter whose configured windows differ from `CONFIG`. Normalization makes transcripts
adapter-independent: UUIDs and opaque handles become `<id:n>`/`<upl:n>`/`<job:n>` in order
of first appearance, contract instants become `t+<seconds>` from the case's start, and
candidate cursors (an adapter's own encoding) become `<cursor>`.

    uv run --frozen python -m infrx.contracts.conformance.acceptance --write
"""
from __future__ import annotations

import asyncio
import inspect
import itertools
import json
import pathlib
import re
from datetime import datetime
from typing import Any, Callable

from pydantic import BaseModel

from .. import codec, errors, ids
from ..v2.lifecycle import refusal_of
from . import lifecycle
from .harness import Harness

VERSION = "f2c-lifecycle-acceptance.2"
PATH = pathlib.Path(__file__).resolve().parent.parent / "fixtures" / "acceptance" / "lifecycle.json"
# The windows the transcript's instants assume (keywords every lifecycle factory accepts).
CONFIG = {"upload_ttl_s": 3600.0, "grace_s": 60.0, "claim_ttl_s": 30.0, "retention_s": 600.0}
# Asserted by its case, not transcribed: a thousand registrations and a thousand-row page
# would be most of the file and say nothing the case's own assertions do not.
UNRECORDED = frozenset({"retention_durable__candidates_page_without_loss_or_repeat"})

_INSTANT = re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?Z")
_UUID = re.compile(ids.UUID_RE.pattern)
_HANDLE = re.compile(r"(upl|job)_[A-Za-z0-9_-]{22,64}")


class _Log:
    def __init__(self) -> None:
        self.steps: list[dict] = []
        self.t0: datetime | None = None
        self.aliases: dict[str, str] = {}

    def alias(self, value: str, kind: str) -> str:
        if value not in self.aliases:
            count = sum(1 for alias in self.aliases.values() if alias.startswith(f"<{kind}:"))
            self.aliases[value] = f"<{kind}:{count + 1}>"
        return self.aliases[value]

    def instant(self, value: datetime) -> str:
        seconds = (value - self.t0).total_seconds()
        return f"t+{seconds:g}" if seconds >= 0 else f"t{seconds:g}"

    def norm(self, value: Any) -> Any:
        if isinstance(value, BaseModel):
            value = value.model_dump(mode="json", exclude_none=True)
        if isinstance(value, dict):
            return {key: self.norm(item) for key, item in value.items()}
        if isinstance(value, (list, tuple)):
            return [self.norm(item) for item in value]
        if isinstance(value, datetime):
            return self.instant(value)
        if isinstance(value, str):
            if _INSTANT.fullmatch(value):
                return self.instant(datetime.fromisoformat(value.replace("Z", "+00:00")))
            if value.startswith("cc1."):
                return "<cursor>"
            value = _HANDLE.sub(lambda m: self.alias(m.group(0), m.group(1)), value)
            return _UUID.sub(lambda m: self.alias(m.group(0), "id"), value)
        return value


class _Recorder:
    """A port or JobStore seen as process `label`: every async call is logged."""

    def __init__(self, target, log: _Log, label: str) -> None:
        self._target, self._log, self._label = target, log, label

    def __getattr__(self, name: str):
        attribute = getattr(self._target, name)
        if not inspect.iscoroutinefunction(attribute):
            return attribute
        log, label = self._log, self._label

        async def recorded(*args, **kwargs):
            try:
                result = await attribute(*args, **kwargs)
            except errors.DomainError as refused:
                reason = refusal_of(refused)
                log.steps.append({"p": label, "op": name, "refused": {
                    "code": refused.code, **({"reason": reason.value} if reason else {})}})
                raise
            log.steps.append({"p": label, "op": name, "ok": log.norm(result)})
            return result
        return recorded


class _Clock:
    def __init__(self, clock, log: _Log) -> None:
        self._clock, self._log = clock, log

    def now(self) -> datetime:
        return self._clock.now()

    def advance(self, seconds: float) -> datetime:
        moved = self._clock.advance(seconds)
        self._log.steps.append({"clock": self._log.instant(moved)})
        return moved


def _recording(factory: Callable[..., Harness], log: _Log) -> Callable[..., Harness]:
    def make(**kw) -> Harness:
        harness = factory(**{**CONFIG, **kw})
        log.t0 = harness.clock.now()
        extra = dict(harness.extra)
        processes = itertools.count(2)
        if "reopen" in extra:
            reopen = extra["reopen"]
            extra["reopen"] = lambda: _Recorder(reopen(), log, f"p{next(processes)}")
        if "jobs" in extra:
            extra["jobs"] = _Recorder(extra["jobs"], log, "jobs")
        return Harness(port=_Recorder(harness.port, log, "p1"), clock=_Clock(harness.clock, log),
                       ids=harness.ids, failures=harness.failures, extra=extra)
    return make


def record(factory: Callable[..., Harness]) -> dict:
    """Run every lifecycle case against `factory` and return the normalized transcript."""
    cases = {}
    for case in lifecycle.cases():
        if case.__name__ in UNRECORDED:
            continue
        log = _Log()
        try:
            asyncio.run(case(_recording(factory, log)))
        except Exception as failure:          # a failing case is a transcript difference too
            log.steps.append({"raised": type(failure).__name__})
        cases[case.__name__] = log.steps
    return {"version": VERSION, "config": CONFIG, "cases": cases,
            "unrecorded": sorted(UNRECORDED),
            "generated_by": "infrx.contracts.conformance.acceptance (the reference fakes)"}


def committed() -> dict:
    return json.loads(PATH.read_bytes())


def _untimed(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _untimed(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_untimed(item) for item in value]
    return "t" if isinstance(value, str) and re.fullmatch(r"t[+-][0-9.e+-]+", value) else value


def replay(factory: Callable[..., Harness], *, strict_times: bool = True) -> list[str]:
    """Mismatches between `factory`'s transcript and the committed one ([] = accepted)."""
    expected, got = committed(), record(factory)
    if expected["version"] != VERSION:
        return [f"committed transcript is {expected['version']}, this code is {VERSION}"]
    problems = []
    for name, steps in expected["cases"].items():
        mine = got["cases"].get(name)
        if not strict_times:
            steps, mine = _untimed(steps), _untimed(mine)
        if mine == steps:
            continue
        first = next((n for n, (a, b) in enumerate(zip(steps, mine or [])) if a != b),
                     min(len(steps), len(mine or [])))
        problems.append(f"{name}: step {first}: expected "
                        f"{steps[first] if first < len(steps) else 'end'}, got "
                        f"{(mine or [])[first] if first < len(mine or []) else 'end'}")
    return problems


def build() -> bytes:
    from ..fakes.factories import lifecycle_factory
    return codec.canonical_bytes(record(lifecycle_factory))


def main() -> int:
    import argparse
    parser = argparse.ArgumentParser(description="regenerate the F2C acceptance transcript")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    payload = build()
    changed = not PATH.exists() or PATH.read_bytes() != payload
    if args.write and changed:
        PATH.write_bytes(payload)
    print(("wrote " if args.write and changed else "would change " if changed else "unchanged ")
          + str(PATH.name))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

