#!/usr/bin/env node
// P4's mutant runner (R32; LANE-RULES addendum) over tests/p, on the shared Lab harness.
// Usage: node tests/p/run-mutants.mjs [--only ID,ID]
import { m, runMutants } from "../l/shell/harness.mjs";

const SUITE = ["view", "journey", "actions", "pages", "http", "wiring"].map((f) => `tests/p/${f}.test.ts`);
const PORT = "lib/services/pipelines/port.ts";
const ACCESS = "lib/auth/access.ts"; // LAB-07: the one role table
const FAKE = "lib/services/pipelines/fake.ts";
const VIEW = "lib/services/pipelines/view.ts";
const ACTIONS = "lib/services/pipelines/actions.ts";
const ANNOT = "app/(provider)/annotations/page.tsx";
const TRAIN = "app/(provider)/training/page.tsx";
const HTTP = "lib/services/pipelines/http.ts";
const TRANSPORT = "lib/services/http.ts"; // LAB-04: the one transport every family adapter calls
const SHAPES = "lib/services/shapes.ts"; // LAB-10: the shared input shapes
const SERVER = "lib/services/pipelines/server.ts";

const C = {
  v01: "P4-V01 roles mirror ROLE_CAPABILITIES: a viewer runs no pipeline, a developer does, only an administrator assigns",
  v02: "P4-V02 synthetic, imported and reviewed labels never read alike; only a human review is ground truth",
  v03: "P4-V03 only a submitted label can be reviewed, and only by a role that runs pipelines",
  v04: "P4-V04 an import receipt lists every rejected row with its reason; an unknown reason is not echoed",
  v05: "P4-V05 an export shows its lineage (sample → labels and methods) and every omitted sample with its reason",
  v06: "P4-V06 a training run shows its USD budget and named payer, config, data and holdout pin",
  v07: "P4-V07 an ambiguous submission reads as unknown with its hold, and offers no resubmit or cancel",
  v08: "P4-V08 cost is unsettled, unknown or as reported, never estimated; the manual bundle holds nothing",
  v09: "P4-V09 run actions follow the record: submit a prepared bundle, finish a manual one, cancel live ones; none for a viewer",
  v10: "P4-V10 a rejected checkpoint shows its reason and is never evaluated or approvable",
  v11: "P4-V11 lineage runs from the checkpoint to its run, data, export, config and holdout pin",
  v12: "P4-V12 approval needs a succeeded evaluation on exactly the run's pinned holdout; training metrics never promote",
  v13: "P4-V13 a refusal is fixed copy for a known reason and nothing for anything else in the URL",
  v14: "P4-V14 the pipelines port fails closed: unavailable until the real adapter is wired, the preview never in production",
  j01: "P4-J01 import → correction → adjudication → train-only export: methods kept apart, lineage and omissions recorded",
  j02: "P4-J02 manual bundle → submit (nothing reserved) → finish → checkpoint → held-out evaluation → eligible, all replay-safe",
  j03: "P4-J03 a bad, late or mismatched checkpoint is rejected with its reason and never evaluated; a redelivery keeps the first outcome",
  j04: "P4-J04 an ambiguous submission is only ever looked up, never resubmitted; a revoked grant stops a submit",
  j05: "P4-J05 unauthorized variants: another provider, a viewer, a developer assigning, a foreign payer, an expired export",
  a01: "P4-A01 actions run as the session's provider and role, whatever the form claims",
  a02: "P4-A02 a role without the capability is refused before the pipeline service is asked",
  a03: "P4-A03 malformed input, another provider's payer or dataset, or an unknown op never reaches the pipeline service",
  a04: "P4-A04 the training connector is always the manual bundle, never the form's; a double submit is one run",
  a05: "P4-A05 the service's refusal is carried as its reason; its success is a plain return to the records",
  a06: "P4-A06 a consumer-only user gets a 404 from every action and the pipeline service is never asked",
  p01: "P4-P01 each page reads the pipeline records as the session's workspace and shows ?refused= only as fixed copy",
  p02: "P4-P02 every import, export, bundle and checkpoint form carries an id minted at render, never typed or re-minted by the action",
  p03: "P4-P03 the paid forms show the USD budget and named payer, and no form picks a connector",
  p04: "P4-P04 labels show their kind and ground-truth status apart; the preview stand-in is labelled only when it is on",
  h01: "P4-H01 every call is the session's token and the actor's provider on its route; keys are renamed both ways, values untouched",
  h02: "P4-H02 the route's refusals are the port's reasons (410 is gone); anything else, or no answer, is unavailable",
  h03: "P4-H03 the route's records pass (renamed only); one unreadable row fails the whole answer closed",
  h04: "P4-H04 without a session token nothing is sent and every call is unavailable",
  h05: "P4-H05 a session-token getter that rejects is no session: nothing is sent and every call is unavailable",
  w01: "P4-W01 LAB_PIPELINES_API_URL set: the port reads the route as the session's own access token",
  w02: "P4-W02 a missing LAB_PIPELINES_API_URL or Supabase config fails closed: every call unavailable, nothing sent",
  v15: "P4-V15 a teacher dry run shows its USD budget, named payer, cost ceiling and each chunk's reservation; nothing is reserved or sent",
  v16: "P4-V16 only an administrator approves, only a dry run within its budget, and never twice",
  v17: "P4-V17 each chunk reads as its ledger records it: held, ambiguous (never resent), settled or unknown cost, stopped, failures counted",
  j06: "P4-J06 teacher batch: a dry run sends nothing; only an administrator approves within the budget; a double click is one batch; ambiguous, stopped and unauthorized variants",
  a07: "P4-A07 a teacher dry run and its approval: the session's actor and the form's batch id; a developer never approves; malformed input never reaches the service",
  p05: "P4-P05 the teacher section: a dry-run form with its batch id minted at render, its USD budget and payer; approval only where the view allows it; unavailable said as such",
  h06: "P4-H06 teacher batches: listed, planned (the form's batch id, snake_case) and approved on their routes; an unreadable batch or chunk fails closed",
};

const MUTANTS = [
  // port
  m("P4-X01", "a viewer may run pipelines", ACCESS, 'viewer: ["read_aggregate_health"],', 'viewer: ["read_aggregate_health", "run_evaluation"],', [C.v01, C.a02, C.j05]),
  m("P4-X02", "a developer may assign reviewers", ACCESS, '"manage_dev_deployment", "run_evaluation"],\n  administrator', '"manage_dev_deployment", "run_evaluation", "manage_members"],\n  administrator', [C.v01, C.a02, C.j05]),
  m("P4-X03", "the preview stand-in runs in production", PORT, ' && env.NODE_ENV !== "production"', "", [C.v14]),
  m("P4-X04", "the default port is the stand-in, not unavailable", PORT, "labPipelines(env) ?? UNAVAILABLE", "labPipelines(env) ?? (preview ??= new FakePipelines())", [C.v14, C.w02]),
  m("P4-X05", "any preview flag value turns the stand-in on", PORT, 'env.LAB_PIPELINES_PREVIEW === "1"', "env.LAB_PIPELINES_PREVIEW !== undefined", [C.v14]),
  // view
  m("P4-X06", "a synthetic label reads as an imported one", VIEW, 'synthetic: "Synthetic (model-generated)",', 'synthetic: "Imported (external human pipeline)",', [C.v02]),
  m("P4-X07", "any label flagged ground truth reads as ground truth", VIEW, 'l.method === "human" && l.groundTruth ?', "l.groundTruth ?", [C.v02]),
  m("P4-X08", "a decided label can be reviewed again", VIEW, 'reviewable: l.state === "submitted" && ', "reviewable: ", [C.v03]),
  m("P4-X09", "a viewer may review", VIEW, 'l.state === "submitted" && holds(role, "run_evaluation"),', 'l.state === "submitted",', [C.v03]),
  m("P4-X10", "an unknown import reason is echoed", VIEW, '(IMPORT_REFUSALS as readonly string[]).includes(x.reason) ? IMPORT_COPY[x.reason] : "rejected (reason not recognised)"', "IMPORT_COPY[x.reason] ?? x.reason", [C.v04]),
  m("P4-X11", "rejected rows are not counted", VIEW, "${r.rejected.length} rejected", "0 rejected", [C.v04]),
  m("P4-X12", "export lineage hides the label methods", VIEW, ' (${x.methods.join(", ")})', "", [C.v05]),
  m("P4-X13", "omitted samples are dropped from the export", VIEW, "omitted: e.omitted.map((x) => `${x.sampleId}: ${x.reason}`),", "omitted: [],", [C.v05]),
  m("P4-X14", "the budget hides what is reserved", VIEW, "budget: `limit ${r.limitUsd} USD · reserved ${r.reservedUsd} USD`", "budget: `limit ${r.limitUsd} USD`", [C.v06]),
  m("P4-X15", "the payer is not the run's", VIEW, "payer: r.payerRef,", 'payer: "workspace default",', [C.v06]),
  m("P4-X16", "the holdout pin is hidden", VIEW, "pinned ${r.holdout.sha256}", "pinned", [C.v06]),
  m("P4-X17", "an ambiguous submission reads as submitted", VIEW, 'case "ambiguous": return `Submission outcome unknown: ${r.reservedUsd} USD held until it is looked up; it is never resubmitted.`;', 'case "ambiguous": return "Submitted.";', [C.v07]),
  m("P4-X18", "an ambiguous submission offers a resubmit", VIEW, 'if (r.state === "prepared") actions.push("submit");', 'if (r.state === "prepared" || r.state === "ambiguous") actions.push("submit");', [C.v07]),
  m("P4-X19", "cancel is offered on any unfinished run", VIEW, 'if (r.state === "prepared" || r.state === "submitted") actions.push("cancel");', 'if (r.state !== "completed") actions.push("cancel");', [C.v07, C.v09]),
  m("P4-X20", "an unknown cost is estimated", VIEW, 'r.costUsd === null ? "Unknown: the provider reported no cost. It is never estimated." :', "r.costUsd === null ? `${r.limitUsd} USD (estimated).` :", [C.v08]),
  m("P4-X21", "an unsettled run reads as settled", VIEW, '  if (!r.settled) return "Not settled yet.";\n', "", [C.v08]),
  m("P4-X22", "the manual bundle reads as a platform charge", VIEW, '  if (manual(r)) return "Nothing reserved or charged: the manual bundle trains on your own compute.";\n', "", [C.v08]),
  m("P4-X23", "finish is offered on an automatic run", VIEW, 'if (r.state === "submitted" && manual(r)) actions.push("finish");', 'if (r.state === "submitted") actions.push("finish");', [C.v09]),
  m("P4-X24", "a viewer gets run actions", VIEW, '    if (holds(role, "run_evaluation")) {\n', "    {\n", [C.v09]),
  m("P4-X25", "a failure hides its reason", VIEW, 'return `Failed: ${r.reason ?? "no reason recorded"}.`;', 'return "Failed.";', [C.v09]),
  m("P4-X26", "an unknown checkpoint reason is echoed", VIEW, ': "Rejected: reason not recognised."', ": `Rejected: ${reason}.`", [C.v10]),
  m("P4-X27", "a rejected checkpoint reads as evaluated", VIEW, "state: c.state === \"rejected\" ? rejection(c.reason)\n", "state: c.state === \"rejected\" ? \"Held-out evaluation queued.\"\n", [C.v10]),
  m("P4-X28", "lineage skips the dataset", VIEW, "→ ${r.datasetRef} · export ${r.export.exportId}", "→ export ${r.export.exportId}", [C.v11]),
  m("P4-X29", "an orphan checkpoint claims a lineage", VIEW, "r === undefined ? `run ${c.externalRunId} is not in this workspace's records`", "r === undefined ? c.externalRunId", [C.v11]),
  m("P4-X30", "an evaluation on another split approves", VIEW, 'e.split === "holdout" && ', "", [C.v12]),
  m("P4-X31", "an evaluation on another holdout pin approves", VIEW, " && e.holdoutSha256 === r.holdout.sha256", "", [C.v12]),
  m("P4-X32", "an unfinished evaluation approves", VIEW, 'onHoldout && e!.state === "succeeded"', "onHoldout", [C.v12]),
  m("P4-X33", "an eligible candidate is offered approval again", VIEW, "approvable: passed && !c.eligible && ", "approvable: passed && ", [C.v12]),
  m("P4-X34", "a viewer may approve", VIEW, 'approvable: passed && !c.eligible && holds(role, "run_evaluation"),', "approvable: passed && !c.eligible,", [C.v12]),
  m("P4-X35", "an eligible candidate reads as published", VIEW, '"Eligible candidate: not public and not promoted."', '"Published."', [C.v12]),
  m("P4-X36", "any ?refused= string is looked up", VIEW, "(REFUSALS as readonly unknown[]).includes(value) ?", 'typeof value === "string" ?', [C.v13]),
  // fake (the route's contract)
  m("P4-X37", "reads are not scoped to the provider", FAKE, "rows.filter((r) => r.providerId === actor.providerId).map((r) => bare<T>(r))", "rows.map((r) => bare<T>(r))", [C.j05]),
  m("P4-X38", "another provider's dataset is served", FAKE, "return d?.providerId === actor.providerId ? d : undefined;", "return d;", [C.j05]),
  m("P4-X39", "another provider's run is served", FAKE, "r.externalRunId === id && r.providerId === actor.providerId", "r.externalRunId === id", [C.j05]),
  m("P4-X40", "a row claiming ground truth is imported", FAKE, '        : (row.ground_truth ?? false) !== false ? "forged_ground_truth"\n', "\n", [C.j01]),
  m("P4-X41", "an imported human label becomes ground truth", FAKE, 'groundTruth: fields.method === "human",', 'groundTruth: fields.method !== "synthetic",', [C.j01]),
  m("P4-X42", "an ungranted sample is imported", FAKE, 'sample.readable === false ? "grant_not_current"', 'false ? "grant_not_current"', [C.j01]),
  m("P4-X43", "an import replay with other rows is accepted", FAKE, 'if (prior) return prior.body === body ? ok(bare<ImportReceipt>(prior)) : no("conflict");', "if (prior) return ok(bare<ImportReceipt>(prior));", [C.j01]),
  m("P4-X44", "a correction writes no human label", FAKE, "if (input.correction !== null) this.label(", "if (false) this.label(", [C.j01]),
  m("P4-X45", "a decided label is reviewed again", FAKE, 'if (row.state !== "submitted") return row.state === input.decision && input.correction === null ? ok(null) : no("conflict");', "", [C.j01]),
  m("P4-X46", "adjudication leaves the disputed labels live", FAKE, 'r.state = r.state === "accepted" ? "superseded" : "rejected";', "void r;", [C.j01]),
  m("P4-X47", "a holdout sample is exported", FAKE, 'const reason = s.split !== "train" ? s.split :', 'const reason = s.split === "validation" ? s.split :', [C.j01, C.j02]),
  m("P4-X48", "a disputed sample is exported", FAKE, 'values.size > 1 ? "disagreement"', 'false ? "disagreement"', [C.j01]),
  m("P4-X49", "an export replay with another adapter is accepted", FAKE, 'if (prior) return prior.body === body ? ok(bare<LabelExport>(prior)) : no("conflict");', "if (prior) return ok(bare<LabelExport>(prior));", [C.j01]),
  m("P4-X50", "a prepare replay with another budget is accepted", FAKE, 'if (prior) return prior.body === body ? ok(bare<TrainingRun>(prior)) : no("conflict");', "if (prior) return ok(bare<TrainingRun>(prior));", [C.j02]),
  m("P4-X51", "another provider's payer pays", FAKE, "\n      || !input.payerRef.startsWith(`lab:payer:${actor.providerId}:`)", "", [C.j05]),
  m("P4-X52", "an expired export is bundled", FAKE, '    if (exp.expired) return no("gone");\n', "", [C.j05]),
  m("P4-X53", "the bundle names an automatic connector", FAKE, 'connector: MANUAL, state: "prepared"', 'connector: "vendor-x", state: "prepared"', [C.j02]),
  m("P4-X54", "the manual bundle reserves budget", FAKE, "if (r.connector !== MANUAL) this.reservations += 1;", "this.reservations += 1;", [C.j02]),
  m("P4-X55", "an ambiguous submission is submitted again", FAKE, 'if (r.state === "ambiguous") {', "if (false) {", [C.j04]),
  m("P4-X56", "a revoked grant still submits", FAKE, 'if ([...r.bundled.train, ...r.bundled.dev].some((id) => !readable.has(id))) return no("denied");', "", [C.j04]),
  m("P4-X57", "an ambiguous run can be cancelled", FAKE, 'if (!["prepared", "submitted"].includes(r.state)) return no("conflict");', 'if (r.state === "completed") return no("conflict");', [C.j04]),
  m("P4-X58", "a prepared run can be finished", FAKE, 'if (!["submitted", "completed"].includes(r.state)) return no("conflict");', "", [C.a05]),
  m("P4-X59", "a late checkpoint is accepted", FAKE, '!["submitted", "completed"].includes(r.state) ? `run_${r.state}` : ', "", [C.j03]),
  m("P4-X60", "a checkpoint of other bytes is accepted", FAKE, ' : stored !== input.artifactDigest ? "digest_mismatch"', "", [C.j03]),
  m("P4-X61", "a missing artifact reads as a digest mismatch", FAKE, 'stored === undefined ? "missing_artifact" : ', "", [C.j03]),
  m("P4-X62", "a redelivery is judged again", FAKE, "    if (prior) return ok(bare<Checkpoint>(prior));\n", "", [C.j03]),
  m("P4-X63", "a checkpoint outside its run's prefix is taken", FAKE, 'if (!input.artifactKey.startsWith(`lab/${actor.providerId}/training/${input.externalRunId}/`)) return no("invalid");', "", [C.j03]),
  m("P4-X64", "a rejected checkpoint is queued for evaluation", FAKE, "if (!reason) this.evaluationsQueued += 1;", "this.evaluationsQueued += 1;", [C.j03]),
  m("P4-X65", "approval without a succeeded evaluation", FAKE, 'if (c?.evaluation?.state !== "succeeded") return no("conflict");', 'if (!c) return no("conflict");', [C.j02]),
  m("P4-X66", "the role is not checked", FAKE, 'return holds(actor.role, capability) ? null : "denied";', "return void capability, null;", [C.j05]),
  m("P4-X67", "assigning needs only run_evaluation", FAKE, 'const refused = this.gate(actor, "manage_members");\n    if (refused) return no(refused);\n    return this.set(', "const refused = this.gate(actor);\n    if (refused) return no(refused);\n    return this.set(", [C.j05]),
  // actions
  m("P4-X68", "an import acts as the form's provider", ACTIONS, "pipelinesPort().importLabels(actor(w),", 'pipelinesPort().importLabels({ providerId: String(data.get("providerId")), role: w.role },', [C.a01]),
  m("P4-X69", "the actor's role is not the session's", ACTIONS, "({ providerId: w.providerId, role: w.role });", '({ providerId: w.providerId, role: "administrator" });', [C.a01]),
  m("P4-X70", "the capability check is skipped", ACTIONS, '!holds(w.role, capability) ? "denied" : ', "", [C.a02]),
  m("P4-X71", "malformed input reaches the pipeline service", ACTIONS, ' : !valid ? "invalid"', "", [C.a03]),
  m("P4-X72", "another provider's refs pass as this provider's", ACTIONS, ":${w.providerId}:${UUID}@", ":${UUID}:${UUID}@", [C.a03]),
  m("P4-X73", "any USD amount passes", SHAPES, "USD_RE = /^(0|[1-9][0-9]{0,11})\\.[0-9]{8}$/;", "USD_RE = /./;", [C.a03]),
  m("P4-X74", "any id passes as a run id", SHAPES, "UUID_RE = new RegExp(`^${UUID}$`);", "UUID_RE = /./;", [C.a03]),
  m("P4-X75", "any objective passes", ACTIONS, 'oneOf(data, "objective", ["sft", "preference"] as const)', 'text(data, "objective") as "sft"', [C.a03]),
  m("P4-X76", "any op reaches the service", ACTIONS, 'const op = oneOf(data, "op", ["submit", "finish", "cancel"] as const);', 'const op = text(data, "op") as "submit" | null;', [C.a03]),
  m("P4-X77", "a correction may accept", ACTIONS, '(raw === "" || (correction !== null && decision === "rejected"))', '(raw === "" || correction !== null)', [C.a03]),
  m("P4-X78", "an export may outlive N2's bound", ACTIONS, "ttlS <= MAX_EXPORT_TTL_S", "ttlS <= 9_999_999", [C.a03]),
  m("P4-X79", "the connector is read from the form", ACTIONS, "      config: { objective: objective!,", '      connector: text(data, "connector"), config: { objective: objective!,', [C.a04]),
  m("P4-X80", "a refusal is dropped on the way back", ACTIONS, 'redirect(result.ok ? page : `${page}${page.includes("?") ? "&" : "?"}refused=${result.reason}`);', "redirect(page);", [C.a02, C.a05]),
  m("P4-X81", "a success is flagged by the action, not the records", ACTIONS, "redirect(result.ok ? page :", 'redirect(result.ok ? `${page}${page.includes("?") ? "&" : "?"}done=1` :', [C.a01, C.a05]),
  m("P4-X82", "an action runs without a provider workspace", ACTIONS, "export async function runAction(data: FormData): Promise<void> {\n  const w = await requireProviderWorkspace();",
    'export async function runAction(data: FormData): Promise<void> {\n  const w = { providerId: "11111111-1111-4111-8111-111111111111", providerName: "x", role: "administrator" } as const;', [C.a06]),
  m("P4-X83", "assigning needs only run_evaluation in the action", ACTIONS, '"manage_members", ![datasetRef', '"run_evaluation", ![datasetRef', [C.a02]),
  m("P4-X84", "the action mints a run id when the form has none", ACTIONS, 'const externalRunId = field(data, "externalRunId", ID);\n  const datasetRef', 'const externalRunId = field(data, "externalRunId", ID) ?? globalThis.crypto.randomUUID();\n  const datasetRef', [C.p02, C.a03]),
  // pages
  m("P4-X85", "a page reads records as a fixed provider", TRAIN, "const actor = { providerId: workspace.providerId, role: workspace.role };", 'const actor = { providerId: "11111111-1111-4111-8111-111111111111", role: workspace.role };', [C.p01]),
  m("P4-X86", "a page shows ?refused= raw", ANNOT, "const refused = refusalCopy(query.refused);", 'const refused = String(query.refused ?? "") || null;', [C.p01]),
  m("P4-X87", "a page claims success on its own", TRAIN, "<h1>Training</h1>", "<h1>Training</h1>\n      <p>Submitted successfully.</p>", [C.p01]),
  m("P4-X88", "the run id is typed, not minted at render", TRAIN, '<input type="hidden" name="externalRunId" value={randomUUID()} />', '<input name="externalRunId" required />', [C.p02]),
  m("P4-X89", "the import id is not minted at render", ANNOT, '<input type="hidden" name="importId" value={randomUUID()} />', '<input name="importId" />', [C.p02]),
  m("P4-X90", "the export id is not minted at render", ANNOT, '<input type="hidden" name="exportId" value={randomUUID()} />', "", [C.p02]),
  m("P4-X91", "the checkpoint id is not minted at render", TRAIN, '<input type="hidden" name="checkpointId" value={randomUUID()} />', '<input name="checkpointId" />', [C.p02]),
  m("P4-X92", "the payer is not asked for", TRAIN, '<input name="payerRef" required placeholder="lab:payer:…" />', '<input type="hidden" name="payerRef" value="" />', [C.p03]),
  m("P4-X93", "the budget is not labelled USD", TRAIN, "<legend>Budget (USD)</legend>", "<legend>Budget</legend>", [C.p03]),
  m("P4-X94", "a run row hides its payer", TRAIN, "<td>{r.budget} · payer {r.payer}</td>", "<td>{r.budget}</td>", [C.p03]),
  m("P4-X95", "the form picks a connector", TRAIN, '<button type="submit">Prepare bundle</button>', '<input name="connector" defaultValue="vendor-x" />\n            <button type="submit">Prepare bundle</button>', [C.p03]),
  m("P4-X96", "automatic connectors are advertised", TRAIN, "Automatic training connectors are not offered", "Automatic training connectors are available", [C.p03]),
  m("P4-X97", "a label's ground-truth status is not shown", ANNOT, "<td>{l.kind}</td><td>{l.truth}</td>", "<td>{l.kind}</td><td>{l.state}</td>", [C.p04]),
  m("P4-X98", "the preview label shows when the stand-in is off", TRAIN, '{isPreview() && <p role="note">', '{<p role="note">', [C.p04]),
  // the HTTP adapter (WR-P4-1, lane lab-api-2)
  m("P4-X99", "the session token is not sent", TRANSPORT, "authorization: `Bearer ${bearer}`", "authorization: \"Bearer\"", [C.h01]),
  m("P4-X100", "the provider is not the actor's", TRANSPORT, "encodeURIComponent(actor.providerId)", "\"\"", [C.h01]),
  m("P4-X101", "a list is not unwrapped from {data}", HTTP, "const list: Answer = (p) => camel(p.data);", "const list: Answer = (p) => camel(p);", [C.h01]),
  m("P4-X102", "records keep the route's snake_case keys", TRANSPORT, "k.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase())", "k", [C.h01]),
  m("P4-X103", "bodies go out in the port's camelCase", TRANSPORT, "k.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`)", "k", [C.h01]),
  m("P4-X104", "nested keys are not renamed", TRANSPORT, "[to(k), deep(v)]", "[to(k), v]", [C.h01]),
  m("P4-X105", "a list of records is not renamed", TRANSPORT, "Array.isArray(value) ? value.map(deep)", "Array.isArray(value) ? value", [C.h01]),
  m("P4-X106", "the dataset is not the query's", HTTP, "`&dataset_ref=${encodeURIComponent(datasetRef)}`", '""', [C.h01]),
  m("P4-X107", "the bundle is not the route's JSON text", HTTP, "str, (p) => (obj({})(p) ? JSON.stringify(p) : null)", "str, list", [C.h01]),
  m("P4-X108", "the export pin is flattened", HTTP, "export: { format: exportFormat, export_id: exportId }", "export_format: exportFormat, export_id: exportId", [C.h01]),
  m("P4-X109", "the USD limit is sent under the port's key", HTTP, "limit: limitUsd }", "limit_usd: limitUsd }", [C.h01]),
  m("P4-X110", "a review answer leaks the route's record", HTTP, 'post(actor, "assignments", any, snake(input), none)', 'post(actor, "assignments", any, snake(input))', [C.h01]),
  m("P4-X111", "a submit is a read", HTTP, "submit: (actor, id) => post(actor, `${run(id)}/submit`, RUN)", "submit: (actor, id) => get(actor, `${run(id)}/submit`, RUN, camel)", [C.h01]),
  m("P4-X112", "the approval drops its run", HTTP, "{ external_run_id: externalRunId }", "{}", [C.h01]),
  m("P4-X113", "the body is not declared JSON", TRANSPORT, "if (body !== undefined) headers[\"content-type\"] = \"application/json\";", "", [C.h01]),
  m("P4-X114", "an expired export reads as unavailable", HTTP, ", 410: \"gone\" as const", "", [C.h02]),
  m("P4-X115", "no session reads as unavailable", TRANSPORT, "401: \"denied\", ", "", [C.h02]),
  m("P4-X116", "a missing capability reads as not found", TRANSPORT, "403: \"denied\"", "403: \"not_found\"", [C.h02]),
  m("P4-X117", "an unmapped status is invalid", TRANSPORT, "?? \"unavailable\"", "?? \"invalid\"", [C.h02]),
  m("P4-X118", "no answer is invalid", TRANSPORT, "return { ok: false, reason: \"unavailable\" }; // transport", "return { ok: false, reason: \"invalid\" }; // transport", [C.h02]),
  // the swap (WR-P4-1): the configured adapter, the session's token, the row check
  m("P4-X119", "the configured adapter is ignored", PORT, "return labPipelines(env) ?? UNAVAILABLE;", "return UNAVAILABLE;", [C.w01]),
  m("P4-X120", "another server env names the backend", SERVER, "labApiUrl(env, \"pipelines\")", "labApiUrl(env, \"evaluation\")", [C.w01]),
  m("P4-X121", "the token is not the session's", SERVER, "token: sessionToken(config)", "token: async () => config.anonKey", [C.w01]),
  m("P4-X122", "a call is sent without a session token", TRANSPORT, "    if (!bearer) return { ok: false, reason: \"unavailable\" }; // no session: nothing is sent\n", "", [C.h04, C.w01]),
  m("P4-X123", "an answer is not checked", TRANSPORT, "return readable(value) ? { ok: true, value: value as T } : { ok: false, reason: \"unavailable\" };", "return { ok: true, value: value as T };", [C.h03]),
  m("P4-X124", "an unknown label method is read", HTTP, 'const METHOD = oneOf("imported", "synthetic", "human");', "const METHOD = str;", [C.h03]),
  m("P4-X125", "a label without its ground-truth flag is read", HTTP, "method: METHOD, groundTruth: bool,", "method: METHOD,", [C.h03]),
  m("P4-X126", "an unknown label state is read", HTTP, 'state: oneOf("submitted", "accepted", "rejected", "superseded")', "state: str", [C.h03]),
  m("P4-X127", "a disagreement's refs are not a list", HTTP, "annotationRefs: many(str)", "annotationRefs: () => true", [C.h03]),
  m("P4-X128", "an unknown import refusal is read", HTTP, "reason: among(() => IMPORT_REFUSALS)", "reason: str", [C.h03]),
  m("P4-X129", "a receipt without its count is read", HTTP, "datasetRef: str, accepted: num,", "datasetRef: str,", [C.h03]),
  m("P4-X130", "an unknown lineage method is read", HTTP, "methods: many(METHOD)", "methods: many(str)", [C.h03]),
  m("P4-X131", "an export without its expiry is read", HTTP, "items: num, expiresAt: str,", "items: num,", [C.h03]),
  m("P4-X132", "an unknown export adapter is read", HTTP, "adapter: among(() => ADAPTERS)", "adapter: str", [C.h03]),
  m("P4-X133", "an export's omissions are not checked", HTTP, "omitted: many(obj({ sampleId: str, reason: str })),", "", [C.h03]),
  m("P4-X134", "a USD amount that is not an exact string is read", HTTP, "limitUsd: str, reservedUsd: str,", "limitUsd: () => true, reservedUsd: str,", [C.h03]),
  m("P4-X135", "an unknown run state is read", HTTP, 'state: oneOf("prepared", "submitting", "submitted", "ambiguous", "completed", "failed", "cancelled"),', "state: str,", [C.h03]),
  m("P4-X136", "a run without its config is read", HTTP, '  config: obj({ objective: oneOf("sft", "preference"), adaptation: oneOf("full", "lora"), baseModel: str }),\n', "", [C.h03]),
  m("P4-X137", "an unknown cost (null) and a missing one read alike", HTTP, "bool, costUsd: nul(str), reason", "bool, costUsd: (v) => v == null || typeof v === \"string\", reason", [C.h03]),
  m("P4-X138", "a holdout without its pin is read", HTTP, "holdout: obj({ size: num, sha256: str })", "holdout: obj({ size: num })", [C.h03]),
  m("P4-X139", "a run without its settled flag is read", HTTP, "settled: bool, costUsd", "costUsd", [C.h03]),
  m("P4-X140", "an unknown evaluation state is read", HTTP, 'state: oneOf("queued", "running", "succeeded", "failed")', "state: str", [C.h03]),
  m("P4-X141", "a checkpoint without eligibility is read", HTTP, "reason: nul(str), eligible: bool,", "reason: nul(str),", [C.h03]),
  m("P4-X142", "an unknown checkpoint state is read", HTTP, 'state: oneOf("rejected", "validated")', "state: str", [C.h03]),
  m("P4-X143", "a bundle that is not an object is read", HTTP, "(obj({})(p) ? JSON.stringify(p) : null)", "JSON.stringify(p)", [C.h03]),
  m("P4-X144", "a list answer that is one record is read", HTTP, 'get(actor, "labels", many(LABEL), list, set(datasetRef))', 'get(actor, "labels", (v) => many(LABEL)(v) || LABEL(v), list, set(datasetRef))', [C.h03]),
  m("P4-X145", "a prepared run's answer is not checked", HTTP, 'post(actor, "training-runs", RUN, {', 'post(actor, "training-runs", () => true, {', [C.h03]),
  m("P4-X146", "a submit's answer is not checked", HTTP, "post(actor, `${run(id)}/submit`, RUN)", "post(actor, `${run(id)}/submit`, () => true)", [C.h03]),
  m("P4-X147", "an import's answer is not checked", HTTP, 'post(actor, "label-imports", RECEIPT, snake(input))', 'post(actor, "label-imports", () => true, snake(input))', [C.h03]),
  m("P4-X148", "an export's answer is not checked", HTTP, 'post(actor, "label-exports", EXPORT, snake(input))', 'post(actor, "label-exports", () => true, snake(input))', [C.h03]),
  m("P4-X149", "a checkpoint import's answer is not checked", HTTP, 'post(actor, "checkpoints", CHECKPOINT, snake(input))', 'post(actor, "checkpoints", () => true, snake(input))', [C.h03]),
  m("P4-X150", "an approval's answer is not checked", HTTP, "/approve`, CHECKPOINT, {", "/approve`, () => true, {", [C.h03]),
  m("P4-X151", "a session-token getter that rejects escapes the adapter", TRANSPORT, "const bearer = await token().catch(() => null);", "const bearer = await token();", [C.h05]),
  m("P4-X215", "a write's answer keeps the route's snake_case keys (no rename)", HTTP, "410: \"gone\" as const }, rename: camel }", "410: \"gone\" as const } }", [C.h01]),
  // P4.b: teacher batches (P2 over the route) — the view
  m("P4-X152", "the teacher budget hides its payer", VIEW, "budget: `budget ${b.budgetUsd} USD · payer ${b.payerRef}`", "budget: `budget ${b.budgetUsd} USD`", [C.v15]),
  m("P4-X153", "an unpriced batch reads as priced", VIEW, 'b.ceilingUsd === null ? "Unpriced: no approved rate for this teacher, so it cannot be approved."', 'b.ceilingUsd === null ? "ceiling 0 USD"', [C.v15]),
  m("P4-X154", "an over-budget ceiling is not said", VIEW, '${b.withinBudget ? "" : " · over the budget: it cannot be approved"}', "", [C.v15]),
  m("P4-X155", "the plan hides the holdout it leaves out", VIEW, "${b.holdout} held-out samples left out", "held-out samples left out", [C.v15]),
  m("P4-X156", "the plan hides the samples that may not leave", VIEW, "${b.notPermitted} not permitted", "0 not permitted", [C.v15]),
  m("P4-X157", "a dry run reads as sent", VIEW, '"Dry run: nothing reserved or sent."', '"Submitted."', [C.v15]),
  m("P4-X158", "a chunk hides its reservation", VIEW, ': `reservation ${c.ceilingUsd ?? "unpriced"} USD · not reserved, nothing sent`);', ': "not reserved, nothing sent");', [C.v15]),
  m("P4-X159", "teacher labels read as ground truth", VIEW, "imported as synthetic (model-generated), never ground truth.", "imported as ground truth.", [C.v15]),
  m("P4-X160", "a developer may approve a teacher batch", VIEW, 'b.withinBudget && holds(role, "manage_members"),', 'b.withinBudget && holds(role, "run_evaluation"),', [C.v16]),
  m("P4-X161", "an over-budget batch is approvable", VIEW, "approvable: b.approval === null && b.withinBudget && ", "approvable: b.approval === null && ", [C.v16]),
  m("P4-X162", "an approved batch is offered approval again", VIEW, "approvable: b.approval === null && b.withinBudget", "approvable: b.withinBudget", [C.v16]),
  m("P4-X163", "the approval hides who and when", VIEW, "`Approved by ${b.approval.approvedBy} at ${b.approval.approvedAt}.`", '"Approved."', [C.v16]),
  m("P4-X164", "an ambiguous chunk reads as submitted", VIEW, 'case "ambiguous": return `${head}outcome unknown: ${c.reservedUsd} USD held; it is never resent, only looked up`;', 'case "ambiguous": return `${head}submitted`;', [C.v17]),
  m("P4-X165", "an unknown teacher cost is estimated", VIEW, 'c.costUsd === null ? "cost unknown: the teacher reported none (never estimated)"', "c.costUsd === null ? `cost ${c.reservedUsd} USD (estimated)`", [C.v17]),
  m("P4-X166", "a held chunk hides its failures", VIEW, "return `${head}${c.sent} sent · ${c.reservedUsd} USD held${failures(c)}`;", "return `${head}${c.sent} sent · ${c.reservedUsd} USD held`;", [C.v17]),
  m("P4-X167", "an unknown failure reason is echoed", VIEW, 'Object.hasOwn(TEACHER_FAILURES, f.reason) ? TEACHER_FAILURES[f.reason] : "reason not recognised"', "TEACHER_FAILURES[f.reason] ?? f.reason", [C.v17]),
  m("P4-X168", "failures are not counted", VIEW, "(counts.get(copy) ?? 0) + 1", "1", [C.v17]),
  m("P4-X169", "a stopped chunk reads as a dry run", VIEW, "chunkCopy(c, b.approval !== null)", "chunkCopy(c, false)", [C.v17]),
  m("P4-X170", "a failed chunk reads as held", VIEW, '    case "failed":\n    case "cancelled": return `${head}${c.state}: the hold is released`;\n', "", [C.v17]),
  // the fake (the route's contract)
  m("P4-X171", "a dry run sends", FAKE, "    this.teachers.push(b);\n", "    this.teachers.push(b);\n    this.teacherSends += 1;\n", [C.j06]),
  m("P4-X172", "another batch under a batch id is accepted", FAKE, 'if (prior) return prior.body === body ? ok(bare<TeacherBatch>(prior)) : no("conflict");', "if (prior) return ok(bare<TeacherBatch>(prior));", [C.j06]),
  m("P4-X173", "the role is checked before the batch is found", FAKE, '    if (!b) return no("not_found");\n    const refused = this.gate(actor, "manage_members");\n    if (refused) return no(refused);\n',
    '    const refused = this.gate(actor, "manage_members");\n    if (refused) return no(refused);\n    if (!b) return no("not_found");\n', [C.j06]),
  m("P4-X174", "a developer approves a teacher batch", FAKE, 'this.gate(actor, "manage_members");\n    if (refused) return no(refused);\n    if (!b.withinBudget)', "this.gate(actor);\n    if (refused) return no(refused);\n    if (!b.withinBudget)", [C.j06]),
  m("P4-X175", "an over-budget or unpriced batch is approved", FAKE, '    if (!b.withinBudget) return no("conflict");\n', "", [C.j06]),
  m("P4-X176", "live submission off still sends", FAKE, '    if (!this.teacherLive) return no("unavailable");\n', "", [C.j06]),
  m("P4-X177", "a resume resends reserved chunks", FAKE, '      if (c.state !== "unreserved") continue;', "      if (false) continue;", [C.j06]),
  m("P4-X178", "the payer's budget does not stop the batch", FAKE, "      if (held + units(c.ceilingUsd!) > units(this.payerBudgetUsd)) break;", "", [C.j06]),
  m("P4-X179", "another provider's payer pays a teacher", FAKE, "if (!set || !input.payerRef.startsWith(`lab:payer:${actor.providerId}:`) || ", "if (!set || ", [C.j06]),
  m("P4-X180", "the holdout is sent to the teacher", FAKE, 'const kept = set.samples.filter((x) => x.split !== "holdout")', "const kept = set.samples", [C.j06]),
  m("P4-X181", "a viewer plans a teacher batch", FAKE, '    this.calls.push(["planTeachers", actor, input]);\n    const refused = this.gate(actor);\n    if (refused) return no(refused);\n', '    this.calls.push(["planTeachers", actor, input]);\n', [C.j06]),
  // the actions
  m("P4-X182", "a dry run acts as the form's provider", ACTIONS, "pipelinesPort().planTeachers(actor(w), {", 'pipelinesPort().planTeachers({ providerId: String(data.get("providerId")), role: w.role }, {', [C.a07]),
  m("P4-X183", "a developer's approval reaches the service", ACTIONS, 'land("/training", w, "manage_members", batchId !== null', 'land("/training", w, "run_evaluation", batchId !== null', [C.a07]),
  m("P4-X184", "any budget string passes", ACTIONS, 'const budgetUsd = field(data, "budgetUsd", USD);', 'const budgetUsd = text(data, "budgetUsd");', [C.a07]),
  m("P4-X185", "another provider's payer or dataset passes", ACTIONS, 'const payerRef = own(data, "payerRef", "payer", w);\n  const budgetUsd', 'const payerRef = text(data, "payerRef");\n  const budgetUsd', [C.a07]),
  m("P4-X186", "a chunk over J1's bound passes", ACTIONS, "chunkSize <= MAX_CHUNK && ", "", [C.a07]),
  m("P4-X187", "the action mints a batch id", ACTIONS, 'const batchId = field(data, "batchId", ID);\n  const datasetRef', 'const batchId = field(data, "batchId", ID) ?? globalThis.crypto.randomUUID();\n  const datasetRef', [C.a07, C.p02]),
  m("P4-X188", "an approval's batch id is not checked", ACTIONS, '"manage_members", batchId !== null,', '"manage_members", true,', [C.a07]),
  m("P4-X189", "the chunk size goes out as text", ACTIONS, "budgetUsd: budgetUsd!, chunkSize,", "budgetUsd: budgetUsd!, chunkSize: chunk as unknown as number,", [C.a07]),
  // the page
  m("P4-X190", "the batch id is typed, not minted at render", TRAIN, '<input type="hidden" name="batchId" value={randomUUID()} />', '<input name="batchId" required />', [C.p05]),
  m("P4-X191", "anyone is offered the approval", TRAIN, "{b.approvable && (\n                    <form action={approveTeachers}>", "{(\n                    <form action={approveTeachers}>", [C.p05]),
  m("P4-X192", "the approval names another batch", TRAIN, '<input type="hidden" name="batchId" value={b.id} />', '<input type="hidden" name="batchId" value={batches.value[0]?.batchId} />', [C.p05]),
  m("P4-X193", "the teacher budget is not labelled USD", TRAIN, "<legend>Teacher budget (USD)</legend>", "<legend>Teacher budget</legend>", [C.p05]),
  m("P4-X194", "the teacher's payer is not asked for", TRAIN, '<label>Payer <input name="payerRef" required placeholder="lab:payer:… (pays the teacher)" /></label>', "", [C.p05]),
  m("P4-X195", "an unwired teacher is not said", TRAIN, '{!batches.ok ? <p role="note">{TEACHER_UNAVAILABLE}</p> :', "{!batches.ok ? null :", [C.p05]),
  m("P4-X196", "the dry-run button claims a send", TRAIN, "Plan a dry run (nothing is sent)", "Send to the teacher", [C.p05]),
  m("P4-X197", "a batch row hides its budget and ceiling", TRAIN, "<td>{b.budget} · {b.ceiling}</td>", "<td>{b.teacher}</td>", [C.p05]),
  // the HTTP adapter
  m("P4-X198", "the teacher listing is another route", HTTP, 'get(actor, "teacher-batches", many(TEACHER))', 'get(actor, "teacher-batch", many(TEACHER))', [C.h06]),
  m("P4-X199", "a dry run goes out in camelCase", HTTP, 'post(actor, "teacher-batches", TEACHER, snake(input))', 'post(actor, "teacher-batches", TEACHER, input)', [C.h06]),
  m("P4-X200", "the approval's batch id is not encoded", HTTP, "`teacher-batches/${encodeURIComponent(id)}/approve`", "`teacher-batches/${id}/approve`", [C.h06]),
  m("P4-X201", "an approval's answer is not checked", HTTP, "/approve`, TEACHER),", "/approve`, () => true),", [C.h06]),
  m("P4-X202", "a dry run's answer is not checked", HTTP, 'post(actor, "teacher-batches", TEACHER, snake(input))', 'post(actor, "teacher-batches", () => true, snake(input))', [C.h06]),
  m("P4-X203", "a batch without within-budget is read", HTTP, "ceilingUsd: nul(str), withinBudget: bool,", "ceilingUsd: nul(str),", [C.h06]),
  m("P4-X204", "a ceiling that is not an exact string is read", HTTP, "priceVersion: nul(str), ceilingUsd: nul(str),", "priceVersion: nul(str), ceilingUsd: () => true,", [C.h06]),
  m("P4-X205", "an approval without its time is read", HTTP, "approval: nul(obj({ approvedBy: str, approvedAt: str })),", "approval: nul(obj({ approvedBy: str })),", [C.h06]),
  m("P4-X206", "a batch without its budget is read", HTTP, "payerRef: str, budgetUsd: str, chunkSize: num,", "payerRef: str, chunkSize: num,", [C.h06]),
  m("P4-X207", "a batch without its payer is read", HTTP, "promptVersion: str, payerRef: str, budgetUsd", "promptVersion: str, budgetUsd", [C.h06]),
  m("P4-X208", "a batch without its not-permitted count is read", HTTP, "holdout: num, notPermitted: num,", "holdout: num,", [C.h06]),
  m("P4-X209", "an unknown chunk state is read", HTTP, "state: among(() => TEACHER_CHUNK_STATES)", "state: str", [C.h06]),
  m("P4-X210", "a chunk without its hold is read", HTTP, "reservedUsd: nul(str), costUsd: nul(str), sent: num,", "costUsd: nul(str), sent: num,", [C.h06]),
  m("P4-X211", "a chunk's failures are not a list", HTTP, "failures: many(obj({ sampleId: str, reason: str })),", "failures: () => true,", [C.h06]),
  m("P4-X212", "a failure without its reason is read", HTTP, "failures: many(obj({ sampleId: str, reason: str }))", "failures: many(obj({ sampleId: str }))", [C.h06]),
  m("P4-X213", "a chunk without its sent count is read", HTTP, "costUsd: nul(str), sent: num,", "costUsd: nul(str),", [C.h06]),
  m("P4-X214", "a chunk's unknown and missing cost read alike", HTTP, "costUsd: nul(str), sent: num", 'costUsd: (v) => v == null || typeof v === "string", sent: num', [C.h06]),
];

process.exit(await runMutants({ suite: SUITE, prefix: "P4", mutants: MUTANTS }));
