#!/usr/bin/env python3
"""r1 R32 for M1's adapter: one single-edit mutant per guard M's tests claim.

Same rule as the contracts list, same verdicts: the mutant is applied to a **copy** of
the package in a temporary directory, the tests that claim the invariant are run there,
and only "pytest failed, and only the named tests failed" counts as a kill. A syntax
error, an import error or a defect with wider reach than the declaration is a broken
runner, which fails the suite exactly as a survivor does. Nothing is written inside the
worktree.

The runner is `tests/contracts/mutants.py`'s (F2R item 9); this file supplies the
target (`tests/m`, not the shared conformance suite) and the list. `Mutant`, `Outcome`
and `Result` are the shared declarations, so a verdict here means what it means there.

    uv run --frozen pytest -q tests/m/test_mutants.py
    uv run --frozen python -m tests.m.mutants --list
"""
from __future__ import annotations

import pathlib
import sys

from ..contracts import mutants as shared
from ..contracts.mutants import Mutant, Outcome, Result, Runner   # noqa: F401

API_DIR = pathlib.Path(__file__).resolve().parents[2]
PACKAGE = "infrx"
SUITE = ("tests/m/test_fetch.py", "tests/m/test_store.py",
         "tests/m/test_probe.py", "tests/m/test_prepare.py",
         "tests/m/test_uploads.py", "tests/m/test_gc.py", "tests/m/test_consent.py",
         "tests/m/test_parity.py", "tests/m/test_upload_restart.py")

F = "media/fetch.py"
S = "media/store.py"
V = "media/video.py"          # F1's address policy, reused by the new path
P = "media/probe.py"          # M2: the container probe
R = "media/prepare.py"        # M2: preparation, the profile and the cache
U = "media/uploads.py"        # M3: owned uploads; M5: over the durable ticket port
G = "media/gc.py"             # M3: collection
C = "media/consent.py"        # M3: consented reuse


# Review B1: the open set taken before the listing (the pre-fix order), as one block edit.
_B1_FIXED = "        listed = await store.objects.keys(UPLOAD_KEY_PREFIX)\n        # M5: this reads a process-local ticket authority's records. A durable one keeps\n        # none in process (`store.uploads` raises), so the pass stops here, before any\n        # delete: its destinations are M6's to sweep over the durable content rows.\n        uploads = store.uploads\n        swept.uploads_expired = await store.tickets.expire(max(1, len(uploads)))\n        open_destinations = set()\n        for handle, upload in list(uploads.items()):\n            if upload.state is UploadState.created:\n                open_destinations.add(store.upload_key(upload.org_id, handle))\n            elif upload.state is not UploadState.finalized and now >= upload.expires_at + self.grace:\n                del uploads[handle]            # a refused record is not kept forever\n        for key in listed:\n"
_B1_STALE = "        # M5: this reads a process-local ticket authority's records. A durable one keeps\n        # none in process (`store.uploads` raises), so the pass stops here, before any\n        # delete: its destinations are M6's to sweep over the durable content rows.\n        uploads = store.uploads\n        swept.uploads_expired = await store.tickets.expire(max(1, len(uploads)))\n        open_destinations = set()\n        for handle, upload in list(uploads.items()):\n            if upload.state is UploadState.created:\n                open_destinations.add(store.upload_key(upload.org_id, handle))\n            elif upload.state is not UploadState.finalized and now >= upload.expires_at + self.grace:\n                del uploads[handle]            # a refused record is not kept forever\n        for key in await store.objects.keys(UPLOAD_KEY_PREFIX):\n"


def _m(name, invariant, file, old, new, *cases, dies_by=(), occurrences=1) -> Mutant:
    return Mutant(name=name, invariant=invariant, file=file, old=old, new=new, cases=cases,
                  dies_by=tuple(dies_by), occurrences=occurrences)


# Five mutants declare a kill mode (F2R item 9): two let a forged organization reach the
# record constructor (`ValidationError` is the refusal, one layer late), two are timeouts
# that must be impossible (the real-clock backstop, the transport translation), and one
# reads a stored payload the mutant never stored. An exception from the mutant text is
# still a broken copy, which the self-tests below prove.
MUTANTS: tuple[Mutant, ...] = (
    # --- the address policy ---------------------------------------------------
    # Review B1 (r2 correction): every check in `address_allowed` is load bearing, and the
    # round-2 claim that `is_reserved` "changes no answer" was wrong - IPv4-compatible forms
    # (`::127.0.0.1`, `::a9fe:a9fe`) are global and not private on every build, and reserved
    # space outside `::/96` (`4000::1`) is refused by `is_reserved` alone. The policy states
    # the tunnel, IPv4-compatible and special-purpose ranges itself so it does not depend on
    # the interpreter's tables either way. `::/96` in `DENIED_NETWORKS` has no mutant for
    # that reason: it is the same refusal `is_reserved` already gives *on this build*, and it
    # is stated so the policy still holds on one where `::/8` is not reserved.
    _m("reserved_addresses_allowed",
       "reserved space is refused (IPv4-compatible forms and 4000::/3 are caught by it alone)",
       V, "or a.is_reserved or a.is_unspecified", "or a.is_unspecified",
       "test_the_address_policy_does_not_depend_on_the_interpreters_tables",
       "test_no_internal_address_form_is_reachable"),
    _m("multicast_allowed", "multicast is refused (224.0.0.1, ff02::1: nothing to fetch there)",
       V, "or a.is_multicast or a.is_reserved", "or a.is_reserved",
       "test_the_address_policy_does_not_depend_on_the_interpreters_tables",
       "test_no_internal_address_form_is_reachable"),
    _m("site_local_allowed", "deprecated site-local fec0::/10 is refused (is_global says True)",
       V, "    if a.version == 6 and a.is_site_local:\n        return False", "    pass",
       "test_the_address_policy_does_not_depend_on_the_interpreters_tables",
       "test_no_internal_address_form_is_reachable"),
    _m("denied_networks_not_checked",
       "the explicit deny-list is checked (6to4 relay anycast, RFC 9637 documentation)",
       V, "    if any(a in net for net in DENIED_NETWORKS if net.version == a.version):\n"
          "        return False", "    pass",
       "test_the_address_policy_does_not_depend_on_the_interpreters_tables",
       "test_no_internal_address_form_is_reachable"),
    _m("mapped_address_not_unwrapped", "a v4-mapped address is judged as the v4 it names",
       V, "    if a.version == 6 and a.ipv4_mapped:\n        a = a.ipv4_mapped", "    pass",
       "test_a_v4_mapped_public_address_is_judged_as_the_v4_it_names",
       "test_the_address_policy_does_not_depend_on_the_interpreters_tables"),
    _m("cgnat_allowed", "only globally routable space is allowed (so not CGNAT)",
       V, "    return a.is_global", "    return True",
       "test_no_internal_address_form_is_reachable"),
    _m("unparseable_address_allowed", "text that is not an address is not a destination",
       V, "    except ValueError:\n        return False", "    except ValueError:\n        return True",
       "test_no_internal_address_form_is_reachable"),

    # --- resolution and pinning -----------------------------------------------
    _m("one_answer_is_enough", "every answer for a name must be public (rebinding)",
       F, "if not all(address_allowed(address) for address in addresses):",
       "if not any(address_allowed(address) for address in addresses):",
       "test_one_private_answer_among_many_is_refused",
       "test_a_rebinding_resolver_cannot_reach_an_internal_address"),
    _m("empty_answer_accepted", "an empty DNS answer is a refusal, not an empty pin",
       F, "        if not addresses:\n            raise refused(\"dns\", host=host)", "        pass",
       "test_a_dns_failure_or_an_empty_answer_is_a_refusal_not_a_crash"),
    _m("resolution_failure_swallowed", "a resolver error is a typed refusal",
       F, "            raise refused(\"dns\", host=host) from None", "            return [host]",
       "test_a_dns_failure_or_an_empty_answer_is_a_refusal_not_a_crash"),
    _m("connects_to_the_name_not_the_address",
       "the connection goes to the validated address, not to the name again",
       F, "\"GET\", target.copy_with(host=address),", "\"GET\", target,",
       "test_the_connection_is_pinned_to_the_validated_address",
       "test_an_ipv6_answer_is_pinned_as_a_bracketed_literal"),
    _m("no_sni_for_the_original_host",
       "TLS still verifies the certificate against the host the caller named",
       F, "extensions={\"sni_hostname\": host, \"timeout\": self._budget(remaining)}",
       "extensions={\"timeout\": self._budget(remaining)}",
       "test_the_connection_is_pinned_to_the_validated_address"),
    _m("host_header_from_the_pinned_url", "the origin still sees the host it was asked for",
       F, "headers={\"Host\": target.netloc.decode(\"ascii\"),",
       "headers={\"X-Original-Host\": target.netloc.decode(\"ascii\"),",
       "test_the_connection_is_pinned_to_the_validated_address"),
    _m("httpx_follows_redirects_itself",
       "no unpinned hop: httpx following a redirect resolves the name again",
       F, "            follow_redirects=False,", "            follow_redirects=True,",
       "test_the_client_follows_nothing_and_trusts_no_environment"),
    _m("proxy_environment_trusted", "no proxy from the environment may replace the pin",
       F, "            trust_env=False,", "            trust_env=True,",
       "test_the_client_follows_nothing_and_trusts_no_environment"),
    _m("the_connect_budget_is_the_whole_budget", "connect and total budgets are separate",
       F, "connect=self.limits.media_fetch_connect_timeout_s)",
       "connect=self.limits.media_fetch_timeout_s)",
       "test_the_client_follows_nothing_and_trusts_no_environment"),

    _m("transport_logs_not_silenced",
       "httpx and httpcore never write a request line (the pinned IP and the query)",
       F, "silence_transport_logs()\n\nALLOWED_MIME", "ALLOWED_MIME",
       "test_no_logger_in_the_process_writes_a_url_an_ip_or_a_location"),
    _m("budget_not_recomputed_after_dns",
       "resolution spends the budget: the request carries what is left after it (review r2)",
       F, "                remaining = expires_at - self.monotonic()\n"
          "                if remaining <= 0:\n"
          "                    raise refused(\"timeout\", host=host)\n"
          "                # No Set-Cookie from one hop reaches the next",
       "                # No Set-Cookie from one hop reaches the next",
       "test_the_budget_is_recomputed_after_the_name_is_resolved"),
    _m("secure_decided_at_the_first_hop",
       "a chain that became confidential stays confidential (review r2)",
       F, "                secure = secure or target.scheme == \"https\"",
       "                secure = target.scheme == \"https\" if hop == 0 else secure",
       "test_a_chain_that_became_confidential_stays_confidential"),
    _m("connect_budget_not_capped",
       "connecting gets the remainder when less is left than the connect budget",
       F, "        connect = min(self.limits.media_fetch_connect_timeout_s, remaining)",
       "        connect = self.limits.media_fetch_connect_timeout_s",
       "test_each_request_carries_what_is_left_of_the_budget"),
    _m("fetch_ignores_the_configured_allow_list",
       "the allow-list the fetcher was given is the one the response is checked against",
       F, "                    mime = video_mime(response.headers.get(\"content-type\"), target,\n"
          "                                      self.allowed_mime)",
       "                    mime = video_mime(response.headers.get(\"content-type\"), target)",
       "test_the_allow_list_the_fetcher_was_given_is_the_one_that_is_used"),
    _m("data_urls_ignore_the_configured_allow_list",
       "the same allow-list decides a data: URL",
       S, "                decode_data_url, source, self.limits, self.fetcher.allowed_mime), MediaKind.inline",
       "                decode_data_url, source, self.limits), MediaKind.inline",
       "test_the_allow_list_the_fetcher_was_given_is_the_one_that_is_used"),
    _m("hop_deadline_not_checked",
       "the budget is checked at the start of every hop, before resolving or connecting",
       F, "                if remaining <= 0:\n                    raise refused(\"timeout\", host=host)",
       "                pass", "test_a_slow_redirect_chain_stops_at_the_aggregate_deadline", occurrences=2),
    _m("request_budget_is_the_whole_budget",
       "each request carries what is left of the aggregate budget, not all of it",
       F, "        connect = min(self.limits.media_fetch_connect_timeout_s, remaining)\n"
          "        return {\"connect\": connect, \"read\": remaining, \"write\": remaining, \"pool\": remaining}",
       "        whole = self.limits.media_fetch_timeout_s\n"
       "        return {\"connect\": self.limits.media_fetch_connect_timeout_s, \"read\": whole,\n"
       "                \"write\": whole, \"pool\": whole}",
       "test_each_request_carries_what_is_left_of_the_budget"),
    _m("resolution_not_bounded", "resolution happens inside the remaining budget",
       F, "            addresses = await asyncio.wait_for(self.resolve(host), max(remaining, 0.001))",
       "            addresses = await self.resolve(host)",
       "test_a_resolver_that_never_answers_is_bounded"),
    _m("no_real_clock_backstop",
       "the aggregate limit also holds on the real clock, for a phase the fetcher cannot see",
       F, "            async with asyncio.timeout(self.limits.media_fetch_timeout_s + BACKSTOP_GRACE_S):\n"
          "                return await self._fetch(url, early)",
       "            return await self._fetch(url, early)",
       "test_a_body_that_stalls_for_ever_is_bounded_by_the_backstop", dies_by=("TimeoutError",)),
    _m("asks_for_compression", "the request asks for no content coding",
       F, "\"Accept-Encoding\": \"identity\"", "\"Accept-Encoding\": \"gzip, br\"",
       "test_a_compressed_body_is_refused_outright"),
    _m("a_redirect_may_downgrade", "an https fetch never continues in plaintext",
       F, "                if hop and secure and target.scheme != \"https\":",
       "                if False:",
       "test_a_redirect_may_not_downgrade_to_plaintext",
       "test_a_chain_that_became_confidential_stays_confidential"),
    _m("cookies_carried_between_hops", "no cookie from one hop reaches the next",
       F, "                client.cookies.clear()", "                pass",
       "test_a_redirect_carries_no_cookie_from_the_hop_before"),
    _m("decoded_host_used_instead_of_the_wire_form",
       "one spelling of the host for the resolver, SNI and Host (IDNA2003 vs 2008)",
       F, "    return url.raw_host.decode(\"ascii\")", "    return url.host",
       "test_the_resolver_and_the_wire_agree_on_one_spelling_of_the_host"),

    # --- the URL and its hops -------------------------------------------------
    _m("any_scheme_fetched", "only http(s) URLs are fetched",
       F, "    if target.scheme not in (\"http\", \"https\"):", "    if False:",
       "test_only_http_urls_with_a_host_are_fetched",
       "test_a_redirect_to_another_scheme_or_to_credentials_is_refused"),
    _m("credentials_in_the_url_accepted", "a URL carrying credentials is refused",
       F, "        raise refused(\"credentials-in-url\", host=raw_host_of(target))", "        pass",
       "test_credentials_in_the_url_are_refused"),
    _m("hostless_url_accepted", "a URL with no host has no destination to validate",
       F, "    if not target.raw_host:\n        raise refused(\"no-host\")", "    pass",
       "test_only_http_urls_with_a_host_are_fetched"),
    _m("later_hops_unvalidated", "every hop is validated, not only the first",
       F, "                target = parse_source(url)\n                host = raw_host_of(target)",
       "                target = parse_source(url) if hop == 0 else httpx.URL(url)\n"
       "                host = raw_host_of(target)",
       "test_a_redirect_to_another_scheme_or_to_credentials_is_refused"),
    _m("later_hops_unresolved", "every hop is resolved and re-pinned",
       F, "                address = await self._pin(host, remaining)",
       "                address = await self._pin(host, remaining) if hop == 0 else host",
       "test_every_redirect_hop_is_validated_and_repinned",
       "test_a_rebinding_resolver_cannot_reach_an_internal_address"),
    _m("redirect_budget_ignored", "the redirect budget is MEDIA_FETCH_MAX_REDIRECTS",
       F, "            for hop in range(limits.media_fetch_max_redirects + 1):",
       "            for hop in range(100):",
       "test_a_redirect_chain_over_the_budget_is_refused"),
    _m("a_redirect_without_a_destination_is_content",
       "a 3xx with no Location is refused, not read as a body",
       F, "                        if not location:\n"
          "                            raise refused(\"bad-redirect\", host=host)",
       "                        if not location:\n                            location = \"/\"",
       "test_a_redirect_without_a_location_is_refused"),

    # --- what came back -------------------------------------------------------
    _m("any_status_is_content", "only 200 carries the media",
       F, "                    if response.status_code != 200:", "                    if False:",
       "test_a_non_200_response_is_refused_without_its_body"),
    _m("content_coding_accepted", "a compressed body is refused (the gzip bomb)",
       F, "                    if coding not in (\"\", \"identity\"):", "                    if False:",
       "test_a_compressed_body_is_refused_outright"),
    _m("any_type_is_a_video", "the response type is on an allow-list",
       F, "                    if mime is None:\n"
          "                        raise refused(\"unsupported-type\", host=host,\n"
          "                                      exc=errors.UnsupportedMedia)",
       "                    mime = mime or \"video/mp4\"",
       "test_a_non_video_response_is_refused",
       "test_an_undeclared_type_falls_back_to_the_extension_only"),
    _m("declared_length_ignored", "a declared oversize body is refused before it is read",
       F, "                    if declared.isdigit() and int(declared) > cap:", "                    if False:",
       "test_a_declared_oversize_body_is_refused_before_it_is_read"),
    _m("streaming_cap_removed", "the byte cap is enforced while the body streams",
       F, "                        if len(body) > cap:", "                        if False:",
       "test_an_oversize_body_is_aborted_mid_stream"),
    _m("aggregate_deadline_not_checked_between_chunks",
       "the aggregate time limit stops a slow body",
       F, "                        if self.monotonic() >= expires_at:\n"
          "                            raise refused(\"timeout\", host=host)\n"
          "                    if not body:",
       "                    if not body:",
       "test_a_slow_body_stops_at_the_aggregate_deadline"),
    _m("an_empty_body_is_a_video", "an empty body is not media",
       F, "                    if not body:\n"
          "                        raise refused(\"empty-body\", host=host)", "                    pass",
       "test_an_empty_body_is_not_a_video"),
    _m("upstream_text_echoed", "no upstream exception text reaches the caller or the log",
       F, "            self.log.warning(\"media fetch failed: type=%s\", type(exc).__name__)\n"
          "            raise refused(\"fetch-failed\") from None",
       "            self.log.warning(\"media fetch failed: %s\", exc)\n"
       "            raise refused(\"fetch-failed\") from exc",
       "test_a_refusal_tells_the_caller_and_the_log_nothing_about_the_url"),
    _m("a_timeout_is_an_unknown_failure", "a transport timeout is reported as a timeout",
       F, "        except (TimeoutError, httpx.TimeoutException):\n"
          "            self.log.warning(\"media fetch refused: reason=%s\", \"timeout\")\n"
          "            raise refused(\"timeout\") from None",
       "        except (TimeoutError, httpx.TimeoutException):\n            raise",
       "test_a_transport_timeout_is_a_timeout_refusal", dies_by=("ReadTimeout",)),

    # --- data: URLs -----------------------------------------------------------
    _m("base64_not_validated", "strict base64: no whitespace or stray characters",
       F, "        data = binascii.a2b_base64(payload, strict_mode=True)",
       "        data = binascii.a2b_base64(payload + \"===\", strict_mode=False)",
       "test_a_data_url_is_decoded_strictly_and_within_a_bound"),
    _m("data_url_bound_after_decode", "the bound is applied before anything is decoded",
       F, "    if len(payload) > (cap + 2) // 3 * 4:\n"
          "        raise refused(\"too-large\", exc=errors.RequestTooLarge)", "    pass",
       "test_an_oversize_data_url_is_refused_before_it_is_decoded"),
    _m("any_data_url_type_accepted", "a data: URL's type is on the same allow-list",
       F, "    if mime not in allowed:\n"
          "        raise refused(\"unsupported-type\", exc=errors.UnsupportedMedia)", "    pass",
       "test_a_data_url_must_be_base64_and_an_allowed_video_type"),
    _m("a_plain_data_url_is_decoded_as_base64", "only base64 is a bounded encoding",
       F, "    if \"base64\" not in parameters[1:]:\n        raise refused(\"bad-data-url\")",
       "    pass", "test_a_data_url_must_be_base64_and_an_allowed_video_type"),

    # --- staging --------------------------------------------------------------
    _m("stage_accepts_another_orgs_request", "a request is staged only for its own org",
       S, "            raise errors.Forbidden(\"a request may only be staged for its own org\")",
       "            pass", "test_a_request_may_only_be_staged_for_its_own_org"),
    _m("stage_accepts_a_foreign_reference", "a body cannot name another tenant's object",
       S, "            existing = self.refs.get((org_id, ref.handle))",
       "            existing = next((value for (_o, handle), value in self.refs.items()\n"
       "                             if handle == ref.handle), None)",
       "test_a_foreign_or_oversize_reference_is_not_staged",
       "test_stage_takes_only_refs_this_store_materialized"),
    _m("stage_ignores_the_byte_cap", "a source over MAX_MEDIA_BYTES is refused",
       S, "            if ref.bytes > self.limits.max_media_bytes:", "            if False:",
       "test_a_foreign_or_oversize_reference_is_not_staged"),
    _m("stage_trusts_an_upload_handle", "an upload reference is resolved, not trusted",
       S, "                owned = await self.resolve_owned(org_id, ref.handle)\n"
          "                if owned.digest != ref.digest:",
       "                owned = ref\n                if False:",
       "test_an_upload_reference_is_resolved_not_trusted"),
    _m("stage_returns_the_callers_ref",
       "an owned object is staged as the store has it, not as the request describes it",
       S, "            resolved.append(existing)\n", "            resolved.append(ref)\n",
       "test_a_known_handle_is_staged_as_the_object_the_store_has"),
    _m("materialize_indexes_before_the_write",
       "no ref is indexed without an object behind it",
       S, "        await self._write_once(ref.storage_ref, fetched.data, ref.mime)\n"
          "        self.refs[(org_id, ref.handle)] = ref",
       "        self.refs[(org_id, ref.handle)] = ref\n"
       "        await self._write_once(ref.storage_ref, fetched.data, ref.mime)",
       "test_no_ref_is_indexed_without_an_object_behind_it"),
    _m("handle_clash_ignored", "a handle never comes to name different content",
       S, "            raise errors.Conflict(f\"handle {ref.handle} already names different content\")",
       "            pass", "test_a_handle_that_already_names_other_content_is_a_conflict"),
    _m("digest_taken_from_the_fetcher", "the stored object's digest is measured here",
       S, "        digest = await asyncio.to_thread(digest_of, fetched.data)",
       "        digest = fetched.digest",
       "test_the_digest_is_measured_not_taken_from_the_fetcher"),
    # F2R item 4: `stage` no longer indexes a caller's ref, so the three mutants of the
    # code that did (replace-on-conflict, last-of-two-handles, index-as-it-goes) went with
    # it; this is the one rule left, and it is the one they were approximating.
    _m("stage_takes_a_ref_it_never_made", "only a ref this store materialized is staged",
       S, "            if existing is None or existing.digest != ref.digest:",
       "            if False:",
       "test_stage_takes_only_refs_this_store_materialized"),
    _m("payload_key_from_the_request", "the caller never names the payload's path",
       S, "        key = f\"payloads/{valid_org(org_id)}/{request.request_id}.json\"",
       "        key = request.payload_ref",
       "test_staging_makes_the_canonical_payload_durable_with_a_digest_and_a_size"),
    _m("payload_not_stored", "the canonical payload is durable before acceptance",
       S, "        await self._write_once(key, payload, \"application/json\")", "        pass",
       "test_staging_makes_the_canonical_payload_durable_with_a_digest_and_a_size", dies_by=("KeyError",)),
    _m("payload_size_from_the_reference", "the durable payload's digest and size are measured",
       S, "        self.payloads[request.request_id] = StagedPayload(ref=key, digest=digest_of(payload),\n"
          "                                                          bytes=len(payload))",
       "        self.payloads[request.request_id] = StagedPayload(ref=key,\n"
       "                                                          digest=request.payload_digest,\n"
       "                                                          bytes=0)",
       "test_staging_makes_the_canonical_payload_durable_with_a_digest_and_a_size"),
    _m("an_object_can_be_replaced", "content already at a key is immutable",
       S, "        if await self.objects.head(key) != digest_of(data):\n"
          "            raise errors.Conflict(f\"an object already exists at {key} with different content\")",
       "        pass",
       "test_an_object_is_never_replaced_by_different_content",
       "test_a_second_payload_for_one_request_id_cannot_replace_the_first"),

    # --- keys, materialization and attach -------------------------------------
    _m("key_without_the_tenant", "two orgs never share an object",
       S, "        return (f\"media/{valid_org(org_id)}/{valid_profile(profile_version)}\"",
       "        return (f\"media/{valid_profile(profile_version)}\"",
       "test_two_organizations_never_share_an_object"),
    _m("key_without_the_profile_version",
       "the profile version namespaces the cache key (01)",
       S, "        return (f\"media/{valid_org(org_id)}/{valid_profile(profile_version)}\"",
       "        return (f\"media/{valid_org(org_id)}\"",
       "test_a_fetched_source_becomes_a_tenant_scoped_content_addressed_object"),
    _m("profile_version_unvalidated",
       "a profile version is an identifier, not a path (cross-track hazard)",
       S, "    if not isinstance(version, str) or not PROFILE_VERSION_RE.fullmatch(version):",
       "    if False:", "test_a_profile_version_cannot_escape_the_tenants_prefix"),
    _m("profile_version_may_start_with_a_dot",
       "a profile version starts with an alphanumeric, so `..` is not one (B-R2-1.4)",
       S, 'PROFILE_VERSION_RE = re.compile(r"^[a-z0-9][a-z0-9._-]{0,63}$")',
       'PROFILE_VERSION_RE = re.compile(r"^[a-z0-9.][a-z0-9._-]{0,63}$")',
       "test_a_profile_version_cannot_escape_the_tenants_prefix"),
    _m("digest_unvalidated_in_the_key",
       "the digest a key is built from is validated where the key is built (review r2)",
       S, "                f\"/{valid_digest(digest)}/{part}\")",
       "                f\"/{digest.split(':')[1][:16]}/{part}\")",
       "test_a_digest_cannot_carry_a_path_into_a_key"),
    _m("org_unvalidated", "the tenant every key is namespaced by is validated first",
       S, "    if not isinstance(org_id, str) or not UUID_RE.fullmatch(org_id):",
       "    if False:", "test_a_malformed_tenant_is_refused_before_anything_is_fetched", dies_by=("ValidationError",)),
    _m("org_matched_as_a_prefix",
       "the tenant is the whole string, not a UUID with something after it (B-R2-1.5)",
       S, "    if not isinstance(org_id, str) or not UUID_RE.fullmatch(org_id):",
       "    if not isinstance(org_id, str) or not UUID_RE.match(org_id):",
       "test_a_malformed_tenant_is_refused_before_anything_is_fetched", dies_by=("ValidationError",)),
    _m("any_source_materialized", "a media source is an http(s) or data: URL",
       S, "            raise errors.InvalidRequest(\"a media source must be an http(s) or data: URL\")",
       "            fetched, kind = await self.fetcher.fetch(source), MediaKind.url",
       "test_an_unsupported_source_is_refused_before_anything_is_stored"),
    _m("materialized_bytes_unbounded",
       "a materialized source is bounded whatever the fetcher returned",
       S, "        if len(fetched.data) > self.limits.max_media_bytes:", "        if False:",
       "test_an_oversize_source_never_reaches_the_object_store"),
    _m("attach_trusts_the_refs_tenant", "every attached ref belongs to the job's org (R52)",
       S, "                raise errors.NotFound(\"media attached to a job must belong to its org\")",
       "                pass", "test_attach_takes_the_tenant_from_the_job_row"),
    _m("attach_without_a_job_row", "the org comes from the job row, and there must be one",
       S, "        org_id = self.job_org(job_id)\n        owned: list[MediaRef] = []",
       "        org_id = refs[0].org_id if refs else None\n        owned: list[MediaRef] = []",
       "test_attach_takes_the_tenant_from_the_job_row"),
    _m("attach_lookup_is_not_tenant_scoped",
       "the ref a job gets is looked up in the job's own org (B-R2-1.3)",
       S, "        indexed = self.refs.get((org_id, ref.handle))",
       "        indexed = next((m for (_o, h), m in self.refs.items() if h == ref.handle),\n"
       "                       None)",
       "test_the_attach_lookup_is_inside_the_jobs_tenant"),
    _m("attach_accepts_an_unstaged_ref",
       "a job executes only on media this store staged, as the store described it",
       S, "        return indexed if indexed is not None and indexed.digest == ref.digest else None",
       "        return ref",
       "test_only_a_staged_ref_can_be_attached_to_a_job",
       "test_a_known_handle_is_staged_as_the_object_the_store_has"),
    _m("resolve_ignores_the_tenant", "a handle is resolved inside its own tenant only",
       S, "        media = self.refs.get((org_id, ref))",
       "        media = next((m for (_o, h), m in self.refs.items() if h == ref), None)",
       "test_two_organizations_never_share_an_object"),
    # ======================================================================
    # M2: the container probe (`media/probe.py`)
    #
    # Two guards here deliberately have **no** mutant, for the reason M1 gave for `::/96`:
    # every single-edit version of them either produces the same refusal by another route or
    # makes the walk stop advancing, i.e. hang. They are the lower half of the ISO box-length
    # check (`size < body - at`, a termination guard, proved by the bounded-time assertion in
    # `test_a_hostile_length_is_refused_not_followed`) and the EBML `first == 0` width check
    # (a width of nine is refused by the truncation guard on any file short enough to matter).
    # `ProcessingCache.path_for`'s cache-root check is the third of the same kind: see
    # `cache_root_check_rejects_valid_paths` for what is and is not claimed about it.
    # ----------------------------------------------------------------------
    _m("box_length_not_compared_with_the_file",
       "a box may not claim more bytes than the file has (the content being there is not the "
       "same as the length being right)",
       P, "        if size < body - at or at + size > end:", "        if size < body - at:",
       "test_a_box_longer_than_the_file_is_refused_although_its_content_is_there"),
    _m("extended_64_bit_length_ignored",
       "`size == 1` is a 64-bit length; reading the literal 1 walks into the header",
       P, "        if size == 1:\n            size = _u(data, body, 8)\n            body += 8",
       "        if False:\n            size = _u(data, body, 8)\n            body += 8",
       "test_a_64_bit_box_length_is_read"),
    _m("to_end_of_file_length_ignored",
       "`size == 0` is \"to the end of the file\"; an empty box instead parses the payload "
       "after it as boxes",
       P, "        elif size == 0:\n            size = end - at",
       "        elif size == 0:\n            size = BOX_HEADER",
       "test_a_box_that_runs_to_the_end_of_the_file_is_read"),
    _m("second_movie_header_ignored",
       "two movie headers stating the duration is refused, not resolved first-wins - the "
       "second copy is then a free rewrite of the number the frame budget uses (review R20)",
       P, '            if kind == "mvhd":\n                if seen_movie_header:',
       '            if kind == "mvhd":\n                if False:',
       "test_a_duplicate_duration_header_is_refused"),
    _m("second_matroska_duration_ignored",
       "likewise for a second Duration inside one Info",
       P, "            elif element == DURATION:\n                if duration:",
       "            elif element == DURATION:\n                if False:",
       "test_a_duplicate_duration_header_is_refused"),
    _m("mvhd_version_1_offsets",
       "version 1 of the movie header has 64-bit times, so the timescale and duration move",
       P, "    if version == 1:\n        return _u(data, start + 20, 4), _u(data, start + 24, 8)",
       "    if version == 1:\n        return _u(data, start + 12, 4), _u(data, start + 16, 4)",
       "test_the_probe_reads_the_container_the_bytes_describe"),
    _m("mvhd_version_unchecked",
       "an undefined movie-header version is refused, not read as version 0",
       P, '    raise _refuse("mvhd-version")',
       "    return _u(data, start + 12, 4), _u(data, start + 16, 4)",
       "test_a_container_that_states_no_usable_duration_is_refused"),
    _m("tkhd_version_1_offsets",
       "version 1 of the track header moves the geometry by twelve bytes",
       P, "    at = start + (88 if version == 1 else 76)", "    at = start + 76",
       "test_the_probe_reads_the_container_the_bytes_describe"),
    _m("tkhd_fixed_point_not_converted",
       "a track header stores 16.16 fixed point, so 640 is 0x02800000",
       P, "    return _u(data, at, 4) >> 16, _u(data, at + 4, 4) >> 16",
       "    return _u(data, at, 4), _u(data, at + 4, 4)",
       "test_the_probe_reads_the_container_the_bytes_describe"),
    _m("zero_timescale_not_refused",
       "a zero timescale is refused (declared: without it the kill is an unhandled "
       "ZeroDivisionError in the named case, not a typed refusal)",
       P, "    if not timescale or not duration:", "    if not duration:",
       "test_a_container_that_states_no_usable_duration_is_refused",
       dies_by=("ZeroDivisionError",)),
    _m("video_track_read_by_position",
       "the video track is the one whose sample entry is a video codec, not track 1",
       P, "    video = next((t for t in tracks if t.get(\"format\") in MP4_CODECS), None)",
       "    video = tracks[0] if tracks else None",
       "test_the_video_track_is_chosen_by_its_codec_not_its_position", dies_by=("KeyError",)),
    _m("mp4_codec_allowlist_widened",
       "the MP4 codec table is the serving pin: ProRes, MPEG-4 part 2 and a JPEG track are "
       "refused whether or not a decoder would open them",
       P, '"av01": "av1", "vp08": "vp8", "vp09": "vp9"}',
       '"av01": "av1", "vp08": "vp8", "vp09": "vp9", "apcn": "prores", "mp4v": "mpeg4",\n'
       '              "jpeg": "jpeg"}',
       "test_a_container_with_no_servable_video_track_is_refused"),
    _m("quicktime_brand_ignored",
       "a `qt  ` major brand is QuickTime, which is a different accepted type and a "
       "different cache extension",
       P, "    return Probed(mime=QUICKTIME_MIME if brand.startswith(b\"qt\") else MP4_MIME,",
       "    return Probed(mime=MP4_MIME,",
       "test_the_probe_reads_the_container_the_bytes_describe"),
    _m("iso_element_budget_removed",
       "the walk stops after MAX_ELEMENTS headers, so a few kilobytes of empty boxes cannot "
       "cost seconds of CPU",
       P, '            if walked > MAX_ELEMENTS:\n                raise _refuse("too-many-boxes")',
       '            if walked > MAX_ELEMENTS * 1000:\n                raise _refuse("too-many-boxes")',
       "test_many_empty_boxes_stop_at_the_element_budget"),
    _m("iso_depth_limit_removed",
       "nesting is bounded, so caller-controlled depth is not a stack",
       P, '            elif kind in ("moov", "trak", "mdia", "minf", "stbl"):\n'
          "                if depth >= MAX_DEPTH:",
       '            elif kind in ("moov", "trak", "mdia", "minf", "stbl"):\n'
          "                if False:",
       "test_a_deeply_nested_container_stops_at_the_depth_limit"),
    _m("ebml_unknown_size_accepted_anywhere",
       "an unknown size is legal on a streamed Segment only; anywhere else it lets the rest "
       "of the file be read as that element's children",
       P, '            if unknown:\n                if element != SEGMENT:\n'
          '                    raise _refuse("unknown-size")\n                size = end - body',
       "            if unknown:\n                size = end - body",
       "test_a_hostile_length_is_refused_not_followed"),
    _m("ebml_element_length_unchecked",
       "an EBML element may not claim more bytes than its parent has",
       P, "            if size < 0 or body + size > end:", "            if size < 0:",
       "test_a_hostile_length_is_refused_not_followed"),
    _m("ebml_uint_width_unchecked",
       "an EBML unsigned integer is at most eight bytes wide: wider ones were accepted as "
       "absurd values, overflowed the arithmetic, or broke the refusal's own formatting - a "
       "500 where the contract says unsupported_media (review B1)",
       P, "    if size > 8:\n        raise _refuse(\"bad-uint\")", "    pass",
       "test_a_hostile_length_is_refused_not_followed", dies_by=("OverflowError", "ValueError")),
    _m("timecode_scale_assumed_default",
       "a Matroska duration is in timecode-scale units, and the scale is in the file",
       P, "                scale = _ebml_uint(data, body, size) or DEFAULT_TIMECODE_SCALE",
       "                scale = DEFAULT_TIMECODE_SCALE",
       "test_the_probe_reads_the_container_the_bytes_describe"),
    _m("matroska_codec_allowlist_widened",
       "the Matroska codec table is the same serving pin: Theora is refused",
       P, '"V_AV1": "av1", "V_VP8": "vp8", "V_VP9": "vp9"}',
       '"V_AV1": "av1", "V_VP8": "vp8", "V_VP9": "vp9",\n                     '
       '"V_THEORA": "theora"}',
       "test_a_container_with_no_servable_video_track_is_refused"),
    _m("matroska_track_type_ignored",
       "the track type is what says there are frames: a video codec on an audio track is "
       "not a video",
       P, '    video = next((t for t in tracks\n                  if t["type"] == VIDEO_TRACK_TYPE '
          'and t["codec"] in MATROSKA_CODECS), None)',
       '    video = next((t for t in tracks\n                  if t["codec"] in MATROSKA_CODECS), None)',
       "test_a_container_with_no_servable_video_track_is_refused"),
    _m("frame_size_unchecked",
       "0x0 and 65535x65535 are declarations, not frames: the cheapest decode bombs there are",
       P, "    if not 0 < probed.width <= MAX_DIMENSION or not 0 < probed.height <= MAX_DIMENSION:\n"
          '        raise _refuse(f"dimensions:{probed.width}x{probed.height}")',
       "    pass",
       "test_a_frame_size_that_is_a_declaration_is_refused"),
    _m("non_finite_duration_allowed_out",
       "`inf`, `nan` and a negative duration never leave the probe (the engine computes a "
       "frame budget from this number)",
       P, '    if not (0 < probed.duration_s < float("inf")):\n'
          '        raise _refuse(f"duration:{probed.duration_s}")',
       "    pass",
       "test_a_non_finite_duration_never_leaves_the_probe",
       "test_a_container_that_states_no_usable_duration_is_refused"),

    # ======================================================================
    # M2: preparation, the profile table and the processing cache (`media/prepare.py`)
    # ----------------------------------------------------------------------
    _m("no_probe_at_materialization",
       "the ref's duration and type are measured from the bytes; without the probe the "
       "engine refuses every video request (S2M D2)",
       R, "        probed = await self.probed(data)\n        self.profile.check(probed, len(data))\n"
          "        return probed.mime, probed.duration_s",
       "        return mime, None",
       "test_preparation_measures_the_clip_and_fills_the_record",
       "test_what_preparation_produces_is_what_the_engine_adapter_accepts"),
    _m("declared_type_kept_over_the_container",
       "the sniffed container wins over the `Content-Type`, because the extension the engine "
       "opens and the object's content type must match its bytes",
       R, "        return probed.mime, probed.duration_s", "        return mime, probed.duration_s",
       "test_the_container_wins_over_the_declared_type"),
    _m("profile_not_checked_before_the_write",
       "media the profile refuses is never stored: the check runs on the measurement, before "
       "the object exists",
       R, "        self.profile.check(probed, len(data))\n        return probed.mime",
       "        return probed.mime",
       "test_a_clip_over_the_duration_cap_is_refused_before_it_is_stored",
       "test_media_the_profile_refuses_is_never_stored"),
    _m("duration_cap_removed",
       "MAX_VIDEO_SECONDS is what keeps an accepted clip at the trained 2 fps (S2M D9)",
       R, "        if probed.duration_s > self.max_duration_s:", "        if False:",
       "test_a_clip_over_the_duration_cap_is_refused_before_it_is_stored",
       "test_a_tightened_profile_refuses_media_the_probe_can_read",
       "test_a_media_first_clip_over_the_cap_is_refused_once_it_has_arrived"),
    _m("profile_codec_allowlist_removed",
       "the profile's codec set is the pin, which may be tighter than what the probe parses",
       R, "        if probed.codec not in self.allowed_codecs:", "        if False:",
       "test_a_tightened_profile_refuses_media_the_probe_can_read"),
    _m("profile_mime_allowlist_removed",
       "the profile's container set is the pin, likewise",
       R, "        if probed.mime not in self.allowed_mime:", "        if False:",
       "test_a_tightened_profile_refuses_media_the_probe_can_read"),
    _m("profile_byte_cap_removed",
       "the profile's byte cap is enforced on what was really decoded",
       R, "        if nbytes > self.max_bytes:", "        if False:",
       "test_a_tightened_profile_refuses_media_the_probe_can_read"),
    _m("duration_cap_not_read_from_the_settings",
       "the pinned profile reads MAX_VIDEO_SECONDS from the settings, not a literal",
       R, "        return cls(version=valid_profile(version), max_duration_s=limits.max_video_seconds,",
       "        return cls(version=valid_profile(version), max_duration_s=1e9,",
       "test_a_clip_over_the_duration_cap_is_refused_before_it_is_stored"),
    _m("parts_per_request_uncapped",
       "one clip per request is a capacity fact, and it is checked before anything is fetched",
       R, "        if len(sources) > self.profile.max_parts:", "        if False:",
       "test_more_parts_than_the_profile_allows_are_refused"),
    _m("request_org_coherence_removed",
       "R10: a request is prepared for its own organization or not at all",
       R, "        if request.org_id != org_id:\n"
          '            raise errors.Forbidden("a request may only be prepared for its own org")',
       "        if False:\n"
          '            raise errors.Forbidden("a request may only be prepared for its own org")',
       "test_a_request_may_only_be_prepared_for_its_own_org"),
    _m("callers_media_tuple_kept",
       "`NormalizedRequest.media` is a claim: the prepared record carries the refs "
       "preparation actually materialized",
       R, '                                          "media": refs})',
       '                                          "media": request.media or refs})',
       "test_a_ref_the_caller_put_in_the_record_is_discarded"),
    _m("rewrite_out_of_order",
       "R58 pairs the n-th media part with the n-th ref; out of order is an answer about "
       "another clip",
       R, "                parts.append({\"type\": VIDEO_PART, VIDEO_PART: {REF_KEY: refs[consumed].handle}})",
       "                parts.append({\"type\": VIDEO_PART, VIDEO_PART: {REF_KEY: refs[-1].handle}})",
       "test_the_parts_and_the_refs_stay_in_order"),
    _m("video_part_shape_unchecked",
       "a part with no url, or one that is not a string, is a typed refusal naming the part "
       "(declared: without it the kill is an AttributeError inside materialization)",
       R, "        if not isinstance(source, str) or not source:\n"
          '            raise errors.InvalidRequest("a video part carries exactly {url}", param="messages")',
       "        if False:\n"
          '            raise errors.InvalidRequest("a video part carries exactly {url}", param="messages")',
       "test_a_video_part_that_is_not_exactly_a_url_is_refused", dies_by=("AttributeError",)),
    _m("preparation_pool_unbounded",
       "r1 R1: PREPARATION_CONCURRENCY bounds how many clips are in memory at once",
       R, "        self.gate = asyncio.Semaphore(max(1, self.limits.preparation_concurrency))",
       "        self.gate = asyncio.Semaphore(1024)",
       "test_preparation_runs_at_most_the_pool_width_at_once"),
    _m("request_memory_budget_removed",
       "one request has one media budget, however many parts it spreads it over",
       R, "        if self.spent > self.allowed:", "        if False:",
       "test_one_request_cannot_exceed_the_media_budget"),
    _m("probe_deadline_removed",
       "PROBE_TIMEOUT_S bounds a decoder that never returns",
       R, "            return await asyncio.wait_for(work, self.limits.probe_timeout_s)",
       "            return await work",
       "test_a_probe_that_never_returns_is_bounded_by_its_deadline", dies_by=("TimeoutError",)),
    _m("head_check_removed",
       "the cheap check answers first: HEAD says the object is gone, so 64 MiB is never read",
       R, "            if await self.objects.head(key) != ref.digest:", "            if False:",
       "test_an_object_that_vanished_between_attach_and_prepare_is_not_found"),
    _m("digest_not_rechecked_after_the_read",
       "HEAD and digest, not HEAD alone: a store that answers with other bytes must not have "
       "them prepared and answered about",
       R, "                if data is None or await asyncio.to_thread(digest_of, data) != ref.digest:",
       "                if data is None:",
       "test_an_object_whose_content_changed_is_not_prepared"),
    _m("cache_hit_stands_in_for_the_durable_artifact",
       "a cache hit is a hit on the local copy; the durable prepared artifact is the record, "
       "so its absence runs the whole path again",
       R, "                    or await self.objects.head(prepared_key) is None:",
       "                    or False:",
       "test_a_prepared_artifact_that_is_gone_is_written_again"),
    _m("prepared_key_uses_the_sources_profile",
       "01: the profile version namespaces the cache, so it is the *requested* profile in "
       "the prepared key",
       R, '                "profile_version": version, "storage_ref": prepared_key,',
       '                "profile_version": version,\n                "storage_ref": self._key('
       'ref.org_id, ref.digest, ref.profile_version, "prepared"),',
       "test_the_profile_version_namespaces_the_prepared_artifact"),
    _m("local_copy_written_before_the_durable_artifact",
       "durable before local: a cache entry written first survives a failed durable write "
       "and the next attempt reports a job prepared against an object that is not there "
       "(review R12)",
       R, "                # Durable before local: the prepared artifact exists in the object store\n"
          "                # before anything downstream can be told the job is prepared.\n"
          "                await self._write_once(prepared_key, body, probed.mime)\n"
          "                entry = (self.cache.put(ref.org_id, ref.digest, version, body, probed)\n"
          "                         if self.cache.enabled\n"
          '                         else CacheEntry("", probed, len(body), 0.0))',
       "                entry = (self.cache.put(ref.org_id, ref.digest, version, body, probed)\n"
          "                         if self.cache.enabled\n"
          '                         else CacheEntry("", probed, len(body), 0.0))\n'
          "                await self._write_once(prepared_key, body, probed.mime)",
       "test_a_failed_durable_write_leaves_no_local_copy"),
    _m("duration_cap_is_a_literal",
       "the duration bound is this deployment's MAX_VIDEO_SECONDS, not the number the "
       "default happens to carry (review R7)",
       R, "        return cls(version=valid_profile(version), max_duration_s=limits.max_video_seconds,",
       "        return cls(version=valid_profile(version), max_duration_s=120.0,",
       "test_a_clip_over_the_duration_cap_is_refused_before_it_is_stored"),
    _m("duration_cap_excludes_its_own_bound",
       "the cap is inclusive: 120.000 s is 240 frames at 2 fps, the worst case the profile "
       "is sized for (review R24)",
       R, "        if probed.duration_s > self.max_duration_s:",
       "        if probed.duration_s >= self.max_duration_s:",
       "test_a_clip_exactly_at_the_cap_is_accepted",
       # M4: the same inclusive bound when the cap is read from a download's header
       "test_a_header_that_is_not_complete_yet_is_looked_at_again"),
    _m("prepared_artifact_not_persisted",
       "the prepared artifact is durable before anything downstream is told the job is "
       "prepared; the local cache is a copy, not the record",
       R, "                await self._write_once(prepared_key, body, probed.mime)",
       "                pass",
       "test_prepare_persists_the_artifact_and_a_file_the_engine_can_open"),
    _m("prepared_ref_trusts_the_attached_duration",
       "the prepared duration is the measurement, not the number on the attached record "
       "(a job row can hand back whatever it stored) (review R1/R23)",
       R, '                "duration_s": entry.probed.duration_s}))',
       '                "duration_s": ref.duration_s}))',
       "test_the_prepared_ref_carries_the_measurement_not_the_attached_record"),
    _m("prepared_ref_trusts_the_attached_mime",
       "likewise the container: it decides the cache file's extension and what the engine "
       "is told it is opening",
       R, '                "mime": entry.probed.mime, "bytes": entry.bytes,',
       '                "mime": ref.mime, "bytes": entry.bytes,',
       "test_the_prepared_ref_carries_the_measurement_not_the_attached_record"),
    _m("prepared_ref_trusts_the_attached_size",
       "likewise the size of the artifact that was actually prepared",
       R, '                "mime": entry.probed.mime, "bytes": entry.bytes,',
       '                "mime": entry.probed.mime, "bytes": ref.bytes,',
       "test_the_prepared_ref_carries_the_measurement_not_the_attached_record"),
    _m("prepared_ref_carries_no_duration",
       "the prepared ref carries the measured duration, which is what the engine budgets "
       "frames from",
       R, '                "duration_s": entry.probed.duration_s}))', '                "duration_s": None}))',
       "test_prepare_persists_the_artifact_and_a_file_the_engine_can_open",
       "test_what_preparation_produces_is_what_the_engine_adapter_accepts"),
    _m("prepared_refs_replace_the_attached_sources",
       "R46 allows bounded preparation retries, so a second attempt re-derives the same "
       "answer instead of preparing the first attempt's output",
       R, "        self.prepared_by_job[job_id] = tuple(prepared)",
       "        self.by_job[job_id] = tuple(prepared)",
       "test_preparing_twice_is_the_same_answer"),
    _m("unknown_job_prepared_as_empty",
       "r1 R46/q23: `prepare` resolves this job's refs or nothing; an empty prepared set for "
       "an unknown job looks like a finished preparation",
       R, "        if sources is None:\n"
          '            raise errors.NotFound(f"no staged media for job {job_id}")',
       "        if sources is None:\n            sources = ()",
       "test_prepare_refuses_a_job_it_knows_nothing_about"),
    _m("profile_version_unvalidated_before_the_read",
       "the profile version is validated before the object is read, so a malformed one costs "
       "no download and reaches no path",
       R, "        version = valid_profile(profile)", "        version = profile",
       "test_a_profile_version_cannot_escape_the_cache_root"),
    _m("cache_expiry_removed",
       "PROCESSING_CACHE_TTL_S is a retention obligation: past it the entry is unreadable",
       R, "        if self.clock() - entry.stored_at >= self.ttl_s:", "        if False:",
       "test_a_cache_entry_expires_and_its_file_goes_with_it",
       "test_a_prepared_clip_is_the_same_across_runs_stores_forms_and_expiry"),
    _m("cache_file_existence_unchecked",
       "the index is a hint about the disk: an entry pointing at a file that is gone is a "
       "miss, not a path handed to a worker",
       R, "        if not os.path.exists(entry.local_path):", "        if False:",
       "test_a_cache_file_deleted_behind_the_index_is_a_miss"),
    _m("cache_path_without_the_tenant",
       "MEDIA-SEC: the organization is in the path, so identical bytes in two tenants are two "
       "files and neither tenant can reach the other's",
       R, "        path = os.path.join(self.root, valid_org(org_id), valid_profile(profile),",
       "        path = os.path.join(self.root, valid_profile(profile),",
       "test_one_tenants_cache_entry_is_not_another_tenants",
       "test_the_cache_path_is_built_from_validated_parts_only"),
    _m("cache_digest_segment_width",
       "a key and a cache path carry the first 16 hex characters of the digest; a shorter "
       "segment is a different address space for the same content (review survivor R9)",
       S, '    return digest[len("sha256:"):][:16]', '    return digest[len("sha256:"):][:12]',
       "test_the_cache_path_is_built_from_validated_parts_only",
       "test_a_fetched_source_becomes_a_tenant_scoped_content_addressed_object"),
    _m("cache_root_check_rejects_valid_paths",
       "the cache-root check must accept the paths the cache builds. **Removing** it is not "
       "killable and is not claimed: `valid_org`, `valid_profile` and `valid_digest` already "
       "exclude every segment that could escape, so it is belt to their braces (review "
       "survivor R10) - what is proved here is that the belt does not refuse a valid path",
       R, "        if os.path.commonpath([self.root, os.path.abspath(path)]) != self.root:",
       "        if os.path.commonpath([self.root, os.path.abspath(path)]) == self.root:",
       "test_the_cache_path_is_built_from_validated_parts_only"),
    _m("cache_path_without_the_profile",
       "R61 as amended: the profile version is a path segment as well as an index key, or "
       "two profiles of one source share one file and expiring one deletes the other's "
       "bytes (review B2)",
       R, "        path = os.path.join(self.root, valid_org(org_id), valid_profile(profile),\n"
          '                            valid_digest(digest), f"{SOURCE_FILENAME}.{extension}")',
       "        path = os.path.join(self.root, valid_org(org_id),\n"
          '                            valid_digest(digest), f"{SOURCE_FILENAME}.{extension}")',
       "test_two_profiles_of_one_object_are_two_local_files",
       "test_the_cache_path_is_built_from_validated_parts_only"),
    _m("cache_extension_unchecked",
       "a cache file is named for a container the profile serves; `source.None` is not a "
       "file any decoder opens",
       R, "        extension = EXTENSIONS.get(mime)\n        if extension is None:",
       "        extension = EXTENSIONS.get(mime)\n        if False:",
       "test_the_cache_path_is_built_from_validated_parts_only"),
    _m("sweep_removes_live_entries",
       "a sweep removes what is past its life and nothing else",
       R, "                   if now - entry.stored_at >= self.ttl_s]", "                   if True]",
       "test_a_sweep_removes_expired_entries_and_leaves_live_ones"),

    # --- M1's store, where M2's probe hook meets it ------------------------
    _m("facts_hook_not_consulted",
       "what a ref records about the bytes comes from `facts`, which M2 overrides with a "
       "probe; hard-coding the fetcher's answer loses the duration and the container",
       S, "        mime, duration_s = await self.facts(fetched.data, fetched.mime)",
       "        mime, duration_s = fetched.mime, None",
       "test_preparation_measures_the_clip_and_fills_the_record",
       "test_the_container_wins_over_the_declared_type"),
    _m("stored_content_type_is_the_declared_one",
       "the object is stored as the container it is, not as the type the server declared",
       S, "        await self._write_once(ref.storage_ref, fetched.data, ref.mime)",
       "        await self._write_once(ref.storage_ref, fetched.data, fetched.mime)",
       "test_the_container_wins_over_the_declared_type"),
    # === M3/M5: owned uploads (media/uploads.py) ========================================
    # M5 moved the ticket to F2C's `UploadRepository`: create's constraint checks are F2C's
    # `UploadConstraints.parse` (mutated in the contracts list), `ProcessUploads` is the
    # process-local port (its guards below die by F2C's own upload cases run on it). Four
    # guards restate a rule `UploadTicket` itself enforces (a receipt inside the cap and the
    # window; a finalized source's duration): removed, the record refuses one layer late with
    # a `ValidationError` - a 500 instead of the typed refusal - which they declare.
    _m("null_constraint_is_a_default", "a null cap or type list is refused, not defaulted",
       U, 'for name in ("max_bytes", "accepted_mime")):', "for name in ()):",
       "test_create_refuses_constraints_the_caller_shapes"),
    _m("duplicate_handle_accepted", "a repeated handle never takes over an existing upload",
       U, "                or handle in self.records:", "                or False:",
       "test_a_handle_source_that_repeats_itself_is_refused"),
    _m("destination_carries_the_org", "R61(1): the destination is infrx-upload:upl_<id> only",
       U, "destination_ref=UPLOAD_REF_SCHEME + ticket.upload_handle",
       'destination_ref=UPLOAD_REF_SCHEME + org_id + ":" + ticket.upload_handle',
       "test_create_issues_an_opaque_handle_and_a_constrained_destination"),
    _m("upload_window_never_closes", "past expires_at an open upload takes nothing",
       U, "        if self.now() >= ticket.expires_at:\n"
          "            raise refuse(R.upload_expired, \"the upload window closed",
       "        if False:\n            raise refuse(R.upload_expired, \"the upload window closed",
       "test_an_expired_window_is_upload_expired_and_stays_closed",
       dies_by=("ValidationError",)),
    _m("upload_window_excludes_its_end", "the window is closed at expires_at, not after it",
       U, "        if self.now() >= ticket.expires_at:\n"
          "            raise refuse(R.upload_expired, \"the upload window closed",
       "        if self.now() > ticket.expires_at:\n"
       "            raise refuse(R.upload_expired, \"the upload window closed",
       "test_an_expired_window_is_upload_expired_and_stays_closed",
       dies_by=("ValidationError",)),
    _m("closed_upload_reopens", "a refused or completed upload takes no second attempt",
       U, "        if ticket.state is not UploadState.created:\n            raise refuse(R.upload_not_open, f\"upload {ticket",
       "        if ticket.state is UploadState.expired:\n            raise refuse(R.upload_not_open, f\"upload {ticket",
       "test_a_refused_upload_stays_refused", "test_a_completed_upload_accepts_no_more_bytes"),
    _m("put_uncapped", "a receipt over the ticket's cap is refused before any byte is stored",
       U, "        if bytes > ticket.constraints.max_bytes:", "        if False:",
       "test_put_upload_is_bounded_and_write_once",
       dies_by=("ValidationError",)),
    _m("receipt_replaced", "one handle, one set of bytes: another receipt is bytes_changed",
       U, "            if (ticket.received.bytes, ticket.received.digest) != (bytes, digest):",
       "            if False:",
       "test_the_f2c_upload_cases_pass_on_the_process_local_repository"),
    _m("upload_owner_unchecked", "another org's upload handle is not_found",
       U, "        if ticket is None or ticket.org_id != org_id:", "        if ticket is None:",
       "test_another_org_cannot_put_finalize_or_resolve"),
    _m("relabelled_source_completes", "complete takes only this ticket's own upload ref",
       U, "        if (source.org_id, source.handle, source.kind) != (org_id, upload_handle,",
       "        if False and (source.org_id, source.handle, source.kind) != (org_id, upload_handle,",
       "test_the_f2c_upload_cases_pass_on_the_process_local_repository"),
    _m("second_completion_replaces_bytes", "a completed ticket answers only its own bytes",
       U, "            if (done.digest, done.bytes, done.mime) != (source.digest, source.bytes, source.mime):",
       "            if False:",
       "test_the_f2c_upload_cases_pass_on_the_process_local_repository"),
    _m("unmeasured_duration_completes", "a completion carries the measured duration (F2C)",
       U, "        if source.duration_s is None:", "        if False:",
       "test_a_completion_without_a_measured_duration_is_refused",
       dies_by=("ValidationError",)),
    _m("abort_reopens_a_closed_ticket", "only an open ticket is aborted",
       U, "        if ticket.state is not UploadState.created or self.now() >= ticket.expires_at:",
       "        if False:",
       "test_the_f2c_upload_cases_pass_on_the_process_local_repository",
       dies_by=("ValidationError",)),
    _m("abort_records_any_reason", "a ticket records only a public upload refusal (F2C)",
       U, "        if refusal not in UPLOAD_ABORT_REASONS:", "        if False:",
       "test_the_f2c_upload_cases_pass_on_the_process_local_repository",
       dies_by=("ValidationError",)),
    _m("receipt_digest_unchecked", "a receipt's digest is a sha256 digest",
       U, "        if not isinstance(digest, str) or not DIGEST_RE.fullmatch(digest):",
       "        if False:",
       "test_the_f2c_upload_cases_pass_on_the_process_local_repository",
       dies_by=("ValidationError",)),
    _m("unfinalized_ticket_resolves", "only a finalized ticket resolves",
       U, "        if ticket.state is not UploadState.finalized:", "        if False:",
       "test_the_f2c_upload_cases_pass_on_the_process_local_repository"),
    _m("use_window_never_closes", "past expires_at a finalized upload is upload_expired",
       U, "        if self.now() >= ticket.expires_at:\n"
          "            raise refuse(R.upload_expired, \"the upload window has expired\")",
       "        if False:\n            raise refuse(R.upload_expired, \"the upload window has expired\")",
       "test_the_f2c_upload_cases_pass_on_the_process_local_repository"),
    _m("expire_ignores_the_window", "expire closes only tickets past their window",
       U, "if t.state is UploadState.created and now >= t.expires_at),",
       "if t.state is UploadState.created),",
       "test_upload_destinations_live_exactly_as_long_as_the_upload_is_open"),
    _m("bytes_before_the_receipt", "a refused PUT writes nothing: the receipt comes first",
       U, "        await self.tickets.acknowledge_put(org_id, handle, bytes=len(data), digest=digest)\n"
          "        await self._register(ContentKind.upload_destination, org_id, key, digest, len(data),\n"
          "                             handle)\n"
          "        await self._write_once(key, data, content_type)",
       "        await self._write_once(key, data, content_type)\n"
       "        await self.tickets.acknowledge_put(org_id, handle, bytes=len(data), digest=digest)\n"
       "        await self._register(ContentKind.upload_destination, org_id, key, digest, len(data),\n"
       "                             handle)",
       "test_upload_restart__another_tenant_is_not_found_in_every_process"),
    _m("finalize_unlocked", "concurrent finalizes in one process verify and copy once",
       U, "        flight = self._finalizing.get((org_id, upload_handle))", "        flight = None",
       "test_concurrent_finalizes_verify_and_copy_once"),
    _m("finalize_past_a_refusal", "only a not-yet-finalized ticket is verified; any other "
       "refusal is the answer",
       U, "            if refusal_of(refused) is not R.upload_not_finalized:\n                raise",
       "            if False:\n                raise",
       "test_another_org_cannot_put_finalize_or_resolve"),
    _m("refinalize_ignores_a_changed_destination",
       "a retry after the destination changed is a conflict, never a quiet success",
       U, "if await self.objects.head(key) not in (None, ref.digest):", "if False:",
       "test_a_second_finalize_with_other_bytes_is_a_conflict"),
    _m("finalize_not_idempotent", "a retry of a completed upload returns the same ref",
       U, "with other bytes\")\n            return ref", "with other bytes\")",
       "test_a_retry_returns_the_same_completed_handle"),
    _m("head_size_unchecked", "bytes over MAX_MEDIA_BYTES are refused before a download",
       U, "            if size > self.limits.max_media_bytes:", "            if False:",
       "test_an_oversize_object_is_refused_without_being_downloaded"),
    _m("oversize_not_final", "bytes over the ticket's cap abort it (the bytes decide)",
       U, "                raise await self._abort(org_id, handle, R.too_large, refused)",
       "                raise refused",
       "test_a_head_that_understates_the_size_is_caught_by_the_bytes"),
    _m("declared_size_unverified", "a declared exact size is checked before anything is copied",
       U, "            if c.bytes is not None and len(data) != c.bytes:", "            if False:",
       "test_a_declared_size_is_verified"),
    _m("declared_digest_unverified", "a declared digest is checked before anything is copied",
       U, "            if c.digest is not None and digest != c.digest:", "            if False:",
       "test_a_declared_digest_is_verified"),
    _m("declared_digest_prefix_compared", "the whole declared digest is compared (review)",
       U, "            if c.digest is not None and digest != c.digest:",
       "            if c.digest is not None and digest[:20] != c.digest[:20]:",
       "test_a_declared_digest_is_verified"),
    _m("declared_type_trusted", "type and duration come from the bytes (the probe)",
       U, "mime, duration_s = await self.facts(data, declared_mime)",
       "mime, duration_s = declared_mime, None",
       "test_the_container_wins_over_the_declared_content_type",
       "test_finalize_measures_the_bytes_that_arrived"),
    _m("probe_refusal_not_final", "bytes the probe refuses abort the upload",
       U, "                raise await self._abort(org_id, handle, R.media_refused, refused)",
       "                raise refused",
       "test_bytes_the_probe_refuses_abort_the_upload"),
    _m("accepted_type_unchecked", "a type outside the accept list is refused before a copy",
       U, "            if mime not in c.accepted_mime:", "            if False:",
       "test_an_unaccepted_type_is_refused"),
    _m("upload_not_at_the_source_key",
       "a finalized upload's bytes live at the content-addressed source key prepare rebuilds",
       U, '                           storage_ref=self._key(org_id, digest, self.profile_version,\n'
          '                                                 "source"),',
       '                           storage_ref=self._key(org_id, digest, self.profile_version,\n'
       '                                                 "upload"),',
       "test_finalize_measures_the_bytes_that_arrived",
       "test_an_uploaded_clip_is_prepared_like_any_source"),
    _m("ticket_names_another_key", "the ref a ticket names is rebuilt at the source key",
       U, '                                              done.profile_version, "source"),',
       '                                              done.profile_version, "upload"),',
       "test_finalize_measures_the_bytes_that_arrived"),
    _m("refusal_not_recorded", "an aborted upload stays aborted, in the repository",
       U, "        await self.tickets.abort(org_id, handle, reason)", "        pass",
       "test_a_refused_upload_stays_refused"),
    _m("unfinalized_upload_resolves_as_invalid", "R99(a): an unfinalized upload is not_found",
       U, "            if refusal_of(refused) is R.upload_not_finalized:\n"
          "                raise errors.NotFound",
       "            if False:\n                raise errors.NotFound",
       "test_resolve_refuses_an_upload_that_is_not_finalized_even_if_its_handle_is_indexed"),
    _m("upload_handle_resolved_by_the_index", "an upload handle resolves through its ticket",
       U, "        if not isinstance(ref, str) or not UPLOAD_HANDLE_RE.fullmatch(ref):\n"
          "            return await super().resolve_owned(org_id, ref)",
       "        if True:\n            return await super().resolve_owned(org_id, ref)",
       "test_finalize_measures_the_bytes_that_arrived"),
    _m("use_time_recheck_case_folded", "the use-time re-check is exact, not case-folded (review)",
       U, "        if await self.objects.head(media.storage_ref) != media.digest:",
       "        if (await self.objects.head(media.storage_ref) or \"\").lower() != media.digest:",
       "test_the_use_time_recheck_compares_the_whole_digest"),
    _m("changed_upload_object_resolves", "a finalized upload's object is re-checked at use",
       U, "        if await self.objects.head(media.storage_ref) != media.digest:",
       "        if False:",
       "test_an_upload_whose_object_changed_is_not_staged"),
    _m("attach_accepts_a_forged_upload_ref",
       "an upload ref binds as the store's record, never the caller's copy (R82)",
       U, "        return record if record == ref else None", "        return ref",
       "test_upload_restart__forged_digest_or_a_second_finalize_never_replaces_accepted_bytes"),
    _m("attach_compares_only_the_digest",
       "the caller's upload ref must be the store's record field for field: a forged key "
       "(another tenant's same bytes), duration, size, type or handle binds nothing",
       U, "        return record if record == ref else None",
       "        return record if record.digest == ref.digest else None",
       "test_upload_restart__forged_digest_or_a_second_finalize_never_replaces_accepted_bytes"),
    _m("expired_binding_not_replayed",
       "past the window a job's own binding, attached again, is a no-op (M5 item 3)",
       U, "            if bound != tuple(refs):\n                raise",
       "            if True:\n                raise",
       "test_upload_restart__the_window_is_the_tickets_and_an_admitted_job_outlives_it"),
    _m("upload_ref_bound_by_the_index", "an upload ref binds through its ticket, not M1's index",
       U, "        if ref.kind is not MediaKind.upload:\n            return await super()._staged_ref(org_id, ref)",
       "        if True:\n            return await super()._staged_ref(org_id, ref)",
       "test_an_uploaded_clip_is_prepared_like_any_source",
       "test_upload_restart__the_window_is_the_tickets_and_an_admitted_job_outlives_it"),
    _m("content_rows_not_registered", "each written object has its content row first (F2C)",
       U, "        if self.content is not None:", "        if False:",
       "test_upload_restart__create_put_complete_and_use_each_in_another_process"),
    _m("finalize_unbounded", "completions download under the preparation pool's bound",
       U, "        async with self.gate:\n            described", "        if True:\n            described",
       "test_concurrent_completions_share_the_preparation_bound"),
    _m("stage_is_not_a_use", "staging renews an object's grace",
       U, "        refs = await super().stage(org_id, request)\n        self._touch(refs)",
       "        refs = await super().stage(org_id, request)",
       "test_recent_use_renews_the_grace"),
    _m("attach_is_not_a_use", "attaching renews an object's grace",
       U, "        self._touch(self.by_job[job_id])", "        pass",
       "test_attach_is_a_use"),
    _m("finalize_is_not_a_use", "finalizing renews the content-addressed object's grace",
       U, "        if ref.storage_ref in self.idle_since:  # a use", "        if False:  # a use",
       "test_a_finalize_is_a_use"),
    # === M3: collection (media/gc.py) =====================================================
    _m("liveness_ignored", "a live job's input is protected",
       G, "            if job in live:", "            if False:",
       "test_a_live_jobs_input_is_never_collected"),
    _m("prepared_artifact_unprotected", "a live job's prepared artifact is protected too",
       G, "refs = store.by_job.get(job, ()) + store.prepared_by_job.get(job, ())",
       "refs = store.by_job.get(job, ())",
       "test_a_live_jobs_input_is_never_collected"),
    _m("protection_is_only_the_grace", "protection holds even with a zero grace",
       G, "            if key in protected:\n                continue", "            pass",
       "test_a_live_jobs_input_is_never_collected"),
    _m("lookup_failure_fails_open", "a failed liveness lookup aborts the pass",
       G, "        live = {job for job in jobs if await self.is_live(job)}",
       "        live = set()\n        for job in jobs:\n            try:\n"
       "                if await self.is_live(job):\n                    live.add(job)\n"
       "            except Exception:\n                pass",
       "test_a_lookup_that_fails_collects_nothing"),
    _m("idle_not_renewed_while_live", "the grace counts from the last pass that saw it live",
       G, "            store.idle_since[key] = now        # grace", "            pass  # grace",
       "test_input_is_collected_after_the_job_ends_and_the_grace_passes"),
    _m("dead_job_attachments_kept", "an ended job's attachments are forgotten",
       G, "                store.by_job.pop(job, None)", "                pass",
       "test_input_is_collected_after_the_job_ends_and_the_grace_passes"),
    _m("grace_ignored", "an unreferenced object survives the grace period",
       G, "            if now - store.idle_since.setdefault(key, now) >= self.grace:",
       "            if True:",
       "test_a_failed_stage_blob_is_eventually_removed"),
    _m("orphans_never_collected", "an unreferenced object is removed after the grace",
       G, "            if now - store.idle_since.setdefault(key, now) >= self.grace:",
       "            if False:",
       "test_a_failed_stage_blob_is_eventually_removed"),
    _m("index_forgotten_after_the_delete", "a collected object leaves the index before its delete",
       G, "                self._forget(key)\n                await store.objects.delete(key)",
       "                await store.objects.delete(key)\n                self._forget(key)",
       "test_a_stage_during_the_delete_is_refused_not_admitted"),
    _m("collected_ref_still_resolves", "a collected object's refs leave the index",
       G, "                del store.refs[index]", "                pass",
       "test_media_staged_for_a_request_never_admitted_is_removed"),
    _m("open_set_taken_before_the_listing",
       "an upload created while the listing is in flight keeps its destination (review B1)",
       G, _B1_FIXED, _B1_STALE,
       "test_an_upload_created_during_the_listing_keeps_its_destination"),
    _m("open_destination_collected", "an open upload's destination is kept",
       G, "            if upload.state is UploadState.created:\n                open_destinations",
       "            if False:\n                open_destinations",
       "test_upload_destinations_live_exactly_as_long_as_the_upload_is_open"),
    _m("closed_destination_kept", "a closed upload's destination is removed",
       G, "            if key not in open_destinations:", "            if False:",
       "test_upload_destinations_live_exactly_as_long_as_the_upload_is_open"),
    _m("lapsed_window_left_open", "a pass closes a lapsed upload window",
       G, "swept.uploads_expired = await store.tickets.expire(max(1, len(uploads)))",
       "swept.uploads_expired = 0",
       "test_a_lapsed_upload_window_is_closed_and_its_bytes_removed"),
    _m("refused_record_kept_forever", "a refused upload record is dropped after the grace",
       G, "                del uploads[handle]            # a refused", "                pass  # a refused",
       "test_a_refused_upload_record_is_dropped_after_the_grace"),
    _m("finalized_record_dropped_by_age", "a finalized record lives as long as its object (review)",
       G, "elif upload.state is not UploadState.finalized and now >= upload.expires_at + self.grace:",
       "elif now >= upload.expires_at + self.grace:",
       "test_a_finalized_record_outlives_its_window_while_its_object_lives"),
    _m("refused_record_dropped_early", "a refused record is kept for the grace after expiry",
       G, "now >= upload.expires_at + self.grace:", "now >= upload.expires_at:",
       "test_a_refused_upload_record_is_dropped_after_the_grace"),
    _m("cache_expiry_not_run", "a pass runs ProcessingCache.sweep",
       G, "swept.cache_expired = cache.sweep()", "swept.cache_expired = 0",
       "test_the_sweep_runs_the_processing_cache_expiry"),
    _m("cache_cap_ignored", "the cache byte cap is enforced",
       G, "            if self.max_cache_bytes is not None:", "            if False:",
       "test_the_cache_cap_evicts_idle_entries_and_never_a_live_jobs"),
    _m("cache_cap_evicts_live_entries", "a live job's cache entry is never evicted",
       G, "                    if key in in_use:\n                        continue",
       "                    pass",
       "test_the_cache_cap_evicts_idle_entries_and_never_a_live_jobs"),
    _m("cache_cap_evicts_newest_first", "eviction is oldest first",
       G, "key=lambda kv: kv[1].stored_at)", "key=lambda kv: -kv[1].stored_at)",
       "test_the_cache_cap_evicts_idle_entries_and_never_a_live_jobs"),
    _m("stray_files_removed_at_once", "a stray cache file gets the grace first",
       G, "if now - self.stray_since.setdefault(path, now) >= self.grace:", "if True:",
       "test_stray_cache_files_are_removed_after_the_grace"),
    _m("indexed_files_treated_as_stray", "an indexed cache file is never a stray",
       G, "                if path in indexed:\n                    continue", "                pass",
       "test_stray_cache_files_are_removed_after_the_grace"),
    _m("failed_pass_stops_the_schedule", "a failed pass is logged and collection goes on",
       G, "            except Exception:\n                log.exception",
       "            except ZeroDivisionError:\n                log.exception",
       "test_run_sweeps_on_a_schedule_and_survives_a_failed_pass"),
    # === M3: consented reuse (media/consent.py) ===========================================
    _m("consent_org_unchecked", "another org's consent never opens this org's media",
       C, "    if consent.org_id != org_id:", "    if False:",
       "test_another_orgs_consent_never_widens_the_tenant"),
    _m("judge_consent_unchecked", "judge reuse needs evaluation consent",
       C, "        check_consent(org_id, consent, now)", "        pass",
       "test_trace_consent_is_not_evaluation_consent"),
    _m("judge_window_unchecked", "evaluation consent is not retroactive (R56)",
       C, "        if not within_consent_window(captured_at, consent):", "        if False:",
       "test_evaluation_consent_is_not_retroactive"),
    _m("trace_mode_unchecked", "trace reuse needs trace_mode full",
       C, "if not consent.is_current(now) or consent.trace_mode is not TraceMode.full:",
       "if not consent.is_current(now):",
       "test_trace_reuse_needs_current_full_trace_consent"),
    _m("trace_consent_currency_unchecked", "trace reuse needs a current consent record",
       C, "if not consent.is_current(now) or consent.trace_mode is not TraceMode.full:",
       "if consent.trace_mode is not TraceMode.full:",
       "test_trace_reuse_needs_current_full_trace_consent"),
    _m("retention_unchecked", "content past its retention is result_expired",
       C, "    if now >= captured_at + timedelta(days=consent.content_retention_days):",
       "    if False:", "test_content_expires_logically_at_its_retention"),
    _m("retention_excludes_its_end", "content is expired at its retention, not after",
       C, "    if now >= captured_at + timedelta(days=consent.content_retention_days):",
       "    if now > captured_at + timedelta(days=consent.content_retention_days):",
       "test_content_expires_logically_at_its_retention"),
    _m("reused_bytes_unverified", "the bytes handed to T/J hash to the ref's digest",
       C, "    if data is None or digest_of(data) != ref.digest:", "    if data is None:",
       "test_the_bytes_returned_are_the_refs_bytes"),
    _m("unknown_purpose_allowed", "a reuse purpose outside trace/judge is refused",
       C, "    else:\n        raise errors.InvalidRequest(f\"unknown reuse purpose",
       "    elif False:\n        raise errors.InvalidRequest(f\"unknown reuse purpose",
       "test_an_unknown_purpose_is_refused"),
    # === M4: the streaming digest and one copy (media/fetch.py) ============================
    _m("streaming_digest_keeps_only_the_last_chunk",
       "the fetched digest covers every chunk, in order",
       F, "                        hasher.update(chunk)\n",
       "                        hasher = hashlib.sha256(chunk)\n",
       "test_the_digest_covers_every_chunk_in_the_order_it_arrived"),
    _m("fetched_body_copied_twice",
       "a fetched body is copied once: the high-water stays under 2.5x the body (was ~3x)",
       F, 'digest="sha256:" + hasher.hexdigest(), host=host)',
       "digest=digest_of(bytes(body)), host=host)",
       "test_a_fetched_body_is_held_at_most_about_twice"),
    # === M4: full-body digests off the event loop (media/store.py, media/prepare.py) =======
    _m("materialize_digest_on_the_loop",
       "materialize's full-body digest runs in a worker thread, not on the event loop",
       S, "        digest = await asyncio.to_thread(digest_of, fetched.data)",
       "        digest = digest_of(fetched.data)",
       "test_no_full_body_digest_runs_on_the_event_loop"),
    _m("prepare_digest_on_the_loop",
       "prepare's full-body digest runs in a worker thread, not on the event loop",
       R, "await asyncio.to_thread(digest_of, data) != ref.digest:",
       "digest_of(data) != ref.digest:",
       "test_no_full_body_digest_runs_on_the_event_loop"),
    # === M4: data: URLs - one copy of the text, the digest off the loop ======================
    _m("data_url_text_copied_again",
       "a data: URL is decoded from one slice of its text (high-water under 3x the output)",
       F, "        data = binascii.a2b_base64(payload, strict_mode=True)",
       "        data = binascii.a2b_base64(payload.encode(\"ascii\"), strict_mode=True)",
       "test_a_data_url_is_decoded_from_one_copy_of_its_text"),
    _m("data_url_decoded_on_the_loop",
       "a data: URL is decoded, and its digest taken, in a worker thread",
       S, "            fetched, kind = await asyncio.to_thread(\n"
          "                decode_data_url, source, self.limits, self.fetcher.allowed_mime), MediaKind.inline",
       "            fetched, kind = decode_data_url(source, self.limits, self.fetcher.allowed_mime), MediaKind.inline",
       "test_no_full_body_digest_runs_on_the_event_loop"),
    # === M4: refusing from the header of a download in progress =============================
    _m("early_look_never_taken", "the head of a download is looked at once it reaches 1 MiB",
       F, "                        if early is not None and len(body) >= look:",
       "                        if False:",
       "test_a_header_first_clip_over_the_cap_is_refused_before_the_rest_arrives",
       "test_the_head_is_looked_at_when_it_doubles_not_on_every_chunk"),
    _m("early_look_on_every_chunk", "the head is looked at when it has doubled, not per chunk",
       F, "                            look = 2 * len(body)", "                            look = len(body)",
       "test_the_head_is_looked_at_when_it_doubles_not_on_every_chunk"),
    _m("early_look_not_wired", "materialize shows the fetcher's download head to the profile",
       S, "await self.fetcher.fetch(source, early=self.refuse_early)",
       "await self.fetcher.fetch(source)",
       "test_a_header_first_clip_over_the_cap_is_refused_before_the_rest_arrives"),
    _m("header_not_checked_against_the_profile",
       "a header the profile refuses stops the download",
       R, "            self.profile.check(probed, 0)           # bytes are the fetcher's own cap",
       "            pass",
       "test_a_header_first_clip_over_the_cap_is_refused_before_the_rest_arrives"),
    _m("early_refusal_reason_untagged", "the operator's log names an early refusal as such",
       R, "            refusal.reason = \"header\"", "            pass",
       "test_a_header_first_clip_over_the_cap_is_refused_before_the_rest_arrives"),
    _m("header_probe_refusal_escapes",
       "an incomplete or unprobeable header is 'nothing yet', never a refusal",
       P, "    except errors.UnsupportedMedia:        # truncated",
       "    except ValueError:        # truncated",
       "test_a_media_first_clip_within_the_cap_is_read_to_the_end_and_accepted"),
    _m("incomplete_header_probed", "a moov still arriving is not copied and probed",
       P, "if at + size <= len(data) else None", "if True else None",
       "test_a_header_still_arriving_is_not_probed"),
    _m("header_scan_unbounded", "the early walk stops after MAX_ELEMENTS boxes, as the probe does",
       P, "        for _ in range(MAX_ELEMENTS):\n            size, kind",
       "        while True:\n            size, kind",
       "test_the_header_scan_stops_where_the_probe_would"),
    # === M4 fold-in (review 2e323be) ===========================================================
    _m("header_probe_copy_unbounded",
       "S1: a look copies and probes at most HEADER_PROBE_MAX of the head",
       P, "                if at + size > HEADER_PROBE_MAX:", "                if False:",
       "test_a_moov_too_large_for_a_look_is_left_to_the_whole_object"),
    _m("early_look_never_settles",
       "S1: a head that settled everything it can is not shown again",
       F, "                                early = None      # settled",
       "                                pass              # settled",
       "test_a_settled_header_is_not_looked_at_again"),
    _m("header_never_settles",
       "S1: a complete moov that passed the profile settles the download's looks",
       R, "        return True                                 # settled", "        return False",
       "test_a_settled_header_is_not_looked_at_again"),
    _m("early_shown_a_copy",
       "S2: a look is shown the live buffer, so the body is still held at most about twice",
       F, "                            if early(body):", "                            if early(bytes(body)):",
       "test_a_fetched_body_is_held_at_most_about_twice"),
    _m("early_looks_stop_before_the_cap",
       "S3: the head is looked at at every doubling up to the cap, not only the first few",
       F, "                        if early is not None and len(body) >= look:",
       "                        if early is not None and len(body) >= look and len(body) <= (16 << 20):",
       "test_the_head_is_looked_at_when_it_doubles_not_on_every_chunk"),
    _m("early_refusal_drops_param",
       "S4: an early refusal is the whole-object refusal apart from its reason tag",
       R, "            refusal.reason = \"header\"",
       "            refusal.reason = \"header\"; refusal.param = None",
       "test_a_header_first_clip_over_the_cap_is_refused_before_the_rest_arrives"),
    _m("data_urls_ignore_the_configured_limits",
       "S5: the same limits decide a data: URL, before it is decoded",
       S, "                decode_data_url, source, self.limits, self.fetcher.allowed_mime)",
       "                decode_data_url, source, DEFAULTS, self.fetcher.allowed_mime)",
       "test_a_data_url_is_bounded_by_the_configured_limits_before_it_is_decoded"),
    _m("injected_probe_bypassed_early",
       "H2: with an injected probe, the built-in header walk refuses nothing early",
       R, "        if self.probe is not probing.probe:\n            return False",
       "        if False:\n            return False",
       "test_an_injected_probe_is_the_only_one_that_decides"),
    # === M4: MEDIA-PARITY (tests/m/test_parity.py) ============================================
    _m("prepared_bytes_are_not_the_source",
       "profile v1 prepares the source bytes: the durable and local artifacts hash to the ref",
       R, "        return data\n", "        return data[:-1]\n",
       "test_a_prepared_clip_is_the_same_across_runs_stores_forms_and_expiry"),
    _m("cache_file_name_varies",
       "a prepared clip lands at the same path under the cache root on every run and store",
       R, 'f"{SOURCE_FILENAME}.{extension}")', 'f"{SOURCE_FILENAME}.{time.monotonic_ns()}.{extension}")',
       "test_a_prepared_clip_is_the_same_across_runs_stores_forms_and_expiry"),
    _m("budget_frames_not_rounded_to_even",
       "the engine's frame budget for the measured duration is whole temporal patches (10.5 s -> 22)",
       V, "        frames += frames % 2\n", "        pass\n",
       "test_a_prepared_clip_is_the_same_across_runs_stores_forms_and_expiry"),
    _m("budget_frames_truncated",
       "P1: the engine's frame budget rounds the measured duration (5.3 s -> 12), not truncates",
       V, "max(s.min_frames, round(seconds * s.fps))", "max(s.min_frames, int(seconds * s.fps))",
       "test_a_prepared_clip_is_the_same_across_runs_stores_forms_and_expiry"),
    # === M3: the object-store port additions (media/store.py) =============================
    _m("keys_ignore_the_prefix", "a listing returns only the prefix it was asked for",
       S, "return sorted(key for key in self.objects if key.startswith(prefix))",
       "return sorted(self.objects)",
       "test_a_live_jobs_input_is_never_collected"),
    _m("describe_misreports_the_size", "describe reports the stored size",
       S, "return (len(stored[1]), stored[2]) if stored else None",
       "return (0, stored[2]) if stored else None",
       "test_an_oversize_object_is_refused_without_being_downloaded"),
)

#: F2R item 9: the shared runner, aimed at `tests/m`.
RUNNER = Runner(name="m1", targets=SUITE)


def run_mutant(mutant: Mutant) -> Result:
    """Apply one mutant to a throwaway copy and run the tests it names."""
    return shared.run_mutant(mutant, RUNNER)


if __name__ == "__main__":
    sys.exit(shared.main(MUTANTS, RUNNER, "run track M's mutation list"))
