#!/usr/bin/env python3
"""F2C.c: the published-model projection, alias pricing and the profile check (CATALOG-TRUTH).

Each test names the broken behaviour it catches (its failure oracle). The fixtures are
`infrx/contracts/v2/published/`, generated by `published_fixtures.py`; the console half
(`apps/app/tests/contracts/v2/published-model.test.ts`) reads the same files.

    uv run --frozen pytest -q tests/contracts/v2/test_published_model.py
    uv run --frozen python -m infrx.contracts.v2.published_fixtures --write   # regenerate
"""
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

import pytest
from pydantic import ValidationError

from infrx import config
from infrx.contracts import codec, errors, records as v1
from infrx.contracts.v2 import fixtures as v2fix, published_fixtures as pf
from infrx.contracts.v2 import published_model as pm
from infrx.contracts.v2.money_units import Credit, Usd
from infrx.contracts.v2.records import AccountingRegime, DeploymentState, Visibility
from infrx.gateway.routes import validate
from infrx.media.prepare import MediaProfile

from ..test_parity_console import ts_string_array

API = Path(__file__).resolve().parents[3]
REPO = API.parents[1]
TS = (API.parent / "app" / "lib" / "contracts" / "v2" / "published-model.ts").read_text()

CREDIT_DOC = pf.load("published_marlin_credit.json")
LEGACY_DOC = pf.load("published_marlin_legacy_usd.json")
PROFILE = pm.ServingProfile.model_validate(pf.load("serving_profile_marlin.json"))
CASES = pf.load("cases.json")
ALIASES = pf.load("alias_compatibility.json")


def _serving():
    return v2fix.BUILDERS["serving_revision.json"]()


def _deployment():
    return v2fix.BUILDERS["deployment_revision_public.json"]()


def _project(**overrides):
    profile = pf.deployed_profile()
    kw = dict(serving=_serving(), deployment=_deployment(), listing_version=1,
              regime="credit", credit_card=v2fix.BUILDERS["rate_card_marlin.json"](),
              credit_provisional=True, usd_price=pf._canonical_usd_row(),
              capability=profile.capability, retention=profile.retention, owned_by="nemostation",
              available=True, as_of=pf.AS_OF)
    kw.update(overrides)
    return pm.project(**kw)


# --- fixtures: generated, fresh, identical bytes ------------------------------
def test_every_fixture_is_claimed_and_fresh():
    """Oracle: a record change nobody regenerated, or a stray hand-written file."""
    assert set(pf.names()) == set(pf.BUILDERS)
    built = pf.build()
    for name in pf.names():
        assert built[name] == (pf.DIR / name).read_bytes(), (
            f"{name} is stale: uv run --frozen python -m infrx.contracts.v2.published_fixtures "
            f"--write")


@pytest.mark.parametrize("name,model", [("published_marlin_credit.json", pm.PublishedModel),
                                        ("published_marlin_legacy_usd.json", pm.PublishedModel),
                                        ("serving_profile_marlin.json", pm.ServingProfile)])
def test_each_record_round_trips_to_identical_bytes(name, model):
    """Oracle: a field that serializes differently from how it parses (the TS half
    byte-compares its own re-serialization against the same file)."""
    raw = (pf.DIR / name).read_bytes()
    assert codec.canonical_bytes(model.model_validate(json.loads(raw))) == raw


# --- the deployed profile is the runtime's, not a transcription ----------------
def runtime_profile(env: dict[str, str]) -> pm.ServingProfile:
    """How G7 builds the enforced profile from the running configuration (reference)."""
    settings = config.from_env(env)
    return pm.serving_profile(
        limits=settings.pilot, deployment=_deployment(), serving=_serving(),
        parameters=validate.SUPPORTED, refused=validate.UNSUPPORTED,
        video_mime=set(settings.allowed_video_mime) & set(MediaProfile().allowed_mime),
        fps=int(settings.fps), min_frames=settings.min_frames, max_frames=settings.max_frames,
        max_pixels_per_frame=settings.px_per_frame, execution_modes=list(v1.ExecutionMode))


def test_the_fixture_profile_is_what_the_deployed_configuration_enforces():
    """Oracle: the fixture's allow-list, MIME set, sampling or TTLs drifting from the code
    (validate.SUPPORTED/UNSUPPORTED, MediaProfile, Settings) or from the 82 s env."""
    assert runtime_profile({"MAX_VIDEO_SECONDS": "82"}) == PROFILE
    assert set(pf.ACCEPTED_PARAMETERS) == validate.SUPPORTED
    assert set(pf.REFUSED_PARAMETERS) == validate.UNSUPPORTED


def test_the_code_default_120s_profile_is_not_the_deployed_one():
    """Oracle: publishing from code defaults. Without MAX_VIDEO_SECONDS=82 the runtime
    enforces 120 s, so a projection built from the defaults advertises what the pilot
    refuses (P-20)."""
    default = runtime_profile({})
    assert default.capability.video.max_seconds == 120
    published = pm.PublishedModel.model_validate(CREDIT_DOC)
    assert pm.violations(published, default) == []            # honest against 120 s
    stale = published.model_copy(update={"capability": default.capability})
    assert [v.split(":")[0] for v in pm.violations(stale, PROFILE)] == [
        "capability.video.max_seconds"]


def test_the_profile_follows_the_deployment_ceilings():
    """Oracle: advertising the pilot's 32k context when the deployment validated less."""
    small = _deployment().model_copy(update={"max_input_tokens": 20000,
                                             "max_output_tokens": 1024})
    profile = pm.serving_profile(limits=pf.DEPLOYED_LIMITS, deployment=small, serving=_serving(),
                                 parameters=pf.ACCEPTED_PARAMETERS, refused=pf.REFUSED_PARAMETERS,
                                 video_mime=pf.SERVED_VIDEO_MIME, execution_modes=pf.MODES,
                                 **pf.VIDEO_SAMPLING)
    assert (profile.capability.max_input_tokens, profile.capability.max_output_tokens) == (
        20000, 1024)


# --- failure oracles: never published ----------------------------------------
@pytest.mark.parametrize("visibility,state", [
    (Visibility.private, DeploymentState.ready_private),
    *[(Visibility.public, s) for s in DeploymentState if s is not DeploymentState.active]])
def test_a_private_or_deactivated_deployment_is_never_published(visibility, state):
    """Oracle: a private dev, proposed, draining or retired deployment in the catalog."""
    deployment = _deployment().model_copy(update={"visibility": visibility, "state": state})
    with pytest.raises(errors.NotFound):
        _project(deployment=deployment)


@pytest.mark.parametrize("overrides", [
    {"credit_card": None},
    {"regime": "legacy_usd", "usd_price": None},
    {"credit_card": v2fix.BUILDERS["rate_card_marlin.json"]().model_copy(
        update={"deployment_revision_id": v2fix.IDS.dev_deployment})},
    {"usd_price": pf._canonical_usd_row().model_copy(
        update={"model_revision": v2fix.PUBLIC_MODEL_ID})},
], ids=["no-credit-card", "no-usd-price", "card-for-another-deployment", "usd-keyed-by-spelling"])
def test_unpriced_or_mispriced_fails_closed(overrides):
    """Oracle: an unpriced model published as free, a card pinned to another revision, or
    a USD price looked up by a spelling instead of the revision (P-22)."""
    with pytest.raises(errors.InvalidRequest):
        _project(**overrides)


@pytest.mark.parametrize("patch", [
    {"parameters": tuple(sorted([*pf.ACCEPTED_PARAMETERS, "tools"])),
     "unsupported_parameters": tuple(p for p in pf.REFUSED_PARAMETERS if p != "tools")},
    {"parameters": tuple(sorted([*pf.ACCEPTED_PARAMETERS, "response_format"])),
     "unsupported_parameters": tuple(p for p in pf.REFUSED_PARAMETERS
                                     if p != "response_format")},
    {"video": pf.deployed_profile().capability.video.model_copy(update={"live_stream": True})},
    {"max_output_tokens": 4096, "max_input_tokens": 28672},
], ids=["tools", "structured-output", "live-video", "past-deployment-output"])
def test_a_capability_the_serving_revision_does_not_declare_is_refused(patch):
    """Oracle: tool calling, JSON-schema output or live video published for a serving
    revision whose capability record says no, or limits past the deployment's."""
    capability = pf.deployed_profile().capability.model_copy(update=patch)
    with pytest.raises(errors.InvalidRequest):
        _project(capability=capability)


def test_a_legacy_regime_projection_shows_no_credit_rate():
    """Oracle: the console showing a CREDIT rate while admission charges USD."""
    legacy = pm.PublishedModel.model_validate(LEGACY_DOC)
    assert legacy.pricing.regime is AccountingRegime.legacy_usd and legacy.pricing.credit is None
    assert _project(regime="legacy_usd").pricing.credit is None


@pytest.mark.parametrize("case", CASES["refusals"], ids=lambda c: c["name"])
def test_a_malformed_or_dishonest_record_does_not_parse(case):
    """Oracles: ZDR/trace-off-as-deletion claims, unknown video/tool features, USD parsed
    as CREDIT (and back), non-canonical or numeric amounts, unpriced regimes, spellings as
    USD keys, foreign aliases, coerced caps/flags, missing fields, v1 payloads."""
    with pytest.raises(ValidationError):
        pm.PublishedModel.model_validate(pf.apply_patches(CREDIT_DOC, case["patches"]))


@pytest.mark.parametrize("case", CASES["violations"], ids=lambda c: c["name"])
def test_the_profile_check_names_exactly_what_is_overclaimed(case):
    """Oracle: a projection advertising a cap, parameter, MIME type, live video, sampling
    rate or retention figure the serving profile refuses - and no false alarm for an
    honest understatement."""
    record = pm.PublishedModel.model_validate(pf.apply_patches(CREDIT_DOC, case["patches"]))
    assert [v.split(":")[0] for v in pm.violations(record, PROFILE)] == case["expected"]


def test_the_fixtures_themselves_are_honest():
    for doc in (CREDIT_DOC, LEGACY_DOC):
        assert pm.violations(pm.PublishedModel.model_validate(doc), PROFILE) == []


def test_every_field_is_covered_by_a_profile_rule():
    """Oracle: a field added to the capability and never compared, so it can overclaim."""
    other = {"schema_version"}
    assert set(pm.Capability.model_fields) == (set(pm.CAPS) | set(pm.SUBSETS) | other
                                               | {"unsupported_parameters", "video"})
    assert set(pm.VideoInput.model_fields) == (set(pm.VIDEO_CAPS) | set(pm.VIDEO_EXACT) | other
                                               | {"mime_types", "live_stream"})


# --- resolution and pricing, once --------------------------------------------
@pytest.mark.parametrize("requested", ["", "@2026-09-01", "a@b@c", "nemostation/marlin 2b",
                                       "x" * 201, "nemostation/marlin-2b@" + "9" * 65, None])
def test_a_malformed_name_is_not_found(requested):
    """Oracle: a malformed name answered differently from an unknown one (R70)."""
    with pytest.raises(errors.NotFound):
        pm.split_model(requested)


def _second_revision(label: str, listing_version: int) -> pm.PublishedModel:
    base = pm.PublishedModel.model_validate(CREDIT_DOC)
    serving = base.serving.model_copy(update={"revision_label": label})
    revision = f"{base.id}@{label}"
    usd = base.pricing.legacy_usd.model_copy(update={"model_revision": revision})
    return pm.PublishedModel.model_validate(
        {**CREDIT_DOC, "model_revision": revision, "listing_version": listing_version,
         "aliases": sorted({base.id, revision}), "serving": serving.model_dump(mode="json"),
         "pricing": {**CREDIT_DOC["pricing"], "legacy_usd": usd.model_dump(mode="json")}})


def test_the_unlabelled_id_takes_the_highest_listing_and_a_pin_its_own_revision():
    """Oracle: an alias that floats to an older listing, or a pin that floats at all
    (0008 `order by version desc`)."""
    old = pm.PublishedModel.model_validate(CREDIT_DOC)
    new = _second_revision("2026-10-01", 2)
    old_pinned = old.model_copy(update={"aliases": (old.model_revision,)})
    assert pm.resolve("nemostation/marlin-2b", [old_pinned, new]) is new
    assert pm.resolve(v2fix.REQUESTED_MODEL, [old_pinned, new]) is old_pinned
    assert pm.catalog_problems([old_pinned, new]) == []
    # the floating id advertised on the older record resolves elsewhere: a catalog problem
    assert pm.catalog_problems([old, new]) == [
        "nemostation/marlin-2b@2026-09-01: alias 'nemostation/marlin-2b' resolves to "
        "nemostation/marlin-2b@2026-10-01"]
    assert pm.catalog_problems([old, old]) != []


def test_pricing_preserves_the_requested_string_beside_the_canonical_revision():
    """Oracle: the requested spelling lost, or replaced by the canonical one, on the pin."""
    credit = pm.PublishedModel.model_validate(CREDIT_DOC)
    pin = pm.price("nemostation/marlin-2b", [credit])
    assert (pin.requested_model, pin.model_revision) == ("nemostation/marlin-2b",
                                                          v2fix.REQUESTED_MODEL)
    assert (pin.rate_card_version, pin.price_version) == (v2fix.RATE_CARD_VERSION, None)
    legacy = pm.price("nemostation/marlin-2b", [pm.PublishedModel.model_validate(LEGACY_DOC)])
    assert (legacy.rate_card_version, legacy.price_version) == (
        None, "pv_marlin2b_usd_2026_09_r1")


def test_the_two_price_identities_never_convert():
    """Oracle: a CREDIT rate derived from USD (or the reverse): the units are distinct
    types, and a pin carrying both identities, or neither, does not construct."""
    credit = pm.PublishedModel.model_validate(CREDIT_DOC).pricing
    assert isinstance(credit.credit.input_rate_per_million, Credit)
    assert isinstance(credit.legacy_usd.input_rate_per_million, Usd)
    with pytest.raises(TypeError):
        credit.credit.input_rate_per_million + credit.legacy_usd.input_rate_per_million
    pin = pm.price(v2fix.REQUESTED_MODEL, [pm.PublishedModel.model_validate(CREDIT_DOC)])
    for update in ({"price_version": "pv_x"}, {"rate_card_version": None}):
        with pytest.raises(ValidationError):
            pm.PricedResolution.model_validate({**pin.model_dump(mode="json"), **update})


# --- P-22: every existing alias, before and after -------------------------------
ROWS = {row["price_version"]: row for row in ALIASES["hosted_usd_rows"]}


@pytest.mark.parametrize("case", ALIASES["cases"], ids=lambda c: c["requested"])
def test_no_historical_resolution_or_price_changes(case):
    """Oracle: an alias that resolved (or was refused) on the pilot resolving differently,
    or pricing at other rates, under the resolve-then-price rule. `before` is the recorded
    outcome on the hosted pilot at bda1586, where the USD lookup keyed the literal string."""
    before = case["before"]
    for regime in ("credit", "legacy_usd"):
        after = case[regime]
        assert after == pf._priced(case["requested"], pm.PublishedModel.model_validate(
            CREDIT_DOC if regime == "credit" else LEGACY_DOC))
        if "refused" in before:
            assert after == before, f"{case['requested']} is newly resolvable in {regime}"
            continue
        assert after["deployment_revision_id"] == before["deployment_revision_id"]
        assert after["requested_model"] == case["requested"]
        assert after["model_revision"] == v2fix.REQUESTED_MODEL
    if "refused" not in before:
        # the literal lookup keyed this very spelling; the canonical row prices the same
        old, new = ROWS[before["price_version"]], ROWS[case["legacy_usd"]["price_version"]]
        assert old["model_revision"] == case["requested"]
        assert new["model_revision"] == v2fix.REQUESTED_MODEL
        for field in ("input_rate_per_million", "output_rate_per_million",
                      "token_rules_version"):
            assert new[field] == old[field]


def _model_strings_in(paths: list[str]) -> set[str]:
    pattern = re.compile(r'"(?:model|model_revision|requested_model)":\s*"([^"]+)"')
    return {m for path in paths for m in pattern.findall((REPO / path).read_text())}


def test_the_table_covers_every_model_string_in_fixtures_and_results():
    """Oracle: a client, fixture or result spelling nobody checked for compatibility."""
    tracked = subprocess.run(["git", "ls-files", "models/marlin2b/results",
                              "apps/infrx-api/infrx/contracts/fixtures",
                              "apps/app/lib/contracts/fixtures"],
                             cwd=REPO, capture_output=True, text=True, check=True).stdout.split()
    seen = _model_strings_in([p for p in tracked if p.endswith((".json", ".jsonl"))])
    seen |= _model_strings_in(["research/plan/evidence/e/E4B-endpoint.md"])
    seed = (REPO / "apps/app/supabase/migrations/0002_seed_models.sql").read_text()
    seen |= set(re.findall(r"^\s*\('([^']+)', '[^']+', '[^']+',$", seed, re.M))
    seen.add(config.Settings().model_id)
    tabled = {case["requested"] for case in ALIASES["cases"]}
    assert seen, "found no model strings: the scan is broken"
    assert seen - {"claude-opus-5"} <= tabled, sorted(seen - tabled)


# --- the TypeScript twin states the same rules --------------------------------
@pytest.mark.parametrize("name,values", [
    ("STORED_CONTENT", pm.STORED_CONTENT), ("CAPS", pm.CAPS), ("SUBSETS", pm.SUBSETS),
    ("VIDEO_CAPS", pm.VIDEO_CAPS), ("VIDEO_EXACT", pm.VIDEO_EXACT)])
def test_the_console_twin_declares_the_same_rule_tables(name, values):
    """Oracle: a profile rule or stored-content category present in one language only."""
    assert ts_string_array(TS, name) == list(values)


def test_the_console_twin_uses_the_same_model_grammar():
    match = re.search(r"export const MODEL_GRAMMAR = /(.+)/u;", TS)
    assert match and match.group(1) == pm.MODEL_GRAMMAR.pattern


def test_the_g6b_minted_card_is_not_the_seeded_deployment_s_public_rate():
    """S3 F11. Oracle: `marlin_release()`'s locally computed provisional card (certify's
    `published_release`, the E4B endpoint doc) shown as the rate of the deployment the hosted
    catalog lists. It prices G6B's own deployment revision, so `project` refuses the pairing;
    the public identity is the listing's card, the seed's."""
    from infrx.operations import service
    _serving_g6b, deployment_g6b, card_g6b, requested = service.marlin_release(
        provider_org_id=v2fix.IDS.provider_org, created_at=v2fix.T0, effective_at=v2fix.T0)
    assert requested == v2fix.REQUESTED_MODEL
    assert card_g6b.rate_card_version == "rc_marlin2b_20260901T000000Z_provisional_p01"
    assert card_g6b.deployment_revision_id != _deployment().deployment_revision_id
    with pytest.raises(errors.InvalidRequest):
        _project(credit_card=card_g6b)
    published = pm.PublishedModel.model_validate(CREDIT_DOC)
    assert (published.pricing.credit.rate_card_version, published.pricing.credit.unit) == (
        v2fix.RATE_CARD_VERSION, "CREDIT")
    assert published.pricing.credit.provisional is True
