#!/usr/bin/env python3
"""r1 R32 for track G: one single-edit defect per invariant this suite claims.

Same contract *and* the same runner as `tests/contracts/mutants.py` (F2R item 9): the
list is G's, the vocabulary and the rules are shared. One mutant at a time, applied to a
**copy** of the package in a temporary directory, with the named cases run there. A
mutant that survives means the case claiming that invariant proves nothing.

G's one local need is which files to collect: collecting the whole suite for every
mutant imports FastAPI and the contracts fakes 50 times over, so `files_for` narrows the
target to the files defining the named cases. That is a `Runner` argument now.

    uv run --frozen pytest -q tests/g/test_mutants.py     # the whole list
    uv run --frozen python -m tests.g.mutants --list
    uv run --frozen python -m tests.g.mutants body_cap_removed
"""
from __future__ import annotations

import pathlib
import re
import shutil
import sys

from ..contracts import mutants as shared
from ..contracts.mutants import Mutant, Outcome, Result, Runner   # noqa: F401

API_DIR = pathlib.Path(__file__).resolve().parents[2]
PACKAGE = "infrx"
SUITE = "tests/g"

I = "gateway/routes/intake.py"
V = "gateway/routes/validate.py"
N = "gateway/routes/ingress.py"
A = "auth/context.py"
K = "auth/keys.py"                      # F1's caches: G owns the file, and the bounds
C = "gateway/routes/catalog.py"         # G1R: model resolution for a credential's audience
R = "gateway/routes/relay.py"           # G2: the acceptor, the sync wait and the SSE relay
P = "gateway/pilot.py"                  # G2: the pilot composition
OR = "observe/route.py"                 # I3B's loopback rule, which G2's /readyz reuses
ST = "contracts/fakes/state.py"         # the contract store the G2 drills run against


def _m(name, invariant, file, old, new, *cases, dies_by=(), occurrences=1) -> Mutant:
    return Mutant(name=name, invariant=invariant, file=file, old=old, new=new, cases=cases,
                  dies_by=tuple(dies_by), occurrences=occurrences)


# --- declared kill modes (F2R item 9) -------------------------------------------------
# The shared runner requires every death to be assertion-shaped or a typed `DomainError`,
# so a case that **crashes** must say which class it crashes with. Twenty-one mutants here
# do, and they are almost all one shape: the case reads the error envelope or a header out
# of a response the mutant emptied - `body["error"]["code"]`, `headers["Retry-After"]`,
# `headers["Inference-Id"]` - so the missing key IS the invariant's negation. `KeyError`
# therefore names the kill rather than hiding a broken copy. The four others are their own
# invariants stated backwards: a raise that must not happen (`malformed_row_raises_a_...`,
# `probe_exception_escapes`, `unhandled_exceptions_unwrapped`) and a stall that must not be
# possible (`stalled_peer_deadline_removed`). None of them is an exception from the mutant
# **text**: that is still a `broken_runner`, which the self-tests below prove.
MUTANTS: tuple[Mutant, ...] = (
    # --- intake: bounded and deadlined before the parse -----------------------
    _m("body_cap_removed", "the body is bounded before it is parsed",
       I, "                if total > max_bytes:", "                if False:",
       "test_media_sec__an_oversized_body_is_refused_before_it_is_parsed",
       "test_media_sec__a_chunked_body_is_bounded_by_the_running_total",
       "test_media_sec__the_cap_counts_the_whole_stream_not_one_chunk",
       "test_media_sec__the_cap_is_an_upper_bound_not_an_off_by_one"),
    _m("cap_counts_one_chunk", "the cap counts the whole stream, not one chunk",
       I, "                total += len(chunk)", "                total = len(chunk)",
       "test_media_sec__the_cap_counts_the_whole_stream_not_one_chunk"),
    _m("cap_is_off_by_one", "the cap is an upper bound",
       I, "                if total > max_bytes:", "                if total >= max_bytes:",
       "test_media_sec__the_cap_is_an_upper_bound_not_an_off_by_one"),
    # --- review r1 item 1: the parser's failures are ours to classify ----------
    _m("recursion_error_escapes", "deep nesting is a 400, not a 500",
       I, "    except (ValueError, RecursionError):", "    except ValueError:",
       "test_media_sec__a_parser_hostile_body_is_a_400_not_a_500"),
    _m("json_constants_accepted", "NaN and Infinity are not numbers JSON has",
       I, "        body = json.loads(text, parse_constant=_no_constants,\n"
          "                          parse_int=_bounded_int, parse_float=_bounded_float)",
       "        body = json.loads(text, parse_int=_bounded_int, parse_float=_bounded_float)",
       "test_media_sec__the_parser_itself_refuses_json_that_is_not_json"),
    # --- review r1 item 2: the error path cannot raise -------------------------
    _m("param_echoed_unfiltered", "only a parameter-shaped param is echoed",
       I, "    return param if isinstance(param, str) and SAFE_PARAM.fullmatch(param) else None",
       "    return param if isinstance(param, str) else None",
       "test_f_base__an_unrenderable_param_is_still_an_envelope",
       "test_f_base__a_caller_string_is_never_reflected_or_logged"),
    _m("param_never_echoed", "a parameter name that is one is still named",
       I, "    return param if isinstance(param, str) and SAFE_PARAM.fullmatch(param) else None",
       "    return None", "test_f_base__a_parameter_name_that_is_a_name_is_still_echoed", dies_by=("KeyError",)),
    _m("internal_code_reaches_http_status", "an internal-only code is answered as internal_error",
       I, "        public = error if error.code in errors.HTTP_ERRORS else errors.InternalError()",
       "        public = error",
       "test_f_base__an_internal_only_code_escaping_a_route_is_a_500_envelope"),
    # The invariant is the ABSENCE of an exception - the envelope of last resort renders
    # whatever the request carried - so the only way to break it is to let the raise out,
    # and the only honest kill is that raise (F2R item 9: declared, not assumed).
    _m("envelope_render_unprotected", "rendering the envelope cannot fail",
       I, "    except Exception:\n"
          '        log.exception("the error envelope could not be rendered for request %s", request_id)',
       "    except KeyboardInterrupt:\n        raise",
       "test_f_base__the_envelope_of_last_resort",
       dies_by=("PydanticSerializationError",)),
    # --- review r1 item 3: structure, liveness and identity-first -------------
    _m("messages_unbounded", "the message count is bounded",
       V, "    if len(messages) > MAX_MESSAGES:", "    if False:",
       "test_media_sec__the_message_count_is_bounded"),
    _m("parts_unbounded", "the parts per message are bounded",
       V, "        if len(content) > MAX_PARTS_PER_MESSAGE:", "        if False:",
       "test_media_sec__the_parts_per_message_are_bounded"),
    _m("text_unbounded", "the total text is bounded",
       V, "            if text_chars > MAX_TEXT_CODEPOINTS:\n"
          "                raise errors.InvalidRequest(f\"at most {MAX_TEXT_CODEPOINTS} characters of text\",\n"
          "                                            param=\"messages\")\n"
          "            continue",
       "            continue", "test_media_sec__the_total_text_is_bounded"),
    _m("url_unbounded", "a public url is bounded",
       V, "    if len(source) > MAX_URL_CHARS:", "    if False:",
       "test_media_sec__a_public_url_is_bounded", dies_by=("KeyError",)),
    _m("identity_after_the_body", "identity is resolved before the body is read or parsed",
       N, "        auth = await self.auth.context(request)\n        intake.check_content_type(request)",
       "        intake.check_content_type(request)",
       "test_dur_rls__an_unauthenticated_caller_never_makes_us_buffer",
       "test_dur_rls__identity_is_checked_before_the_body_is_parsed"),
    _m("unstorable_text_accepted", "text the database cannot store is refused",
       V, "    try:\n        text.encode()\n    except UnicodeEncodeError:",
       "    try:\n        text.encode(errors=\"replace\")\n    except UnicodeEncodeError:",
       "test_media_sec__text_the_database_cannot_store_is_refused"),
    _m("nul_accepted", "a NUL cannot be stored and is refused",
       V, '    if "\\x00" in text:', "    if False:",
       "test_media_sec__text_the_database_cannot_store_is_refused"),
    _m("unhashable_role_crashes", "a non-string role is refused before the set lookup",
       V, "        if not isinstance(role, str) or role not in ROLES:", "        if role not in ROLES:",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    # R-3 retires no_skew_margin/skew_margin_added: DB-clock clamping replaces the
    # gateway tolerance heuristic. The JobStore deadline mutant proves the clamp.
    _m("admission_ignores_db_deadline", "the DB clock clamps a gateway ahead of it",
       "contracts/fakes/state.py", '            return request.model_copy(update={"deadline_at": ceiling})',
       "            return request",
       "test_dur_admit__the_deadline_survives_clock_skew"),
    _m("deadline_shortens_generation", "the ingress offers the full bounded generation budget",
       V, "                                                 + budgets.generation_s)),",
       "                                                 + budgets.generation_s / 2)),",
       "test_dur_admit__the_ingress_deadline_is_one_the_store_can_keep"),
    # --- review r1 item 6 and the nonblocking list ----------------------------
    _m("null_parameter_is_absent", "a null parameter is refused, not treated as absent",
       V, "            if body[name] is None:", "            if False:",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("seed_unranged", "seed is 0..2**63-1",
       V, "        if seed is not None and not 0 <= seed <= MAX_SEED:", "        if False:",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("unknown_model_resolves_the_default", "a name resolves itself, never a fallback",
       V, "        resolved = await resolve(self.catalog, auth, model)",
       "        resolved = await resolve(self.catalog, auth, self.rt.settings.model_id)",
       "test_f_base__an_unserved_model_is_refused_without_naming_what_is_served",
       "test_split_contract__the_operator_seeded_catalog_serves_without_lab",
       dies_by=("KeyError",)),
    _m("model_length_unbounded", "a model name is bounded",
       V, "        if len(model) > MAX_MODEL_CHARS:", "        if False:",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code",
       "test_media_sec__a_megabyte_model_name_never_reaches_the_store"),
    _m("prefer_matched_as_a_substring", "Prefer is parsed as tokens",
       V, '    tokens = {token.strip().lower().split("=")[0]\n'
          '              for token in (headers.get("prefer") or "").split(",")}',
       '    tokens = (headers.get("prefer") or "").lower()',
       "test_f_base__prefer_is_parsed_as_tokens_not_as_a_substring"),
    _m("stream_and_async_both_accepted", "one response shape per request",
       V, "        if stream:\n            # One response shape per request", "        if False:\n            # One response shape per request",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("upload_form_unchecked", "an upload reference is infrx-upload:upl_…",
       V, "        if not ids.UPLOAD_HANDLE_RE.fullmatch(handle):", "        if False:",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("data_url_form_unchecked", "an inline video is data:<mime>;base64,",
       V, "    if match is None:", "    if False:",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("control_characters_in_urls", "a url carries no control characters",
       V, "    if UNSAFE_IN_URL.search(source):", "    if False:",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("content_type_unchecked", "the body is application/json",
       I, "    if declared != JSON_MEDIA_TYPE:", "    if False:",
       "test_f_base__a_body_that_is_not_json_is_refused", dies_by=("KeyError",)),
    _m("digest_over_the_raw_bytes", "the payload digest is canonical",
       V, "    if not media:\n        return \"sha256:\" + hashlib.sha256(canonical_bytes(body)).hexdigest()",
       "    if not media:\n        return \"sha256:\" + hashlib.sha256(repr(body).encode()).hexdigest()",
       "test_dur_admit__the_payload_digest_is_canonical"),
    _m("trace_default_is_full", "the trace policy defaults to off",
       V, "    return ConsentSnapshot(org_id=org_id, consent_version=0, trace_mode=TraceMode.off,",
       "    return ConsentSnapshot(org_id=org_id, consent_version=0, trace_mode=TraceMode.full,",
       "test_trace_tenant__the_trace_policy_defaults_to_off"),
    _m("consent_source_ignored", "an injected consent source is used",
       V, "        self.consent_for = consent_for or off_mode_policy",
       "        self.consent_for = off_mode_policy",
       "test_trace_tenant__an_injected_consent_source_is_used_as_given"),
    _m("a_second_clock", "there is one clock, and it is injected",
       V, "        return datetime.fromtimestamp(self.rt.clock(), timezone.utc)",
       "        return datetime.now(timezone.utc)",
       "test_f_base__there_is_no_second_clock"),
    _m("key_ttl_ignored", "a cached key expires and is looked up again",
       K, "        if hit is None or hit[0] < now():", "        if hit is None:",
       "test_dur_rls__a_cached_key_expires_and_is_looked_up_again",
       "test_dur_rls__a_miss_expires_on_its_own_shorter_ttl",
       "test_dur_rls__a_revocation_takes_effect_when_the_cache_expires"),
    _m("key_id_not_passed_to_the_store", "the key the store rechecks is the caller's key",
       A, "        return AuthContextV2(audience=audience, org_id=org_id, key_id=key_id, principal=key_id,",
       "        return AuthContextV2(audience=audience, org_id=org_id, key_id=org_id, principal=key_id,",
       "test_dur_rls__admission_rechecks_revocation_on_the_identity_we_pass",
       "test_dur_rls__a_known_key_becomes_an_auth_context",
       "test_api_auth__a_provider_dev_key_never_spends_a_consumer_wallet"),
    _m("orgless_row_becomes_an_identity", "an identity row names a tenant",
       A, "    if not org_id or not key_id:", "    if False:",
       "test_dur_rls__an_identity_row_without_a_tenant_is_not_an_identity"),
    _m("malformed_row_raises_a_validation_error", "a malformed identity row is a typed failure",
       A, "    except ValueError:\n        raise errors.InternalError(",
       "    except KeyboardInterrupt:\n        raise errors.InternalError(",
       "test_dur_rls__a_malformed_identity_row_fails_closed_without_a_trace", dies_by=("ValidationError",)),
    # --- review r1 item 7: FastAPI's own answers -------------------------------
    # Without the handler Starlette's own 404 body has no `error` key, so the case reads
    # one that is not there. Declared: the missing envelope IS the defect.
    _m("http_exceptions_unwrapped", "404 and a wrong method are envelopes",
       N, "    app.add_exception_handler(StarletteHTTPException, http_exception)", "    pass",
       "test_f_base__an_unknown_path_and_a_wrong_method_are_envelopes",
       dies_by=("KeyError",)),
    _m("unhandled_exceptions_unwrapped", "an error outside a route is an envelope",
       N, "    app.add_exception_handler(Exception, unhandled)", "    pass",
       "test_f_base__an_unhandled_error_outside_a_route_is_still_an_envelope", dies_by=("JSONDecodeError",)),
    _m("slow_body_deadline_removed", "a slow body cannot outlast INTAKE_TIMEOUT_S",
       I, "                if clock() > deadline:", "                if False:",
       "test_media_sec__a_slow_body_hits_the_intake_deadline"),
    _m("stalled_peer_deadline_removed", "a peer that sends nothing is still deadlined",
       I, "        async with asyncio.timeout(timeout_s):", "        async with asyncio.timeout(None):",
       "test_media_sec__a_peer_that_sends_nothing_hits_the_intake_deadline", dies_by=("TimeoutError",)),
    _m("non_object_body_accepted", "the body must be a JSON object",
       I, "    if not isinstance(body, dict):", "    if False:",
       "test_media_sec__a_non_object_body_is_refused"),
    # --- the envelope ---------------------------------------------------------
    _m("error_omits_the_request_id_header", "every answer names its request",
       I, "    headers = {wire.HEADER_INFERENCE_ID: request_id}", "    headers = {}",
       "test_f_base__every_answer_carries_a_freshly_minted_inference_id", dies_by=("KeyError",)),
    _m("retry_after_header_dropped", "429/503 carry retry guidance",
       I, "        if public.retry_after_s is not None:", "        if False:",
       "test_f_base__retry_guidance_rides_with_every_429_and_503",
       "test_dur_cap__denied_capacity_is_retryable_and_the_retry_is_admitted_once",
       "test_dur_cap__the_headless_client_retries_denied_capacity_with_its_own_key",
       dies_by=("KeyError",)),
    _m("unhandled_exception_text_leaks", "an unexpected exception never reaches the client",
       I, "            except Exception:\n"
          "                log.exception(\"%s: unhandled error on request %s\", request.url.path, request_id)\n"
          "                return response(errors.InternalError(), request_id)",
       "            except Exception as leaked:\n"
       "                return JSONResponse({\"error\": {\"message\": str(leaked),\n"
       "                                               \"type\": \"server_error\",\n"
       "                                               \"code\": \"internal_error\"}},\n"
       "                                    status_code=500)",
       "test_f_base__an_unexpected_exception_never_reaches_the_client",
       "test_f_base__every_failure_is_a_fixed_envelope_with_no_leak"),
    # --- identity ------------------------------------------------------------
    # Dropping the refusal returns `None` where the cases expect an `AuthContext`, so they
    # die reading `.org_id` off it. Declared, because "there is no context at all" is
    # exactly what an accepted anonymous request looks like from the caller's side.
    _m("anonymous_request_accepted", "no accepted request without tenant identity",
       A, '            raise errors.InvalidApiKey("the request carries no per-organization identity")',
       "            pass",
       "test_dur_rls__an_unconfigured_gateway_accepts_no_request",
       "test_dur_rls__a_configuration_with_no_identity_source_accepts_nothing",
       "test_dur_rls__the_shared_legacy_key_is_not_an_identity",
       dies_by=("AttributeError",)),
    _m("unreachable_identity_source_is_a_401", "an unreachable identity source is retryable",
       A, '            raise errors.DependencyUnavailable("the api_keys identity source is unreachable")',
       '            raise errors.InvalidApiKey("the api_keys identity source is unreachable")',
       "test_dur_rls__an_unusable_key_is_refused_with_a_stable_code",
       "test_dur_rls__a_cached_key_survives_an_unreachable_identity_source"),
    _m("pilot_accepts_a_shared_key", "pilot refuses a shared key and a missing identity source",
       A, "        if missing or forbidden:", "        if False:",
       "test_dur_rls__pilot_refuses_to_build_a_resolver_it_cannot_trust"),
    _m("key_cache_unbounded", "the caller-supplied key hash cannot grow a cache without bound",
       K, "    while len(cache) > cap:", "    while False:",
       "test_dur_rls__the_bounded_key_and_miss_caches_are_preserved"),
    # Misses live in their own cache with its own cap; sharing one cache is exactly how
    # a flood of random keys evicts the real ones. (An earlier mutant here - swapping the
    # `pop` target - was equivalent: for a miss the original already pops `keys`.)
    _m("one_cache_for_hits_and_misses", "a flood of misses cannot evict a real key",
       K, "        put(*((self.keys, h, hit, s.key_cache_max) if rows else (self.misses, h, hit, s.miss_cache_max)))",
       "        put(self.keys, h, hit, s.key_cache_max)",
       "test_dur_rls__a_flood_of_misses_cannot_evict_a_real_key"),
    _m("legacy_comparison_is_not_constant_time", "the legacy key comparison is timing-safe",
       K, "if s.legacy_key and hmac.compare_digest(token.encode(), s.legacy_key.encode()):",
       "if s.legacy_key and token == s.legacy_key:",
       "test_dur_rls__the_legacy_key_comparison_is_still_constant_time"),
    # --- shape and parameters ------------------------------------------------
    _m("unsupported_parameters_ignored", "the parameter set is closed and explicit",
       V, "            if name in UNSUPPORTED or name not in SUPPORTED:", "            if False:",
       "test_f_base__an_unsupported_parameter_is_named_and_refused",
       "test_api_auth__no_body_field_or_header_can_name_a_wallet_rate_or_policy",
       "test_api_auth__refusals_leave_no_hold_job_or_journal_reservation"),
    _m("n_greater_than_one_accepted", "only n=1 is supported",
       V, "        if count is not None and count != 1:", "        if False:",
       "test_f_base__only_n_equals_one_is_supported", dies_by=("KeyError",)),
    _m("output_ceiling_unchecked", "the output ceiling is 1..MAX_OUTPUT_TOKENS",
       V, "        if not 1 <= output <= ceiling:", "        if False:",
       "test_f_base__the_output_ceiling_is_range_checked"),
    # A ceiling pair that does not fit the context window is refused by the store (R55), so
    # the honest kill is that typed refusal rather than an assertion about a number.
    _m("input_ceiling_ignores_the_output", "the input ceiling is the context limit minus output",
       V, "        return min(deployment.max_input_tokens, self.limits.max_context_tokens - output), output",
       "        return min(deployment.max_input_tokens, self.limits.max_context_tokens), output",
       "test_split_contract__the_ceilings_are_the_deployments_own"),
    _m("deadline_beyond_the_budgets", "the deadline is one the store can keep (R29)",
       V, "                                                 + budgets.generation_s)),",
       "                                                 + 2 * budgets.generation_s)),",
       "test_f_base__there_is_no_second_clock",
       "test_dur_admit__an_async_request_gets_the_async_queue_budget"),
    _m("prefer_async_ignored", "Prefer: respond-async selects the async queue budget",
       V, "    if wire.PREFER_RESPOND_ASYNC in tokens:", "    if False:",
       "test_f_base__the_execution_mode_follows_stream_and_prefer",
       "test_dur_admit__an_async_request_gets_the_async_queue_budget"),
    _m("stream_mode_ignored", "a streaming request is not a sync request",
       V, "    return ExecutionMode.stream if stream else ExecutionMode.sync",
       "    return ExecutionMode.sync",
       "test_f_base__the_execution_mode_follows_stream_and_prefer"),
    _m("empty_messages_accepted", "messages is a non-empty array",
       V, "    if not isinstance(messages, list) or not messages:",
       "    if not isinstance(messages, list):",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    # --- r1 R58: the message allow-list ---------------------------------------
    _m("message_keys_not_an_allow_list", "a message is exactly {role, content} (R58)",
       V, "        if not isinstance(message, dict) or set(message) != MESSAGE_KEYS:",
       "        if not isinstance(message, dict):",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("unknown_role_accepted", "a message names a known role",
       V, "        if not isinstance(role, str) or role not in ROLES:", "        if False:",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("non_object_part_accepted", "a content part is an object (R58)",
       V, "            if not isinstance(part, dict):", "            if False:",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("text_part_keys_not_an_allow_list", "a text part is exactly {type, text} (R58)",
       V, '                if set(part) != TEXT_PART_KEYS or not isinstance(part["text"], str):',
       '                if not isinstance(part.get("text"), str):',
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("video_part_keys_not_an_allow_list", "a video part is exactly {type, video_url} (R58)",
       V, "                if set(part) != VIDEO_PART_KEYS:", "                if False:",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("part_type_case_insensitive", "part types are matched exactly (R58)",
       V, "            if kind == TEXT_TYPE:", "            if str(kind).lower() == TEXT_TYPE:",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("video_ref_keys_not_an_allow_list", "a video part carries exactly {url} (R58)",
       V, "    if not isinstance(ref, dict) or set(ref) != VIDEO_REF_KEYS:",
       "    if not isinstance(ref, dict):",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("foreign_part_type_accepted", "content parts are text or video only",
       V, '                raise errors.UnsupportedMedia(f"content parts are {TEXT_TYPE} and {VIDEO_TYPE}",\n'
          '                                              param="messages")',
       "                pass",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("media_scheme_unchecked", "a media source is http(s), data: or an upload handle",
       V, "    if not source.lower().startswith(HTTP_SCHEMES):", "    if False:",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("second_video_accepted", "one video per request",
       V, "                if videos > MAX_VIDEO_PARTS:", "                if False:",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("parts_reordered", "normalized parts keep the caller's order (R58)",
       V, "    return tuple(messages)",
       '    return tuple({**m, "content": list(reversed(m["content"]))}\n'
       '                 if isinstance(m.get("content"), list) else m for m in messages)',
       "test_media_sec__accepted_messages_keep_their_parts_in_order"),
    # --- sampling parameters (types and ranges, so no engine 400 is absorbed) --
    _m("stop_bounds_unchecked", "each stop sequence is bounded and non-empty",
       V, "        if not isinstance(item, str) or not item or len(item) > MAX_STOP_CHARS:",
       "        if False:", "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("presence_penalty_unranged", "presence_penalty is ranged at ingress",
       V, '        _number(body, "presence_penalty", -2.0, 2.0)', "        pass",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("frequency_penalty_untyped", "frequency_penalty is typed at ingress",
       V, '        _number(body, "frequency_penalty", -2.0, 2.0)', "        pass",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code"),
    _m("number_range_unchecked", "a sampling range is a range",
       V, "    if not low <= value <= high:", "    if False:",
       "test_media_sec__a_malformed_shape_is_refused_with_a_stable_code",
       "test_media_sec__a_number_json_does_not_have_is_refused"),
    _m("idempotency_key_unbounded", "the idempotency key is bounded",
       V, "    if key is not None and (not key or len(key) > MAX_IDEMPOTENCY_KEY_CHARS):",
       "    if False:", "test_f_base__an_over_long_idempotency_key_is_refused", dies_by=("KeyError",)),
    # --- startup, readiness and ordering -------------------------------------
    _m("pilot_starts_unreachable", "pilot refuses to start with an unreachable component",
       N, '    if rt.mode == "pilot" and unavailable:', "    if False:",
       "test_f_base__pilot_refuses_to_start_when_a_component_is_unreachable"),
    _m("missing_probe_counts_as_ok", "a missing probe is not a passing probe",
       N, "            state[name] = OK if probe is not None and probe() else UNAVAILABLE",
       "            state[name] = OK if probe is None or probe() else UNAVAILABLE",
       "test_f_base__pilot_refuses_to_start_when_a_component_is_unreachable",
       "test_f_base__dev_starts_with_unreachable_components_and_says_so"),
    _m("readiness_is_public", "readiness answers a direct loopback peer only (G2 item 5)",
       N, "        if not is_direct_loopback(request):", "        if False:",
       "test_dur_rls__readiness_is_protected"),
    _m("health_explains_components", "public health is generic",
       N, '        return JSONResponse({"status": OK})',
       '        return JSONResponse({"status": OK, "components": component_state(deps.checks)})',
       "test_f_base__public_health_is_generic"),
    _m("success_omits_the_inference_id", "a success answer names its request too",
       N, "        accepted.headers.setdefault(wire.HEADER_INFERENCE_ID, request_id)", "        pass",
       "test_f_base__every_answer_carries_a_freshly_minted_inference_id", dies_by=("KeyError",)),
    _m("missing_acceptor_is_not_honest", "nothing is accepted before durable acceptance exists",
       N, "        if deps.accept is None:", "        if False:",
       "test_f_base__every_failure_is_a_fixed_envelope_with_no_leak"),
    # --- review r2 B1: refuse before parsing, bound concurrency, spare the payload ---
    _m("structure_not_counted_before_the_parse", "hostile structure is refused before parsing",
       I, "    if sum(text.count(opener) for opener in OPENERS) > max_openers:", "    if False:",
       "test_media_sec__hostile_structure_is_refused_without_parsing_it"),
    _m("opener_cap_counts_only_braces", "both openers are counted",
       I, 'OPENERS = ("{", "[")', 'OPENERS = ("{",)',
       "test_media_sec__hostile_structure_is_refused_without_parsing_it"),
    _m("opener_cap_excludes_text", "braces inside text are text",
       V, "MAX_OPENERS = STRUCTURE_OPENERS + MAX_TEXT_CODEPOINTS", "MAX_OPENERS = STRUCTURE_OPENERS",
       "test_media_sec__a_legitimate_body_at_the_opener_cap_is_still_parsed"),
    _m("large_bodies_unbounded", "at most two large bodies are in flight",
       I, "        if self.slots.in_flight >= self.slots.limit:", "        if False:",
       "test_media_sec__at_most_two_large_bodies_are_in_flight"),
    _m("large_body_slot_never_claimed", "a large body claims a slot",
       I, "        if self.held or total <= self.slots.threshold:",
       "        if self.held or total <= 2 ** 40:",
       "test_media_sec__at_most_two_large_bodies_are_in_flight"),
    _m("large_body_slot_never_released", "a slot is released on every path",
       I, "            self.slots.in_flight -= 1\n            self.held = False",
       "            self.held = False",
       "test_media_sec__a_large_body_slot_is_released_on_every_path",
       "test_media_sec__at_most_two_large_bodies_are_in_flight"),
    _m("declared_length_ignored_for_slots", "a declared large body claims its slot early",
       I, "        if declared.isascii() and declared.isdigit() and len(declared) <= 19:\n            large.account(int(declared))",
       "        pass",
       "test_media_sec__a_declared_large_body_claims_its_slot_before_it_is_read"),
    _m("payload_scanned_byte_by_byte", "no per-byte Python work touches a media payload",
       V, "    if source[:len(DATA_PREFIX)].lower() == DATA_PREFIX:\n"
          "        check_data_url(source, allowed_mime)\n"
          "        return source, True",
       "    if source[:len(DATA_PREFIX)].lower() == DATA_PREFIX:\n"
          "        storable(source, \"messages\")\n"
          "        check_data_url(source, allowed_mime)\n"
          "        return source, True",
       "test_media_sec__no_per_byte_python_work_touches_a_media_payload"),
    _m("digest_reserialises_the_payload", "the digest covers media by hash, not by value",
       V, "    if not media:\n        return \"sha256:\" + hashlib.sha256(canonical_bytes(body)).hexdigest()",
       "    return \"sha256:\" + hashlib.sha256(canonical_bytes(body)).hexdigest()\n"
       "    if not media:\n        pass",
       "test_media_sec__no_per_byte_python_work_touches_a_media_payload"),
    _m("media_token_ignores_the_payload", "one byte of the payload changes the digest",
       V, "                    media[source] = MEDIA_TOKEN + hashlib.sha256(source.encode()).hexdigest()",
       "                    media[source] = MEDIA_TOKEN",
       "test_dur_admit__the_payload_digest_covers_the_media_payload_by_hash"),
    # --- review r2 B2: the cap is code points, in every form -----------------------
    _m("text_cap_in_bytes", "the text cap counts code points, not bytes",
       V, "            text_chars += len(storable(content, \"messages\"))",
       "            text_chars += len(storable(content, \"messages\").encode())",
       "test_media_sec__text_within_the_code_point_cap_is_accepted_in_every_form"),
    _m("text_cap_off_by_one", "the text cap is exact",
       V, "            if text_chars > MAX_TEXT_CODEPOINTS:", "            if text_chars > MAX_TEXT_CODEPOINTS + 1:",
       "test_media_sec__one_code_point_past_the_cap_is_refused", occurrences=2),
    _m("text_cap_off_for_text_parts", "the cap counts text parts too",
       V, "                text_chars += len(storable(part[\"text\"], \"messages\"))",
       "                storable(part[\"text\"], \"messages\")",
       "test_media_sec__the_text_cap_counts_across_parts_and_messages"),
    _m("url_cap_off_by_one", "the url cap is exact",
       V, "    if len(source) > MAX_URL_CHARS:", "    if len(source) > MAX_URL_CHARS + 1:",
       "test_media_sec__the_url_cap_is_exact"),
    # --- review r2 B3 and the same-pass list ---------------------------------------
    _m("max_completion_tokens_ignored", "max_completion_tokens alone is the ceiling",
       V, "        output = requested if requested is not None else alternative",
       "        output = requested",
       "test_f_base__max_completion_tokens_alone_is_the_output_ceiling"),
    _m("omitted_model_not_mapped", "an omitted model is MODEL_ID, resolved like any name",
       V, "            return self.rt.settings.model_id", '            return "nemostation/marlin-2b"',
       "test_f_base__an_omitted_model_goes_through_the_served_map"),
    _m("deps_not_read_from_rt", "register reads its deps from the runtime",
       N, 'ingress = Ingress(rt, deps if deps is not None else getattr(rt, "ingress", None))',
       "ingress = Ingress(rt, deps)",
       # G1R: default deps carry no catalog, so the ingress now refuses to register -
       # the missing runtime deps, observed as a typed startup refusal.
       "test_f_base__register_reads_its_deps_from_the_runtime", dies_by=("RuntimeMisconfigured",)),
    _m("catalog_optional", "the ingress refuses to start without a catalog",
       N, "        if self.deps.catalog is None:", "        if False:",
       "test_f_base__the_ingress_refuses_to_start_without_a_catalog"),
    _m("disconnect_not_caught", "a client disconnect is not a server error",
       I, "    except ClientDisconnect:", "    except KeyboardInterrupt:",
       "test_dur_rls__a_client_that_disconnects_mid_body_is_not_a_server_error"),
    _m("refusal_keeps_the_socket", "a refusal before the body closes the connection",
       I, '        if public.code in CLOSE_CODES:\n            headers["Connection"] = "close"',
       "        pass",
       "test_f_base__a_refusal_before_the_body_closes_the_connection", dies_by=("KeyError",)),
    _m("safe_param_length_6400", "a param name is bounded at 64 characters",
       I, 'SAFE_PARAM = re.compile(r"[A-Za-z0-9_.-]{1,64}")',
       'SAFE_PARAM = re.compile(r"[A-Za-z0-9_.-]{1,6400}")',
       "test_f_base__a_parameter_name_of_65_characters_is_not_echoed"),
    _m("request_id_source_trusted", "a minted id can never reach a header unchecked",
       I, "        if isinstance(minted, str) and REQUEST_ID_RE.fullmatch(minted):\n            return minted",
       "        return minted",
       "test_f_base__a_request_id_source_that_misbehaves_never_reaches_a_header"),
    _m("last_resort_without_the_request_id", "the last resort names the request",
       I, '        body = {"error": {**LAST_RESORT["error"], "request_id": request_id}}',
       "        body = LAST_RESORT",
       "test_f_base__the_envelope_of_last_resort"),
    _m("idempotency_key_not_storable", "an idempotency key is storable text",
       V, '        storable(key, "Idempotency-Key")', "        pass",
       "test_media_sec__an_idempotency_key_is_storable_text"),
    _m("data_url_mime_unchecked", "an inline video is a supported video type",
       V, '    if match.group("mime").lower() not in allowed_mime:', "    if False:",
       "test_media_sec__an_inline_video_must_be_a_supported_video_type", dies_by=("KeyError",)),
    _m("data_url_payload_may_be_empty", "an inline video carries a payload",
       V, "    if len(source) <= match.end():", "    if False:",
       "test_media_sec__an_inline_video_must_be_a_supported_video_type", dies_by=("KeyError",)),
    _m("url_control_only_crlf", "url hygiene covers more than CRLF",
       V, r'UNSAFE_IN_URL = re.compile(r"[\x00-\x20\x7f-\x9f\u2028\u2029@\\]")',
       r'UNSAFE_IN_URL = re.compile(r"[\r\n]")',
       "test_media_sec__a_reference_url_carries_no_smuggling_characters", dies_by=("KeyError",)),
    _m("content_type_prefix_match", "the content type is compared exactly",
       I, '    if declared != JSON_MEDIA_TYPE:', "    if not declared.startswith(JSON_MEDIA_TYPE):",
       "test_f_base__the_content_type_and_prefer_checks_are_case_insensitive"),
    _m("content_type_case_sensitive", "the content type is compared case-insensitively",
       I, '    declared = (request.headers.get("content-type") or "").split(";")[0].strip().lower()',
       '    declared = (request.headers.get("content-type") or "").split(";")[0].strip()',
       "test_f_base__the_content_type_and_prefer_checks_are_case_insensitive"),
    _m("content_type_checked_after_the_body", "the content type is checked before the read",
       N, "        intake.check_content_type(request)\n        large = self.slots.slot()",
       "        large = self.slots.slot()",
       "test_f_base__the_content_type_is_checked_before_the_body_is_read"),
    _m("prefer_case_sensitive", "Prefer is compared case-insensitively",
       V, '    tokens = {token.strip().lower().split("=")[0]',
       '    tokens = {token.strip().split("=")[0]',
       "test_f_base__the_content_type_and_prefer_checks_are_case_insensitive"),
    _m("upload_handle_not_anchored", "an upload handle is matched whole",
       V, "        if not ids.UPLOAD_HANDLE_RE.fullmatch(handle):",
       "        if not ids.UPLOAD_HANDLE_RE.match(handle):",
       "test_media_sec__an_upload_handle_is_anchored_and_exact"),
    _m("retry_hint_not_defaulted", "a 429/503 always carries retry guidance",
       I, "    elif error.code in errors.RETRY_AFTER_CODES:", "    elif False:",
       "test_f_base__retry_guidance_rides_with_every_429_and_503", dies_by=("KeyError",)),
    _m("empty_idempotency_key_accepted", "an empty idempotency key is not a key",
       V, "    if key is not None and (not key or len(key) > MAX_IDEMPOTENCY_KEY_CHARS):",
       "    if key is not None and len(key) > MAX_IDEMPOTENCY_KEY_CHARS:",
       "test_f_base__an_empty_idempotency_key_is_refused_and_absence_is_not"),
    _m("falsy_probe_is_ok", "a probe's answer has to be true",
       N, "            state[name] = OK if probe is not None and probe() else UNAVAILABLE",
       "            state[name] = OK if probe is not None and probe() is not None else UNAVAILABLE",
       "test_f_base__a_probe_that_answers_falsely_is_unavailable"),
    _m("top_p_upper_bound_open", "top_p is bounded above",
       V, '        _number(body, "top_p", 0.0, 1.0)', '        _number(body, "top_p", 0.0, 2.0)',
       "test_f_base__top_p_and_the_closed_set_are_exact_at_the_edges"),
    # --- review r3: separators, UTF-8, the payload's own checks --------------------
    _m("separators_not_counted", "one opener is not one element (r3 B1)",
       I, "    if text.count(SEPARATOR) > max_separators:", "    if False:",
       "test_media_sec__an_opener_free_body_is_refused_without_parsing_it"),
    _m("separator_cap_excludes_text", "commas inside text are text",
       V, "MAX_SEPARATORS = STRUCTURE_SEPARATORS + MAX_TEXT_CODEPOINTS",
       "MAX_SEPARATORS = STRUCTURE_SEPARATORS",
       "test_media_sec__commas_inside_text_are_text"),
    _m("separator_cap_off_by_one", "the separator cap is exact",
       I, "    if text.count(SEPARATOR) > max_separators:",
       "    if text.count(SEPARATOR) > max_separators + 1:",
       "test_media_sec__the_separator_cap_is_exact"),
    _m("separator_counts_payload_bytes", "the count is of separators, not of payload bytes",
       I, 'SEPARATOR = ","', 'SEPARATOR = "A"',
       "test_media_sec__an_inline_video_costs_one_separator"),
    _m("body_encoding_sniffed", "the body is UTF-8 (RFC 8259)",
       I, "    try:\n        text = raw.decode()\n    except UnicodeDecodeError:",
       "    try:\n        text = raw.decode(errors=\"replace\")\n    except UnicodeDecodeError:",
       "test_media_sec__a_body_that_is_not_utf8_is_refused",
       "test_media_sec__utf16_text_is_not_a_413_it_is_a_400"),
    _m("bom_accepted", "a BOM is not part of a JSON document",
       I, "    if text.startswith(BOM):", "    if False:",
       "test_media_sec__a_body_that_is_not_utf8_is_refused"),
    _m("payload_not_ascii_checked", "an inline payload is base64 ASCII (r3 B2)",
       V, "    if not source.isascii():", "    if False:",
       "test_media_sec__an_inline_payload_that_is_not_base64_ascii_is_refused"),
    _m("payload_nul_admitted", "an inline payload carries no NUL",
       V, '    if "\\x00" in source:', "    if False:",
       "test_media_sec__an_inline_payload_that_is_not_base64_ascii_is_refused"),
    _m("digest_ignores_other_params_with_media", "the digest covers the whole body (r3 B3)",
       V, '    document = {**body, "messages": [_tokenised(message, media) for message in messages]}',
       '    document = {"messages": [_tokenised(message, media) for message in messages]}',
       "test_dur_admit__the_payload_digest_covers_the_media_payload_by_hash"),
    # --- review r3 same pass -------------------------------------------------------
    _m("content_length_trusted_blindly", "a declared length is parsed only when it is one",
       I, "        if declared.isascii() and declared.isdigit() and len(declared) <= 19:",
       "        if declared:",
       "test_media_sec__a_declared_length_that_is_not_a_number_is_ignored"),
    _m("opener_cap_off_by_one", "the opener cap is exact at its boundary",
       I, "    if sum(text.count(opener) for opener in OPENERS) > max_openers:",
       "    if sum(text.count(opener) for opener in OPENERS) > max_openers + 1:",
       "test_media_sec__the_opener_cap_is_exact_at_its_real_boundary"),
    _m("slot_threshold_inclusive", "a body at the threshold is not a large body",
       I, "        if self.held or total <= self.slots.threshold:",
       "        if self.held or total < self.slots.threshold:",
       "test_media_sec__the_large_body_threshold_is_exclusive"),
    _m("slot_released_twice", "a slot is released once, however often release is called",
       I, "        if self.held:\n            self.slots.in_flight -= 1",
       "        if True:\n            self.slots.in_flight -= 1",
       "test_media_sec__a_slot_is_released_once_however_often_release_is_called"),
    _m("close_only_on_401", "every pre-body refusal closes the connection",
       I, 'CLOSE_CODES = frozenset({"invalid_api_key", "request_too_large", "capacity_exhausted",\n'
          '                         "deadline_exceeded"})',
       'CLOSE_CODES = frozenset({"invalid_api_key"})',
       "test_f_base__a_429_and_a_504_also_close_the_connection", dies_by=("KeyError",)),
    _m("last_resort_keeps_stale_headers", "the last resort drops the failed envelope's headers",
       I, "        return JSONResponse(body, status_code=500,\n"
          "                            headers={wire.HEADER_INFERENCE_ID: request_id})",
       "        return JSONResponse(body, status_code=500, headers=headers)",
       "test_f_base__the_last_resort_carries_no_header_from_the_envelope_it_replaced"),
    _m("handlers_mint_unchecked", "the app-level handlers mint a checked id",
       N, "        return intake.response(errors.DomainError(code=code), intake.mint(mint_request_id))",
       "        return intake.response(errors.DomainError(code=code), mint_request_id())",
       "test_f_base__the_app_level_handlers_mint_a_checked_request_id"),
    _m("unhandled_mints_unchecked", "the unhandled handler mints a checked id",
       N, "        request_id = intake.mint(mint_request_id)", "        request_id = mint_request_id()",
       "test_f_base__the_app_level_handlers_mint_a_checked_request_id"),
    _m("backslash_allowed_in_urls", "a backslash alone is enough to refuse a url",
       V, r'UNSAFE_IN_URL = re.compile(r"[\x00-\x20\x7f-\x9f\u2028\u2029@\\]")',
       r'UNSAFE_IN_URL = re.compile(r"[\x00-\x20\x7f-\x9f\u2028\u2029@]")',
       "test_media_sec__a_backslash_alone_is_enough_to_refuse_a_url", dies_by=("KeyError",)),
    _m("slow_deadline_doubled", "the intake deadline is the configured one",
       I, "    deadline = clock() + timeout_s", "    deadline = clock() + timeout_s * 2",
       "test_media_sec__a_slow_body_hits_the_intake_deadline"),
    _m("parameters_not_closed", "parameters carry the closed set and nothing else",
       V, '                        if name in SUPPORTED - {"model", "messages"}},',
       "                        if True},",
       "test_f_base__parameters_carry_the_closed_set_and_nothing_else"),
    # --- review r4: the parser's per-literal work, and the allowances --------------
    _m("parse_int_unbounded", "an integer literal is bounded before it is converted",
       I, "        body = json.loads(text, parse_constant=_no_constants,\n"
          "                          parse_int=_bounded_int, parse_float=_bounded_float)",
       "        body = json.loads(text, parse_constant=_no_constants,\n"
          "                          parse_float=_bounded_float)",
       "test_media_sec__a_body_of_huge_integers_is_refused_by_the_parser",
       "test_media_sec__a_number_literal_is_bounded_by_its_length"),
    _m("parse_float_unbounded", "a float literal is bounded too",
       I, "        body = json.loads(text, parse_constant=_no_constants,\n"
          "                          parse_int=_bounded_int, parse_float=_bounded_float)",
       "        body = json.loads(text, parse_constant=_no_constants,\n"
          "                          parse_int=_bounded_int)",
       "test_media_sec__a_number_literal_is_bounded_by_its_length"),
    _m("number_digits_off_by_one", "the digit bound is exact",
       I, "    if len(literal.lstrip(\"-\")) > MAX_NUMBER_DIGITS:\n"
          "        raise ValueError(f\"a number of more than {MAX_NUMBER_DIGITS} digits\")\n"
          "    return int(literal)",
       "    if len(literal.lstrip(\"-\")) > MAX_NUMBER_DIGITS + 1:\n"
          "        raise ValueError(f\"a number of more than {MAX_NUMBER_DIGITS} digits\")\n"
          "    return int(literal)",
       "test_media_sec__a_number_literal_is_bounded_by_its_length"),
    _m("number_sign_counted_as_a_digit", "a sign is not a digit",
       I, '    if len(literal.lstrip("-")) > MAX_NUMBER_DIGITS:', "    if len(literal) > MAX_NUMBER_DIGITS:",
       "test_media_sec__a_number_literal_is_bounded_by_its_length", dies_by=("KeyError",)),
    _m("content_length_non_ascii_digits", "a non-ASCII digit never reaches int()",
       I, "        if declared.isascii() and declared.isdigit() and len(declared) <= 19:",
       "        if declared.isdigit() and len(declared) <= 19:",
       "test_media_sec__a_declared_length_that_is_not_a_number_is_ignored"),
    _m("structure_separators_halved", "the structural allowance fits a maximal body",
       V, "STRUCTURE_SEPARATORS = (len(SUPPORTED) + MAX_MESSAGES * (2 + MAX_PARTS_PER_MESSAGE * 2)\n"
          "                        + MAX_STOP_SEQUENCES)",
       "STRUCTURE_SEPARATORS = (len(SUPPORTED) + MAX_MESSAGES * (2 + MAX_PARTS_PER_MESSAGE * 2)\n"
          "                        + MAX_STOP_SEQUENCES) // 2",
       "test_media_sec__a_maximal_structure_body_is_accepted"),
    _m("text_beside_messages_ignored", "stop sequences and the model name are text too",
       V, "MAX_SEPARATORS = STRUCTURE_SEPARATORS + MAX_TEXT_CODEPOINTS + TEXT_BESIDE_MESSAGES",
       "MAX_SEPARATORS = STRUCTURE_SEPARATORS + MAX_TEXT_CODEPOINTS",
       "test_media_sec__a_maximal_structure_body_is_accepted"),
    # --- the cases the first pass left unkillable ------------------------------
    _m("everything_is_too_large", "a body within the cap is read whole",
       I, "                if total > max_bytes:", "                if total >= 0:",
       "test_media_sec__a_body_within_the_cap_is_read_whole"),
    _m("malformed_json_changes_code", "malformed JSON is a stable invalid_request",
       I, '        raise errors.InvalidRequest("the request body is not valid JSON") from None',
       '        raise errors.UnsupportedParameter("the request body is not valid JSON") from None',
       "test_media_sec__malformed_json_is_a_400_with_no_parser_text"),
    _m("envelope_carries_the_operator_detail", "the envelope carries only contract fields",
       I, '        return JSONResponse(body.model_dump(mode="json", exclude_none=True),',
       '        return JSONResponse({**body.model_dump(mode="json", exclude_none=True),\n'
       '                             "detail": str(error.detail)},',
       "test_f_base__the_envelope_carries_only_the_contract_fields"),
    _m("upload_handles_refused", "an owned upload handle is a valid media reference",
       V, "    if source.startswith(UPLOAD_SCHEME):", "    if False:",
       "test_media_sec__an_owned_upload_handle_and_a_public_url_are_both_accepted"),
    _m("disagreeing_output_ceilings_accepted", "max_tokens and max_completion_tokens must agree",
       V, "        if requested is not None and alternative is not None and requested != alternative:",
       "        if False:", "test_f_base__max_tokens_and_max_completion_tokens_must_agree"),
    # CREDIT-RATE, G's half: admission re-resolves what the caller asked for; a name
    # pinned here would freeze a revision the store never re-read.
    _m("requested_model_pinned_at_validation", "the requested name passes through untouched",
       V, "            model_revision=model,",
       "            model_revision=resolved.serving.model_revision,",
       "test_f_base__the_derived_ceilings_and_mode_reach_the_acceptor",
       "test_credit_rate__admission_takes_the_publication_current_at_admission",
       "test_credit_rate__an_alias_moved_after_acceptance_moves_no_admitted_job_or_replay"),
    _m("api_key_is_an_operator", "an API key is a service principal, never an operator",
       A, "API_KEY_ROLE = Role.service", "API_KEY_ROLE = Role.operator",
       "test_dur_rls__a_known_key_becomes_an_auth_context"),
    _m("entitlement_version_not_injectable", "the entitlement version source is injectable",
       A, "        self.entitlement_version = entitlement_version or (lambda org_id: 0)",
       "        self.entitlement_version = lambda org_id: 0",
       "test_dur_rls__the_entitlement_version_source_is_injectable"),
    _m("empty_token_looked_up", "a request with no bearer token is refused, not looked up",
       K, "        if not token:\n            return None, 401",
       "        if False:\n            return None, 401",
       "test_dur_rls__no_bearer_token_is_401"),
    _m("readiness_hides_the_components", "readiness explains component state",
       N, '        return JSONResponse({"status": OK, "mode": rt.mode, "components": state}, headers=headers)',
       '        return JSONResponse({"status": OK}, headers=headers)',
       "test_f_base__readiness_explains_component_state_to_a_direct_loopback_peer"),
    _m("probe_exception_escapes", "a probe that raises is unavailable, not a 500",
       N, "        except Exception:\n"
          '            intake.log.exception("readiness probe %s failed", name)\n'
          "            state[name] = UNAVAILABLE",
       "        except Exception:\n            raise",
       "test_f_base__a_readiness_probe_that_raises_is_unavailable_not_a_500",
       "test_f_base__pilot_refuses_to_start_when_a_component_is_unreachable", dies_by=("ConnectionError",)),
    # --- G1R item 1: the audience and identity are the key row's -----------------
    _m("audience_defaults_to_consumer", "a row with no audience is not a credential",
       A, "        audience = CredentialAudience(audience)",
       '        audience = CredentialAudience(audience or "consumer")',
       "test_api_auth__a_row_without_a_usable_audience_is_not_a_credential"),
    _m("consumer_without_individual_accepted", "a consumer key names its individual",
       A, "    if consumer and not user_id:", "    if False:",
       "test_api_auth__a_row_without_a_usable_audience_is_not_a_credential"),
    _m("legacy_creator_ignored", "a pre-0009 consumer key is its creator's (D2's coalesce)",
       A, '            user_id=row.get("user_id") or row.get("created_by"),',
       '            user_id=row.get("user_id"),',
       "test_api_auth__each_audience_carries_only_its_own_identity"),
    _m("creator_overrides_the_individual", "a key's own user_id wins over its creator",
       A, '            user_id=row.get("user_id") or row.get("created_by"),',
       '            user_id=row.get("created_by") or row.get("user_id"),',
       "test_api_auth__each_audience_carries_only_its_own_identity"),
    _m("individual_kept_for_every_audience", "only a consumer key carries an individual",
       A, "                             user_id=user_id if consumer else None,",
       "                             user_id=user_id,",
       "test_api_auth__each_audience_carries_only_its_own_identity"),
    _m("provider_key_under_another_org", "a provider dev key's org is its provider's (review S4)",
       A, "    if audience is CredentialAudience.provider_dev and provider_org_id != org_id:",
       "    if False:",
       "test_api_auth__a_row_without_a_usable_audience_is_not_a_credential"),
    _m("consumer_scope_scrubbed", "a consumer row carrying provider scope is refused, not "
       "silently scrubbed (review S3)",
       A, "                             provider_org_id=provider_org_id, endpoint_id=endpoint_id)",
       "                             provider_org_id=None if consumer else provider_org_id,\n"
       "                             endpoint_id=None if consumer else endpoint_id)",
       "test_api_auth__a_row_without_a_usable_audience_is_not_a_credential"),
    _m("provider_scope_dropped", "a provider dev key carries its provider and endpoint",
       A, "                             provider_org_id=provider_org_id, endpoint_id=endpoint_id)",
       "                             provider_org_id=None, endpoint_id=None)",
       "test_api_auth__each_audience_carries_only_its_own_identity"),
    _m("ingress_reads_f1_columns", "the ingress reads 0009's audience and scope columns",
       A, 'KEY_COLUMNS = "id,org_id,revoked_at,audience,user_id,created_by,provider_org_id,endpoint_id"',
       'KEY_COLUMNS = "id,org_id,revoked_at"',
       "test_api_auth__the_ingress_reads_the_0009_columns_and_the_legacy_route_does_not",
       "test_api_auth__a_pre_0009_schema_fails_closed_and_retryable"),
    _m("http_error_ignored", "an HTTP error from the identity source is a failed lookup (review C3)",
       K, "                r.raise_for_status()", "                pass",
       "test_api_auth__a_pre_0009_schema_fails_closed_and_retryable"),
    _m("cached_row_serves_any_select", "a row cached by a narrower select is a miss (review S1)",
       K, "        if hit is not None and hit[1] is not None and not set(select.split(\",\")) <= hit[1].keys():",
       "        if False:",
       "test_api_auth__a_row_cached_by_the_legacy_select_is_not_an_identity_without_audience"),
    _m("legacy_route_reads_0009", "the legacy route keeps F1's columns (hosted has no 0009)",
       K, '    async def authenticate(self, req, select="id,org_id,revoked_at"):',
       '    async def authenticate(self, req, select="id,org_id,revoked_at,audience"):',
       "test_api_auth__the_ingress_reads_the_0009_columns_and_the_legacy_route_does_not"),
    # --- G1R item 2: resolution for the audience, publication, price, capability ---
    # It proves the status (403, not 404); that an operator runs no inference at all (R66)
    # is audience_rule_ignored's kill (review H2).
    _m("operator_runs_inference", "an operator credential is refused forbidden, not not_found",
       C, "    if callable_ is None:\n        raise errors.Forbidden(",
       "    if False:\n        raise errors.Forbidden(",
       "test_split_contract__an_operator_key_runs_no_inference",
       "test_api_auth__refusals_leave_no_hold_job_or_journal_reservation"),
    _m("audience_rule_ignored", "each audience calls only its own kind of deployment",
       C, "    callable_ = CALLABLE.get(auth.audience)",
       "    callable_ = CALLABLE.get(CredentialAudience.consumer)",
       "test_split_contract__a_provider_dev_key_reaches_only_its_own_private_endpoint",
       "test_split_contract__an_operator_key_runs_no_inference"),
    _m("other_endpoint_reached", "a provider dev key reaches only its own endpoint (review S2; "
       "the contract's check, proven here over a leaky catalog)",
       "contracts/v2/ports.py", "        if auth.endpoint_id != deployment.endpoint_id:",
       "        if False:",
       "test_split_contract__a_provider_dev_key_reaches_only_its_own_private_endpoint"),
    _m("rival_provider_reached", "a provider dev key reaches only its own provider's endpoint",
       "contracts/v2/ports.py", "        if auth.provider_org_id != deployment.provider_org_id:",
       "        if False:",
       "test_split_contract__a_provider_dev_key_reaches_only_its_own_private_endpoint"),
    _m("publication_state_ignored", "only an active (or ready private) revision is callable",
       C, "        if deployment is not None and (deployment.visibility, deployment.state) != callable_:",
       "        if deployment is not None and deployment.visibility != callable_[0]:",
       "test_credit_rate__only_an_active_published_deployment_is_callable",
       "test_credit_rate__a_revoked_publication_is_not_found"),
    _m("refusal_confirms_the_artifact", "an uncallable deployment answers like an unknown one",
       C, "            deployment = None                        # the same answer as an unknown model",
       '            raise errors.Forbidden("not callable by this credential")',
       "test_split_contract__a_consumer_key_cannot_reach_a_private_dev_endpoint",
       "test_credit_rate__only_an_active_published_deployment_is_callable"),
    _m("wrong_unit_card_accepted", "a card not priced in CREDIT is no card (R64/R69)",
       C, "        rate_card=card if priced_in_credit(card) else None, policy=policy)",
       "        rate_card=card, policy=policy)",
       "test_credit_rate__an_unpriced_or_wrong_unit_model_is_refused",
       "test_api_auth__refusals_leave_no_hold_job_or_journal_reservation"),
    _m("usd_amounts_accepted", "a unit is a type: USD amounts are not CREDIT",
       C, "            and isinstance(card.input_rate_per_million, Credit)\n"
          "            and isinstance(card.output_rate_per_million, Credit))",
       "            )",
       "test_credit_rate__an_unpriced_or_wrong_unit_model_is_refused"),
    _m("usd_unit_accepted", "a card's unit is CREDIT",
       C, "card.unit == CREDIT", 'card.unit in (CREDIT, "USD")',
       "test_credit_rate__an_unpriced_or_wrong_unit_model_is_refused"),
    _m("unpriced_is_free", "an unpriced deployment is unserveable (R69), seen at the ingress",
       "contracts/v2/ports.py", "    if rate_card is None:\n        raise errors.InvalidRequest(",
       "    if False:\n        raise errors.InvalidRequest(",
       "test_credit_rate__a_provider_preview_needs_its_own_approved_card",
       "test_credit_rate__an_unpriced_or_wrong_unit_model_is_refused"),
    _m("catalog_outage_is_a_500", "a catalog outage is retryable, not an internal error",
       C, "    except Exception:\n        # A lookup that failed",
       "    except KeyboardInterrupt:\n        # A lookup that failed",
       "test_split_contract__a_catalog_outage_is_retryable_not_a_missing_model"),
    _m("modalities_unchecked", "only declared input modalities are accepted",
       C, "    if not needed <= set(capability.input_modalities):", "    if False:",
       "test_split_contract__only_declared_capabilities_are_accepted"),
    _m("text_needs_no_modality", "a text part needs the text modality too",
       C, '                      else (MODALITY[part["type"]] for part in content))',
       '                      else (MODALITY[part["type"]] for part in content\n'
       '                            if part["type"] != "text"))',
       "test_split_contract__only_declared_capabilities_are_accepted"),
    _m("stream_capability_unchecked", "a stream needs a serving revision that streams",
       C, "    if mode is ExecutionMode.stream and not capability.stream_output:", "    if False:",
       "test_split_contract__only_declared_capabilities_are_accepted"),
    _m("default_output_is_not_the_ceiling", "an unstated output ceiling reserves the whole envelope",
       V, "        output = ceiling if output is None else output",
       "        output = 1 if output is None else output",
       "test_dur_admit__admit_accepts_the_ingress_ceilings_and_derives_the_hold"),
    _m("deployment_output_limit_ignored", "the output ceiling is the deployment's too",
       V, "        ceiling = min(self.limits.max_output_tokens, deployment.max_output_tokens)",
       "        ceiling = self.limits.max_output_tokens",
       "test_split_contract__the_ceilings_are_the_deployments_own"),
    _m("deployment_input_limit_ignored", "the input ceiling never exceeds the deployment's",
       V, "        return min(deployment.max_input_tokens, self.limits.max_context_tokens - output), output",
       "        return self.limits.max_context_tokens - output, output",
       "test_f_base__the_derived_ceilings_and_mode_reach_the_acceptor",
       "test_f_base__max_completion_tokens_alone_is_the_output_ceiling"),
    # --- G1R item 3: the idempotency scope is what keeps a replay on its admission ---
    _m("idempotency_key_dropped", "the caller's Idempotency-Key reaches admission",
       V, '    key = headers.get("idempotency-key")', "    key = None",
       "test_credit_rate__a_rate_published_after_acceptance_moves_no_admitted_job_or_replay",
       "test_credit_rate__an_alias_moved_after_acceptance_moves_no_admitted_job_or_replay",
       "test_dur_cap__denied_capacity_is_retryable_and_the_retry_is_admitted_once",
       dies_by=("KeyError",)),
    # --- G1R item 4: pilot never serves chat through the legacy route (E3B dr17) -----
    # `config.validate_runtime` is the coordinator's hook; G1R's brief places this refusal
    # there, so these three edit it in the temporary copy.
    _m("pilot_serves_the_legacy_route", "pilot refuses while the legacy chat route is composed",
       "config.py", "        if ingress not in composition.ROUTERS or chat in composition.ROUTERS:",
       "        if False:",
       "test_api_auth__a_pilot_never_serves_chat_through_the_legacy_route"),
    _m("legacy_route_beside_the_ingress", "the legacy route beside the ingress still refuses",
       "config.py", "        if ingress not in composition.ROUTERS or chat in composition.ROUTERS:",
       "        if ingress not in composition.ROUTERS:",
       "test_api_auth__a_pilot_never_serves_chat_through_the_legacy_route"),
    _m("no_metered_ingress_accepted", "a pilot with no metered ingress refuses (I0's predicate)",
       "config.py", "        if ingress not in composition.ROUTERS or chat in composition.ROUTERS:",
       "        if chat in composition.ROUTERS:",
       "test_api_auth__a_pilot_never_serves_chat_through_the_legacy_route"),
    # --- G1R item 5: the headless client's declared surface is served -------------
    _m("https_video_refused", "an https video reference is served",
       V, "    if not source.lower().startswith(HTTP_SCHEMES):", "    if True:",
       "test_api_auth__the_headless_quickstart_is_served_over_both_media_forms"),
    _m("inline_video_refused", "an inline data: video is served",
       V, '    if match.group("mime").lower() not in allowed_mime:', "    if True:",
       "test_api_auth__the_headless_quickstart_is_served_over_both_media_forms",
       "test_dur_cap__the_headless_client_retries_denied_capacity_with_its_own_key"),
    # These two edit files G does not own, in the temporary copy only: they are the
    # cutover itself, and they say exactly which cases pin today's behaviour.
    _m("composition_root_mounts_the_ingress", "G1 mounts nothing until the cutover",
       "gateway/app.py", "ROUTERS = (health, models, chat)",
       "from .routes import ingress as _ingress\nROUTERS = (health, models, chat, _ingress)",
       "test_f_base__the_composition_root_still_mounts_only_the_legacy_routers"),
    # R44/item 14: while `INFRX_MODE` is unset the legacy entry keeps F1 behaviour, so the
    # honest kill is the refusal this mutant introduces. G2/I0 retire this mutant at cutover.
    _m("unset_mode_refuses", "an unset INFRX_MODE is still legacy behaviour",
       "config.py", '        return "legacy"',
       '        raise RuntimeMisconfigured(mode, detail="INFRX_MODE must be set")',
       "test_f_base__an_unset_mode_is_still_legacy_behaviour",
       "test_f_base__the_composition_root_still_mounts_only_the_legacy_routers",
       "test_f_base__registering_the_ingress_never_replaces_the_legacy_chat_route",
       dies_by=("RuntimeMisconfigured",)),
    # === G2 item 1: durable acceptance (DUR-ADMIT G half, API-MODES) =====================
    _m("admits_the_validation_record", "admission takes prepare_request's record (S2M D1)",
       R, "            else self.jobs.admit(prepared, idem)",
       "            else self.jobs.admit(request, idem)",
       "test_dur_admit__admission_takes_the_prepared_record_never_the_validation_record"),
    _m("stages_the_validation_record", "the staged payload is the prepared record",
       R, "        refs = await _dependency(self.media.stage(auth.org_id, prepared))",
       "        refs = await _dependency(self.media.stage(auth.org_id, request))",
       "test_dur_admit__admission_takes_the_prepared_record_never_the_validation_record"),
    _m("staged_refs_never_attached", "the staged refs are bound to the admitted job",
       R, "                await _dependency(self.media.attach(job.request_id, refs))",
       "                pass",
       "test_dur_admit__admission_takes_the_prepared_record_never_the_validation_record",
       "test_api_modes__the_sync_and_sse_matrix_answers_from_committed_state"),
    _m("attach_without_the_jobs_org", "attach reads the job's org from the admission (R55)",
       R, "            self._attaching[job.request_id] = job.org_id", "            pass",
       "test_dur_admit__admission_takes_the_prepared_record_never_the_validation_record"),
    _m("async_admitted", "explicit async is refused before anything durable (G3's)",
       R, "        if request.execution_mode is ExecutionMode.async_:", "        if False:",
       "test_api_modes__explicit_async_is_refused_before_anything_durable"),
    _m("pin_drift_ignored", "the pinned revision must still serve what was asked (G1R L2)",
       R, "                check_capability(serving, prepared.messages, prepared.execution_mode)",
       "                pass",
       "test_api_modes__a_capability_drift_after_validation_cancels_the_admitted_job"),
    _m("unapproved_card_admitted", "a pinned card other than ACTIVE_RATE_CARD_VERSION refuses",
       R, "                if pins.rate_card_version != self.active_rate_card_version:",
       "                if False:",
       "test_api_modes__a_card_this_deployment_did_not_approve_is_refused_and_released"),
    _m("refused_admission_left_running", "a refusal after admission cancels the job it admitted",
       R, "            await self.cancel(job.org_id, job.handle, quiet=True)\n"
          "            raise\n\n    def job_org",
       "            raise\n\n    def job_org",
       "test_api_modes__a_capability_drift_after_validation_cancels_the_admitted_job",
       "test_api_modes__a_card_this_deployment_did_not_approve_is_refused_and_released"),
    _m("outage_is_a_500", "a dependency failing at acceptance is a typed, retryable 503",
       R, '    except Exception:\n        log.exception("a durable dependency failed at acceptance")',
       "    except Exception:\n        raise",
       "test_dur_admit__an_outage_at_acceptance_is_a_retryable_503_with_no_side_effects"),
    _m("replay_header_dropped", "a replay says so (Idempotency-Replayed, E1B 5 / I2B 7)",
       R, '            headers[wire.HEADER_IDEMPOTENCY_REPLAYED] = "true"', "            pass",
       "test_dur_output__a_lost_answer_is_replayed_by_key_with_one_settlement",
       "test_api_modes__a_replay_of_a_cancelled_job_is_rendered_cancelled_never_failed",
       "test_api_stream__a_gateway_restart_mid_stream_leaves_the_job_to_its_worker"),
    _m("replay_names_a_new_job", "a replay answers for the job it replays, never a new one",
       R, "                   request_id=admission.request_id, model=request.model_revision,",
       "                   request_id=request.request_id, model=request.model_revision,",
       "test_dur_output__a_lost_answer_is_replayed_by_key_with_one_settlement",
       "test_api_modes__success_is_answered_only_after_the_terminal_commit"),
    _m("replay_reaccepted", "a replay re-runs nothing of acceptance",
       R, "        if admission.replayed:", "        if False:",
       "test_dur_output__a_lost_answer_is_replayed_by_key_with_one_settlement"),
    # === G2 item 2: the synchronous wait (API-MODES, DUR-OUTPUT) =========================
    _m("success_before_terminal_commit", "a sync answer only follows the terminal commit",
       R, "                if outcome is not None:\n                    return outcome",
       "                if True:\n                    return outcome",
       "test_api_modes__success_is_answered_only_after_the_terminal_commit"),
    _m("result_not_read", "the 200 body is the committed result object",
       R, "        text = await self.results.read_result(job.org_id, outcome.result_ref)",
       '        text = ""',
       "test_api_modes__success_is_answered_only_after_the_terminal_commit",
       "test_api_modes__the_sync_and_sse_matrix_answers_from_committed_state"),
    _m("sync_disconnect_not_cancelled", "a sync client that leaves cancels its job durably",
       R, "        if gone.done():\n            await self.cancel(job.org_id, job.handle, quiet=True)\n"
          "            return None",
       "        if gone.done():\n            return None",
       "test_api_modes__a_sync_disconnect_cancels_durably"),
    _m("sync_wait_orphans_on_cancellation", "a cancelled sync wait still cancels its job",
       R, "            await self.cancel(job.org_id, job.handle, quiet=True)\n            raise\n"
          "        if gone.done():",
       "            raise\n        if gone.done():",
       "test_api_modes__a_sync_wait_cancelled_from_outside_still_cancels_the_job"),
    _m("cancel_unshielded", "the handler's own cancellation cannot abort the durable cancel",
       R, "            return await asyncio.shield(task)", "            return await task",
       "test_api_modes__a_sync_wait_cancelled_from_outside_still_cancels_the_job"),
    _m("timeout_leaves_job_running", "past the bound the gateway cancels the job",
       R, "        outcome = await self.cancel(job.org_id, job.handle, quiet=True)\n"
          "        if outcome is None:                     # the cancel is unconfirmed",
       "        outcome = None\n        if outcome is None:                     # the cancel is unconfirmed",
       "test_api_modes__a_sync_timeout_cancels_and_answers_the_deadline"),
    _m("unconfirmed_cancel_claims_a_state", "a cancel that could not be confirmed claims no state",
       R, "        if outcome is None:                     # the cancel is unconfirmed",
       "        if False:                     # the cancel is unconfirmed",
       "test_api_modes__a_timeout_whose_cancel_fails_claims_no_state"),
    _m("timeout_hides_committed_result", "a timeout racing a committed result returns it (01)",
       R, "        if outcome.state is JobState.cancelled:\n            raise errors.DeadlineExceeded(",
       "        if True:\n            raise errors.DeadlineExceeded(",
       "test_api_modes__a_timeout_that_races_a_committed_result_returns_the_result",
       "test_api_modes__already_terminal_on_cancel_reads_the_committed_outcome"),
    _m("server_timing_dropped", "Server-Timing names the phase the gateway measured",
       R, "        headers = {wire.HEADER_INFERENCE_ID: job.request_id,\n"
          "                   wire.HEADER_SERVER_TIMING: metrics.server_timing(timings)}",
       "        headers = {wire.HEADER_INFERENCE_ID: job.request_id}",
       "test_api_modes__server_timing_and_the_registry_count_what_the_gateway_saw"),
    _m("rejections_uncounted", "a refusal is counted by code and hashed tenant (I3B 3)",
       R, '            self._count("infrx_requests_rejected_total", code=refused.code, '
          'tenant=auth.org_id)', "            pass",
       "test_api_modes__server_timing_and_the_registry_count_what_the_gateway_saw"),
    _m("acceptances_uncounted", "an acceptance is counted by mode and hashed tenant (I3B 3)",
       R, '            self._count("infrx_jobs_accepted_total", mode=request.execution_mode,\n'
          "                        tenant=auth.org_id)", "            pass",
       "test_api_modes__server_timing_and_the_registry_count_what_the_gateway_saw"),
    # === G2 item 3: the persistent SSE relay (API-STREAM, DUR-OUTPUT) ====================
    _m("progress_frame_without_handle", "the first frame carries the job handle",
       R, '    return {"job_handle": job.handle, "request_id": job.request_id, "phase": phase}',
       '    return {"request_id": job.request_id, "phase": phase}',
       "test_api_stream__the_first_frame_names_the_job_before_any_model_output",
       "test_api_stream__a_gateway_restart_mid_stream_leaves_the_job_to_its_worker"),
    _m("keepalive_as_data", "a keepalive is an SSE comment, never a data frame",
       R, 'KEEPALIVE = wire.SseFrame(comment="keepalive").render()',
       'KEEPALIVE = wire.SseFrame(data="keepalive").render()',
       "test_api_stream__keepalives_are_comments_never_data"),
    _m("keepalive_never_sent", "a quiet stream is kept open by comments",
       R, "                await emit(KEEPALIVE)", "                pass",
       "test_api_stream__keepalives_are_comments_never_data"),
    _m("relay_reads_raw", "only visible text reaches the wire (R58/R80)",
       R, '        visible = chunk.payload.get("visible")',
       '        visible = chunk.payload.get("raw")',
       "test_api_stream__only_visible_text_reaches_the_wire"),
    _m("stream_ends_on_an_empty_page", "an empty journal page is not the end of the job",
       R, "            if chunks is not None and ending is not None:\n                # D3's",
       "            if chunks is not None:\n                # D3's",
       "test_api_stream__done_is_sent_only_after_the_terminal_commit",
       "test_api_modes__the_sync_and_sse_matrix_answers_from_committed_state"),
    _m("done_without_its_cursor", "[DONE] ends on the terminal journal event (R30)",
       R, "                if chunk.event_type is ChunkEventType.terminal:", "                if False:",
       "test_api_stream__done_is_sent_only_after_the_terminal_commit",
       "test_api_modes__the_sync_and_sse_matrix_answers_from_committed_state"),
    _m("usage_frame_dropped", "a successful stream ends with the settled usage",
       R, "            if outcome.usage is not None:", "            if False:",
       "test_api_modes__the_sync_and_sse_matrix_answers_from_committed_state"),
    _m("post_header_error_as_status", "after the headers an error is a stream code, not a status",
       R, "            await emit(_error_frame(job, _refusal(outcome, stream=True)))",
       "            await emit(_error_frame(job, _refusal(outcome, stream=False)))",
       "test_api_stream__an_upstream_error_is_an_honest_terminal_error",
       "test_dur_output__a_kill_after_the_first_committed_chunk_is_never_regenerated"),
    _m("stream_disconnect_not_cancelled", "an SSE client that leaves cancels its job durably",
       R, "            if gone.done():\n                await self.cancel(job.org_id, job.handle, "
          "quiet=True)\n                return\n            try:",
       "            if gone.done():\n                return\n            try:",
       "test_api_stream__a_disconnect_mid_stream_cancels_durably"),
    _m("unstarted_stream_leaks", "a stream that could not go on cancels its job",
       R, "            ended = await relay.cancel(job.org_id, job.handle, quiet=True)",
       "            ended = None",
       "test_api_stream__a_client_gone_before_the_first_byte_still_cancels",
       "test_api_stream__a_replay_gap_ends_the_stream_honestly_and_cancels"),
    _m("gap_reported_as_unknown", "a replay gap is named, not reported as an unknown status",
       R, "            error = failure if isinstance(failure, errors.DomainError) \\\n"
          '                else errors.StatusUnknown("the stream could not continue")',
       '            error = errors.StatusUnknown("the stream could not continue")',
       "test_api_stream__a_replay_gap_ends_the_stream_honestly_and_cancels"),
    _m("journal_outage_ends_the_stream", "a failed journal read is retried, not an end",
       R, "            except Exception:\n                # The database, not the job",
       "            except ZeroDivisionError:\n                # The database, not the job",
       "test_api_stream__a_journal_read_that_fails_is_retried_not_the_end"),
    _m("no_done_after_an_ended_job", "[DONE] follows an error once the job it ended is terminal",
       R, "                if ended is not None:", "                if False:",
       "test_api_stream__a_replay_gap_ends_the_stream_honestly_and_cancels"),
    _m("outcome_fallback_ignored", "without a terminal event the committed outcome ends it",
       R, "                ending = await self._outcome(job)", "                ending = None",
       "test_api_stream__without_a_terminal_event_the_committed_outcome_ends_the_stream"),
    _m("restart_cancels_a_named_stream", "a stream whose identity was sent is left to its worker",
       R, "            if not named:", "            if True:",
       "test_api_stream__a_gateway_restart_mid_stream_leaves_the_job_to_its_worker"),
    # === G2 item 4: rendering the committed outcome (D3 request 2) =======================
    _m("held_unknown_rendered_as_its_settlement", "the state is rendered, never the settlement",
       R, '    detail = {"state": outcome.state.value}',
       '    detail = {"state": outcome.settlement_state.value}',
       "test_api_modes__a_replay_of_a_cancelled_job_is_rendered_cancelled_never_failed",
       "test_api_modes__a_credit_job_that_expires_unclaimed_is_rendered_expired"),
    _m("cancel_rendered_as_failure", "a cancelled job is rendered cancelled, never failed",
       R, "    if outcome.state is JobState.cancelled:\n        return errors.StateConflict",
       "    if False:\n        return errors.StateConflict",
       "test_api_modes__a_replay_of_a_cancelled_job_is_rendered_cancelled_never_failed",
       "test_api_stream__without_a_terminal_event_the_committed_outcome_ends_the_stream"),
    _m("expired_rendered_failed", "an expired job is rendered as its deadline, never billed",
       R, "    if outcome.state is JobState.expired or outcome.cause in DEADLINE_CAUSES:",
       "    if outcome.cause in (TerminalCause.deadline_exceeded, TerminalCause.sync_deadline):",
       "test_api_modes__a_credit_job_that_expires_unclaimed_is_rendered_expired"),
    _m("foreign_cancel_swallowed", "another tenant's handle is not_found, like an unknown one",
       R, "    async def cancel(self, org_id: str, handle: str, *, quiet: bool = False):",
       "    async def cancel(self, org_id: str, handle: str, *, quiet: bool = True):",
       "test_api_modes__a_foreign_or_unknown_handle_is_not_found_and_changes_nothing"),
    _m("already_terminal_not_read", "after already_terminal the outcome is read (D3 delta)",
       R, "        except errors.AlreadyTerminal:", "        except errors.StaleLease:",
       "test_api_modes__already_terminal_on_cancel_reads_the_committed_outcome"),
    # === G2 item 5: composition, readiness and the route table ===========================
    _m("pilot_built_without_catalog", "no pilot without a CatalogDirectory (D5)",
       P, "        if value is None:", '        if value is None and name != "catalog":',
       "test_f_base__a_pilot_is_not_built_without_its_durable_adapters"),
    _m("pilot_built_without_stream", "no pilot without a StreamStore (D4)",
       P, "        if value is None:", '        if value is None and name != "stream":',
       "test_f_base__a_pilot_is_not_built_without_its_durable_adapters"),
    _m("pilot_built_without_objects", "no pilot without a durable object store (M)",
       P, "        if value is None:", '        if value is None and name != "objects":',
       "test_f_base__a_pilot_is_not_built_without_its_durable_adapters"),
    _m("regime_not_read", "ACCOUNTING_REGIME picks the admission (wire-in: G1R composition)",
       P, "    relay = Relay(jobs=jobs, stream=stream, media=None, regime=deployment.accounting_regime,",
       '    relay = Relay(jobs=jobs, stream=stream, media=None, regime="legacy_usd",',
       "test_f_base__the_composed_pilot_admits_in_the_configured_regime"),
    _m("active_card_not_read", "ACTIVE_RATE_CARD_VERSION reaches the relay",
       P, "                  catalog=catalog, active_rate_card_version=pilot.active_rate_card_version,",
       '                  catalog=catalog, active_rate_card_version="",',
       "test_f_base__the_composed_pilot_admits_in_the_configured_regime"),
    _m("two_large_body_bounds", "one LargeBodies per process, shared with uploads",
       P, "                       catalog=catalog, large_bodies=rt.large_bodies)",
       "                       catalog=catalog, large_bodies=intake.LargeBodies())",
       "test_f_base__one_large_body_bound_and_one_media_store_per_process"),
    _m("media_store_not_shared", "the relay stages into rt.media_store (G4U request (a))",
       P, "    relay.media = rt.media_store = MediaUploads(", "    relay.media = MediaUploads(",
       "test_f_base__one_large_body_bound_and_one_media_store_per_process"),
    _m("probe_never_refreshed", "the lifetime task refreshes the readiness answers",
       P, "        self.value = await self._answer()", "        self.value = self.value",
       "test_f_base__readiness_probes_are_cached_answers_the_lifetime_refreshes"),
    _m("probe_asked_on_every_read", "a readiness read is a cached answer, not a blocking call",
       P, "        if self.value is None:", "        if True:",
       "test_f_base__readiness_probes_are_cached_answers_the_lifetime_refreshes"),
    _m("service_role_not_set", "every pooled connection runs set role service_role (D2 7)",
       P, '        await conn.execute("set role service_role")\n', "",
       "test_f_base__the_pool_sets_the_service_role_on_every_connection"),
    _m("reconciler_not_run", "the Q3 relay runs for the process lifetime (Q3 request 2)",
       P, "    lifetime.tasks = [asyncio.create_task(lifetime.reconciler.run(stop)),\n"
          "                      asyncio.create_task(_refresh(lifetime.probes, stop))]",
       "    lifetime.tasks = [asyncio.create_task(_refresh(lifetime.probes, stop))]",
       "test_f_base__the_lifespan_runs_the_dispatch_relay_until_shutdown"),
    _m("relay_worker_id_shared", "each process's relay has its own worker id (D2 OB-1b)",
       P, '                            now=_utc_now, worker_id=f"gateway-{uuid.uuid4().hex[:8]}")',
       '                            now=_utc_now, worker_id="gateway")',
       "test_f_base__the_lifespan_runs_the_dispatch_relay_until_shutdown"),
    _m("readyz_open_behind_proxy", "a relayed loopback request is not the host's own probe",
       OR, "    return peer in LOOPBACK and not any(name in request.headers for name in PROXY_HEADERS)",
       "    return peer in LOOPBACK",
       "test_dur_rls__readiness_is_protected"),
    _m("second_chat_route_tolerated", "exactly one handler serves the metered path (G1R C4)",
       N, "    if len(served) != 1 or served[0].endpoint.__module__ != __name__:",
       "    if not served:",
       "test_f_base__exactly_one_chat_route_and_it_is_the_ingress"),
    _m("chat_route_names_intake", "the route table names the ingress as the chat handler",
       N, "    chat.__module__ = __name__\n", "",
       "test_f_base__exactly_one_chat_route_and_it_is_the_ingress"),
    # === G2 item 6: the DUR-OUTPUT drills, through the contract store ====================
    _m("prepublication_loss_not_retried", "a loss before any committed chunk is retried",
       ST, "            if job.published:\n                # After the publication marker",
       "            if True:\n                # After the publication marker",
       "test_dur_output__a_kill_before_the_first_committed_chunk_is_retried_to_one_output"),
    _m("published_output_regenerated", "a loss after the first committed chunk never reruns",
       ST, "            if job.published:\n                # After the publication marker",
       "            if False:\n                # After the publication marker",
       "test_dur_output__a_kill_after_the_first_committed_chunk_is_never_regenerated"),
)


def _definitions() -> dict[str, str]:
    """case name -> the suite-relative file that defines it."""
    where = {}
    for path in sorted((API_DIR / SUITE).glob("test_*.py")):
        if path.name == "test_mutants.py":
            continue
        for name in re.findall(r"^def (test_\w+)", path.read_text(), re.M):
            where[name] = f"{SUITE}/{path.name}"
    return where


def files_for(cases) -> set[str]:
    where = _definitions()
    return {where[case] for case in cases if case in where}


def case_names() -> set[str]:
    """Every `test_*` function this suite defines about the ingress.

    `test_mutants.py` is excluded: its cases are claims about this list, not about
    the gateway, so requiring a mutant for them would be circular.
    """
    return set(_definitions())


def _layout(root: pathlib.Path) -> pathlib.Path:
    """The repository's shape, because `test_client_smoke` drives `client_example.py`,
    which imports `models/marlin2b/bench.py`: `<tmp>/apps/infrx-api/{infrx,tests,...}`
    plus `<tmp>/models` linked to the real tree (read only; bytecode goes to the copy's
    own `PYTHONPYCACHEPREFIX`)."""
    api = root / "apps" / "infrx-api"
    junk = shutil.ignore_patterns("__pycache__")
    for name in (PACKAGE, "tests"):
        shutil.copytree(API_DIR / name, api / name, ignore=junk)
    for name in ("pyproject.toml", "client_example.py"):
        shutil.copy2(API_DIR / name, api / name)
    (root / "models").symlink_to(API_DIR.parents[1] / "models")
    return api


#: F2R item 9: the shared runner, with G's per-mutant file selection and layout.
RUNNER = Runner(name="g1", targets_for=lambda cases: sorted(files_for(cases)), layout=_layout)


def run_mutant(mutant) -> Result:
    """Apply one mutant to a throwaway copy and run the cases it names."""
    return shared.run_mutant(mutant, RUNNER)


if __name__ == "__main__":
    raise SystemExit(shared.main(MUTANTS, RUNNER, "run track G's mutation list"))
