#!/usr/bin/env node
// L4's mutant runner (R32; LANE-RULES addendum) over tests/l/ui, on the shared Lab harness.
// Usage: node tests/l/ui/run-mutants.mjs [--only ID,ID]
import { m, runMutants } from "../shell/harness.mjs";

const SUITE = ["view", "journey", "actions", "pages", "http"].map((f) => `tests/l/ui/${f}.test.ts`);
const PORT = "lib/services/control/port.ts";
const FAKE = "lib/services/control/fake.ts";
const VIEW = "lib/services/control/view.ts";
const ACTIONS = "lib/services/control/actions.ts";
const HTTP = "lib/services/control/http.ts";
const TRANSPORT = "lib/services/http.ts"; // LAB-04: the one transport every family adapter calls
const SHAPES = "lib/services/shapes.ts"; // LAB-10: the shared input shapes
const SERVER = "lib/services/control/server.ts";
const LAYOUT = "app/(provider)/layout.tsx";
const MODELS = "app/(provider)/models/page.tsx";
const DEPLOY = "app/(provider)/deployments/page.tsx";

const C = {
  v01: "L4-V01 roles mirror ROLE_CAPABILITIES: viewer reads health, developer manages dev, only administrator proposes",
  v02: "L4-V02 a row shows the pinned model, serving, runtime, schema and rate identities and where it is visible",
  v03: "L4-V03 actions follow the record and the role: smoke dev, publish only after a passed smoke, never a provider rollback",
  v04: "L4-V04 a pending proposal is shown as awaiting the operator and blocks a second one; a decided one does not",
  v05: "L4-V05 health rows carry the redacted aggregate only, whatever else a record carries",
  v06: "L4-V06 a refusal is fixed copy for a known reason and nothing for anything else in the URL",
  v07: "L4-V07 the control port fails closed: unavailable until the real adapter is wired, the preview never in production",
  j01: "L4-J01 register → dev smoke → publish proposal → operator approval → App discovery → operator rollback",
  j02: "L4-J02 unauthorized variants: another provider, a viewer, a developer proposing, an unimported model or digest, publish before smoke, a provider rollback, a repeat",
  a01: "L4-A01 register runs as the session's provider and role, whatever the form claims",
  a02: "L4-A02 a role without the capability is refused before the control service is asked",
  a03: "L4-A03 malformed input is refused as invalid and never reaches the control service",
  a04: "L4-A04 the service's refusal is carried as its reason; its success is a plain return to the records",
  a05: "L4-A05 a consumer-only user gets a 404 from every action and the control service is never asked",
  p01: "L4-P01 each page reads the control records as the session's workspace and shows ?refused= only as fixed copy",
  p02: "L4-P02 the provider layout links the L4 pages and labels the preview stand-in only when it is on",
  h01: "L4-H01 every call is the session's token and the actor's provider on its route; records come back in the port's keys, values untouched",
  h02: "L4-H02 the route's refusals are the port's reasons; anything else, or no answer, is unavailable",
  h03: "L4-H03 one unreadable model, deployment, proposal or aggregate fails the whole answer closed",
  h04: "L4-H04 without a session token, or when reading it fails, nothing is sent and every call is unavailable",
  h05: "L4-H05 controlPort() is the HTTP adapter only with LAB_CONTROL_URL and a Lab config, carrying the session's own token",
};

const MUTANTS = [
  m("L4-X01", "a viewer may manage dev deployments", PORT, 'viewer: ["read_aggregate_health"],', 'viewer: ["read_aggregate_health", "manage_dev_deployment"],', [C.v01, C.a02]),
  m("L4-X02", "a developer may propose publication", PORT, 'developer: ["read_aggregate_health", "manage_dev_deployment"],', 'developer: ["read_aggregate_health", "manage_dev_deployment", "propose_publication"],', [C.v01, C.a02, C.j02]),
  m("L4-X03", "the row shows the wrong runtime identity", VIEW, "runtime: d.runtime,", "runtime: d.modelId,", [C.v02]),
  m("L4-X04", "an unpriced revision shows a rate card", VIEW, 'd.rateCardVersion ?? "unpriced"', 'd.rateCardVersion ?? "rc-0"', [C.v02]),
  m("L4-X05", "dev and prod are not told apart", VIEW, "where: `${d.environment} · ${d.visibility}`", "where: d.visibility", [C.v02]),
  m("L4-X06", "publish is offered before a passed smoke", VIEW, 'd.environment === "dev" && d.smoke === "passed") actions.push("publish");', 'd.environment === "dev") actions.push("publish");', [C.v03]),
  m("L4-X07", "a rollback is offered to a provider", VIEW, 'actions.push("publish"); // a rollback', 'actions.push("publish");\n    if (live && !pending && d.environment === "prod" && d.visibility === "public" && holds(role, "propose_publication")) actions.push("rollback"); //', [C.v03]),
  m("L4-X08", "a retired revision still offers actions", VIEW, 'const live = d.state === "active";', "const live = true;", [C.v03]),
  m("L4-X09", "a pending proposal does not block another", VIEW, "if (live && !pending && holds(", "if (live && holds(", [C.v04]),
  m("L4-X10", "a decided proposal still reads as pending", VIEW, 'p.deploymentRevisionId === d.deploymentRevisionId && p.state === "proposed"', "p.deploymentRevisionId === d.deploymentRevisionId", [C.v04]),
  m("L4-X11", "a proposal is shown as already published", VIEW, "proposed · awaiting operator approval", "published", [C.v04]),
  m("L4-X12", "health rows pass through every field of the record", VIEW, "aggregates.map((a) => ({\n", "aggregates.map((a) => ({\n    ...a,\n", [C.v05]),
  m("L4-X13", "an idle window divides by zero", VIEW, "a.requests > 0 ? `${Math.round((a.errors / a.requests) * 1000) / 10}%` : \"—\"", "`${Math.round((a.errors / a.requests) * 1000) / 10}%`", [C.v05]),
  m("L4-X14", "any ?refused= string is looked up", VIEW, "(REFUSALS as readonly unknown[]).includes(value) ?", 'typeof value === "string" ?', [C.v06]),
  m("L4-X15", "the preview stand-in runs in production", PORT, ' && env.NODE_ENV !== "production"', "", [C.v07]),
  m("L4-X16", "the default port is the stand-in, not unavailable", PORT, "  return labControl(env) ?? UNAVAILABLE;\n}", "  return (preview ??= new FakeControl());\n}", [C.v07]),
  m("L4-X17", "any preview flag value turns the stand-in on", PORT, 'env.LAB_CONTROL_PREVIEW === "1"', "env.LAB_CONTROL_PREVIEW !== undefined", [C.v07]),
  m("L4-X18", "reads are not scoped to the provider", FAKE, "rows.filter((r) => r.providerId === actor.providerId).map(strip)", "rows.map(strip)", [C.j02]),
  m("L4-X19", "another provider's revision can be acted on", FAKE, "d.deploymentRevisionId === id && d.providerId === actor.providerId", "d.deploymentRevisionId === id", [C.j02]),
  m("L4-X20", "a foreign id is looked up before the role (the pre-L3 fake)", FAKE,
    '    if (!holds(actor.role, capability)) return "denied";\n    return this.revisions.find((d) => d.deploymentRevisionId === id && d.providerId === actor.providerId && d.environment === "dev") ?? "not_found";',
    '    const row = this.revisions.find((d) => d.deploymentRevisionId === id && d.providerId === actor.providerId && d.environment === "dev");\n    if (row === undefined) return "not_found";\n    return holds(actor.role, capability) ? row : "denied";', [C.j02]),
  m("L4-X21", "register without the capability", FAKE, '    if (!holds(actor.role, "manage_dev_deployment")) return no("denied");\n', "", [C.j02]),
  m("L4-X22", "a digest outside the model's imported weights is registered", FAKE, '    if (!model.weights.includes(r.artifactDigest)) return no("invalid"); // over one of those digests\n', "", [C.j02]),
  m("L4-X23", "smoke runs on a prod revision", FAKE, ' && d.environment === "dev") ?? "not_found";', ') ?? "not_found";', [C.j01]),
  m("L4-X24", "publish is proposed before a passed smoke", FAKE, 'if (d.state !== "active" || d.smoke !== "passed") return no("conflict");', 'if (d.state !== "active") return no("conflict");', [C.j02]),
  m("L4-X25", "a repeated proposal opens a second one", FAKE, '    if (open !== undefined) return ok(strip(open)); // R214: a repeat answers the open proposal\n', "", [C.j02]),
  m("L4-X26", "a provider rollback proposal is accepted", FAKE, '    if (kind !== "publish") return no("invalid"); // a rollback is the operator\'s listing decision\n', "", [C.j01, C.j02]),
  m("L4-X27", "publishing leaves the old revision public", FAKE, '    for (const x of live) x.visibility = "private";\n', "", [C.j01]),
  m("L4-X28", "the operator's rollback does not restore the previous revision", FAKE, '    back.visibility = "public";\n', "", [C.j01]),
  m("L4-X29", "a rejected proposal publishes", FAKE, "    if (!approve) {\n", "    if (false) {\n", [C.j02]),
  m("L4-X30", "App discovery lists every prod revision", FAKE, 'd.environment === "prod" && d.visibility === "public" && d.state === "active").map', 'd.environment === "prod").map', [C.j01]),
  m("L4-X31", "a published revision carries no rate card", FAKE, "rateCardVersion: `rc-${this.cards}`", "rateCardVersion: null", [C.j01]),
  m("L4-X32", "register acts as the form's provider", ACTIONS, "controlPort().register(actor(w),", 'controlPort().register({ providerId: String(data.get("providerId")), role: w.role },', [C.a01]),
  m("L4-X33", "the actor's role is not the session's", ACTIONS, "role: w.role });", 'role: "administrator" });', [C.a01]),
  m("L4-X34", "the capability check is skipped", ACTIONS, '!holds(w.role, capability) ? "denied" : ', "", [C.a02]),
  m("L4-X35", "malformed input reaches the control service", ACTIONS, ' : !valid ? "invalid"', "", [C.a03]),
  m("L4-X36", "any artifact reference passes the shape check", SHAPES, "DIGEST_RE = /^sha256:[0-9a-f]{64}$/;", "DIGEST_RE = /./;", [C.a03]),
  m("L4-X37", "any model name passes the shape check", ACTIONS, "const NAME = /^[a-z0-9][a-z0-9-]{0,62}$/;", "const NAME = /./;", [C.a03]),
  m("L4-X38", "an unknown proposal kind is accepted", ACTIONS, '(kind === "publish" || kind === "rollback") && id !== null', "id !== null", [C.a03]),
  m("L4-X39", "a refusal is dropped on the way back", ACTIONS, "redirect(result.ok ? page : `${page}?refused=${result.reason}`);", "redirect(page);", [C.a02, C.a04]),
  m("L4-X40", "a success is flagged by the action, not the records", ACTIONS, "redirect(result.ok ? page :", "redirect(result.ok ? `${page}?done=1` :", [C.a01, C.a04]),
  m("L4-X41", "proposing needs only the dev capability", ACTIONS, '"propose_publication", valid', '"manage_dev_deployment", valid', [C.a02]),
  m("L4-X42", "an action runs without a provider workspace", ACTIONS, "export async function smokeDeployment(data: FormData): Promise<void> {\n  const w = await requireProviderWorkspace();",
    'export async function smokeDeployment(data: FormData): Promise<void> {\n  const w = { providerId: "x", providerName: "x", role: "administrator" } as const;', [C.a05]),
  m("L4-X43", "a page reads records as a fixed provider", DEPLOY, "{ providerId: workspace.providerId, role: workspace.role }", '{ providerId: "11111111-1111-4111-8111-111111111111", role: workspace.role }', [C.p01]),
  m("L4-X44", "a page shows ?refused= raw", MODELS, "const refused = refusalCopy((await searchParams).refused);", 'const refused = String((await searchParams).refused ?? "") || null;', [C.p01]),
  m("L4-X45", "a page claims success on its own", DEPLOY, "<h1>Deployments</h1>", "<h1>Deployments</h1>\n      <p>Published successfully.</p>", [C.p01]),
  m("L4-X46", "the nav loses the deployments page", LAYOUT, '<Link href="/deployments">Deployments</Link>', "Deployments", [C.p02]),
  m("L4-X47", "the preview label shows when the stand-in is off", LAYOUT, '{isPreview() && <p role="note">', '{<p role="note">', [C.p02]),
  m("L4-X48", "the session token is not forwarded", TRANSPORT, "authorization: `Bearer ${bearer}`", "authorization: \"Bearer service\"", [C.h01, C.h05]),
  m("L4-X49", "the actor's provider is not sent", TRANSPORT, "?provider_org_id=${encodeURIComponent(actor.providerId)}", "", [C.h01, C.h05]),
  m("L4-X50", "a signed-out call is still sent", TRANSPORT, "    if (!bearer) return { ok: false, reason: \"unavailable\" }; // no session: nothing is sent\n", "", [C.h04]),
  m("L4-X51", "an unreadable session throws instead of failing closed", TRANSPORT, "await token().catch(() => null);", "await token();", [C.h04]),
  m("L4-X52", "a 401 is not denied", TRANSPORT, "401: \"denied\", ", "", [C.h02]),
  m("L4-X53", "a 403 reads as not_found", TRANSPORT, "403: \"denied\"", "403: \"not_found\"", [C.h02]),
  m("L4-X54", "409 and 422 are swapped", TRANSPORT, "409: \"conflict\", 422: \"invalid\"", "409: \"invalid\", 422: \"conflict\"", [C.h02]),
  m("L4-X55", "an unknown status is a conflict, not unavailable", TRANSPORT, "?? \"unavailable\" };", "?? \"conflict\" };", [C.h02]),
  m("L4-X56", "a transport failure throws", TRANSPORT, "return { ok: false, reason: \"unavailable\" }; // transport", "throw new Error(\"down\"); // transport", [C.h02]),
  m("L4-X57", "records are not checked", TRANSPORT, "return readable(value) ?", "return true ?", [C.h03]),
  m("L4-X58", "any environment is read", HTTP, 'environment: oneOf("dev", "prod")', "environment: str", [C.h03]),
  m("L4-X59", "any visibility is read", HTTP, 'visibility: oneOf("private", "public")', "visibility: str", [C.h03]),
  m("L4-X60", "any deployment state is read", HTTP, 'state: oneOf("active", "retired")', "state: str", [C.h03]),
  m("L4-X61", "any smoke value is read", HTTP, 'smoke: oneOf("none", "passed", "failed")', "smoke: str", [C.h03]),
  m("L4-X62", "a missing rate card field is read", HTTP, "rateCardVersion: nul(str),", "rateCardVersion: () => true,", [C.h03]),
  m("L4-X63", "a model without its digest is read", HTTP, "artifactDigest: str, schemaVersion: str, runtime: str, registeredAt: str", "schemaVersion: str, runtime: str", [C.h03]),
  m("L4-X64", "any proposal state is read", HTTP, 'state: oneOf("proposed", "approved", "rejected")', "state: str", [C.h03]),
  m("L4-X65", "any proposal kind is read", HTTP, 'kind: oneOf("publish", "rollback")', "kind: str", [C.h03]),
  m("L4-X66", "a proposal without its decision field is read", HTTP, "decidedAt: nul(str)", "decidedAt: () => true", [C.h03]),
  m("L4-X67", "aggregate counts are not checked", HTTP, "requests: num, errors: num, p95LatencyMs: nul(num)", "requests: () => true, errors: num", [C.h03]),
  m("L4-X68", "records keep the route's snake_case", HTTP, "labClient(options, \"/lab/v1/control\", { rename: camel })", "labClient(options, \"/lab/v1/control\")", [C.h01]),
  m("L4-X69", "a read is not unwrapped from {data}", TRANSPORT, "read: Answer = (p) => keys(p.data)", "read: Answer = (p) => keys(p)", [C.h01]),
  m("L4-X70", "the registration body is sent in camelCase", HTTP, "artifact_digest: r.artifactDigest, schema_version: r.schemaVersion", "artifactDigest: r.artifactDigest, schemaVersion: r.schemaVersion", [C.h01]),
  m("L4-X71", "the proposal body names the revision in camelCase", HTTP, "{ kind, deployment_revision_id: id }", "{ kind, deploymentRevisionId: id }", [C.h01]),
  m("L4-X72", "a revision id reaches the path unencoded", HTTP, "`deployments/${encodeURIComponent(id)}/smoke`", "`deployments/${id}/smoke`", [C.h01]),
  m("L4-X73", "every call claims a JSON body", TRANSPORT, "if (body !== undefined) headers[\"content-type\"]", "headers[\"content-type\"]", [C.h01]),
  m("L4-X74", "smoke is a read", HTTP, "post(actor, `deployments/", "get(actor, `deployments/", [C.h01]),
  m("L4-X75", "a trailing slash on the base URL doubles", TRANSPORT, "baseUrl.replace(/\\/+$/, \"\")", "baseUrl", [C.h01]),
  m("L4-X86", "a 410 reads as gone in a family that has no gone", TRANSPORT, "422: \"invalid\" }", "422: \"invalid\", 410: \"gone\" }", [C.h02]),
  m("L4-X76", "the adapter runs without LAB_CONTROL_URL", SERVER, "if (!baseUrl || config === null) return null;\n  return httpControl({ baseUrl,", "if (config === null) return null;\n  return httpControl({ baseUrl: baseUrl ?? \"\",", [C.h05]),
  m("L4-X77", "the adapter carries a fixed credential, not the session's", SERVER, "token: sessionToken(config)", 'token: async () => "service"', [C.h05]),
  m("L4-X87", "the control adapter reads another family's old name", SERVER, "labApiUrl(env, \"control\")", "labApiUrl(env, \"traces\")", [C.h05]),
  m("L4-X78", "controlPort() never uses the adapter", PORT, "return labControl(env) ?? UNAVAILABLE;", "return UNAVAILABLE;", [C.h05]),
  m("L4-X79", "a repeated proposal is a conflict (the pre-R214 fake)", FAKE, "return ok(strip(open));", 'return no("conflict");', [C.j02]),
  m("L4-X80", "a provider rollback is refused as a conflict, not invalid", FAKE, 'return no("invalid"); // a rollback', 'return no("conflict"); // a rollback', [C.j01, C.j02]),
  m("L4-X81", "any name registers the workspace's model", FAKE, 'm.modelId.split("/").at(-1) === r.name', 'm.modelId.split("/").at(-1) === m.modelId.split("/").at(-1)', [C.j02]),
  m("L4-X82", "another provider's imported model is registered", FAKE, 'this.imported.find((m) => m.providerId === actor.providerId && ', "this.imported.find((m) => ", [C.j02]),
  m("L4-X83", "a registration is its own model, not the imported one", FAKE, "const { modelId } = model;", "const modelId = r.name;", [C.j01]),
  m("L4-X85", "a developer may propose to the fake", FAKE, '    if (!holds(actor.role, "propose_publication")) return no("denied");\n', "", [C.j02]),
  m("L4-X84", "the operator's rollback leaves the rolled-back revision public", FAKE, '    live.visibility = "private";\n', "", [C.j01]),
];

process.exit(await runMutants({ suite: SUITE, prefix: "L4", mutants: MUTANTS }));
